# -*- coding: utf-8 -*-
"""budget_optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYy06jYKvHgFln0yCMATFMrEbkzYF4pO
"""

# -*- coding: utf-8 -*-
"""
budget_optimisation.py
======================
MapleThread Outdoor Co. — MMM Phase 6: Budget Optimisation

Turns the Phase 4 hierarchical posterior into a decision tool. For each region,
we find the budget allocation across channels that maximises expected revenue,
subject to a total budget constraint equal to current spend.

Approach
--------
For each posterior draw we have a complete set of channel parameters (alpha, k,
ec, beta). We treat these as the "true" parameters for that draw and solve a
constrained optimisation over the budget allocation vector using SciPy SLSQP.
Collecting optimal allocations across all draws gives us a posterior distribution
over the optimal budget — an honest recommendation with quantified uncertainty.

We also run this across a range of total budget scenarios (50%–200% of current)
to produce budget response curves: how does optimal revenue change as total
budget increases?

Revenue model used in optimiser (per channel c, single-period approximation)
-----------------------------------------------------------------------------
    adstock_c(s_c) ≈ s_c / (1 - alpha_c)      [steady-state geometric adstock]
    adstock_norm_c = adstock_c / p95_c
    saturation_c   = Hill(adstock_norm_c; k_c, ec_c)
    contribution_c = beta_c × saturation_c

The steady-state approximation treats each week as a representative period with
constant spend s_c, giving a clean closed-form that is differentiable and fast
to optimise. This is standard practice in MMM budget tools.

Sections
--------
  1. Imports & Config
  2. Data Loading
  3. Steady-State Revenue Model
  4. Single-Draw Optimisation
  5. Posterior Optimisation (main loop)
  6. Budget Response Curves
  7. Visualisation
  8. Results Table
  9. Entry Point

Run with:
    python budget_optimisation.py

Dependencies:
    outputs/idata_hierarchical.nc   ← saved by Phase 4
    outputs/roas_summary.csv        ← saved by Phase 5
    synthetic_raw.csv               ← raw spend data

Outputs (saved to outputs/):
    fig_optimal_allocation.png      ← current vs optimal spend per channel/region
    fig_budget_response_curves.png  ← optimal revenue across budget scenarios
    fig_allocation_uncertainty.png  ← posterior distribution of optimal allocations
    budget_recommendations.csv      ← full recommendation table
"""

from __future__ import annotations

import os
import warnings
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import arviz as az
from scipy.optimize import minimize

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)

os.makedirs("outputs", exist_ok=True)


# ══════════════════════════════════════════════════════════════════════════════
# 1. CONFIG
# ══════════════════════════════════════════════════════════════════════════════

REGIONS  = ["canada", "united_states", "germany", "japan", "australia"]
CHANNELS = ["tv", "paid_search", "social", "display"]
N_REGIONS = len(REGIONS)
N_CHANNELS = len(CHANNELS)
N_WEEKS    = 156
MAX_LAG    = 52
RANDOM_SEED = 42

REGION_LABELS = {
    "canada":        "Canada",
    "united_states": "United States",
    "germany":       "Germany",
    "japan":         "Japan",
    "australia":     "Australia",
}
CHANNEL_LABELS = {
    "tv":          "TV",
    "paid_search": "Paid Search",
    "social":      "Social",
    "display":     "Display",
}

# Ground truth adstock alphas — used for p95 normalisation constants
TRUE_ALPHAS = {
    "tv": 0.75, "paid_search": 0.20, "social": 0.45, "display": 0.15,
}

# Budget scenario multipliers (fraction of current total spend)
BUDGET_SCENARIOS = [0.50, 0.75, 1.00, 1.25, 1.50, 1.75, 2.00]

# Number of posterior draws to use for optimisation
# Full 4000 draws takes ~10–20 min; 500 gives reliable results in ~2 min
N_OPT_DRAWS = 500

PALETTE = {
    "tv":            "#E63946",
    "paid_search":   "#2A9D8F",
    "social":        "#F4A261",
    "display":       "#457B9D",
    "current":       "#6C757D",
    "optimal":       "#1D3557",
    "canada":        "#E63946",
    "united_states": "#2A9D8F",
    "germany":       "#F4A261",
    "japan":         "#6A4C93",
    "australia":     "#E9C46A",
}

plt.rcParams.update({
    "font.family":       "DejaVu Sans",
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "axes.grid":         True,
    "grid.alpha":        0.3,
    "grid.linestyle":    "--",
    "figure.facecolor":  "#FAFAFA",
    "axes.facecolor":    "#FAFAFA",
})


# ══════════════════════════════════════════════════════════════════════════════
# 2. DATA LOADING
# ══════════════════════════════════════════════════════════════════════════════

def load_idata(path: str = "idata_hierarchical.nc") -> az.InferenceData:
    """Load Phase 4 InferenceData."""
    print(f"  Loading InferenceData from {path}...")
    idata = az.from_netcdf(path)
    chains = idata.posterior.dims["chain"]
    draws  = idata.posterior.dims["draw"]
    print(f"  Chains: {chains}  Draws: {draws}  Total: {chains * draws}")
    return idata


def load_raw_data(path: str = "synthetic_raw.csv") -> pd.DataFrame:
    """Load raw spend data to compute current budgets."""
    raw_df = pd.read_csv(path, parse_dates=["date"])
    print(f"  Loaded {len(raw_df)} rows from {path}.")
    return raw_df


def compute_current_budgets(raw_df: pd.DataFrame) -> dict:
    """
    Compute mean weekly spend per channel per region from the raw data.

    This is the "current budget" the optimiser will constrain against.
    Using the mean over 156 weeks gives a representative steady-state
    spend level that matches the steady-state revenue model assumption.

    Returns
    -------
    dict: region → {channel: mean_weekly_spend}
    """
    budgets = {}
    for region in REGIONS:
        df = raw_df[raw_df["region"] == region]
        budgets[region] = {
            ch: float(df[f"spend_{ch}"].mean()) for ch in CHANNELS
        }
    return budgets


def compute_p95_constants(raw_df: pd.DataFrame) -> dict:
    """
    Recompute p95 normalisation constants — identical to Phase 4/5.

    Returns
    -------
    dict: {channel: np.ndarray of shape (R,)}
    """
    lags = np.arange(MAX_LAG, dtype=float)
    p95  = {ch: [] for ch in CHANNELS}

    for region in REGIONS:
        df = raw_df[raw_df["region"] == region].reset_index(drop=True)
        for ch in CHANNELS:
            spend = df[f"spend_{ch}"].values.astype(float)
            T     = len(spend)
            lag_mat = np.zeros((T, MAX_LAG), dtype=float)
            for l in range(MAX_LAG):
                lag_mat[l:, l] = spend[:T - l]
            weights  = TRUE_ALPHAS[ch] ** lags
            ads_true = lag_mat @ weights
            p95[ch].append(float(np.percentile(ads_true, 95)))

    return {ch: np.array(p95[ch]) for ch in CHANNELS}   # (R,)


def extract_posterior_samples(idata: az.InferenceData,
                               n_draws: int = N_OPT_DRAWS) -> dict:
    """
    Extract and subsample posterior draws for optimisation.

    We subsample to `n_draws` to keep optimisation tractable. Draws are
    selected with a fixed random seed for reproducibility. Using 500 draws
    gives stable results — the distribution of optimal allocations converges
    well before 4000 draws.

    Returns
    -------
    dict: param_name → np.ndarray of shape (n_draws, R)
    """
    posterior = idata.posterior
    chains    = posterior.dims["chain"]
    draws     = posterior.dims["draw"]
    D         = chains * draws

    rng     = np.random.default_rng(RANDOM_SEED)
    indices = rng.choice(D, size=min(n_draws, D), replace=False)

    per_region_params = [
        "alpha_tv",   "alpha_ps",   "alpha_so",   "alpha_disp",
        "k_tv",       "k_ps",       "k_so",       "k_disp",
        "ec_tv",      "ec_ps",      "ec_so",      "ec_disp",
        "beta_tv",    "beta_ps",    "beta_so",    "beta_disp",
    ]

    samples = {}
    for p in per_region_params:
        if p in posterior:
            arr = posterior[p].values.reshape(D, N_REGIONS)
            samples[p] = arr[indices]   # (n_draws, R)

    print(f"  Extracted {len(indices)} posterior draws for optimisation.")
    return samples


# ══════════════════════════════════════════════════════════════════════════════
# 3. STEADY-STATE REVENUE MODEL
# ══════════════════════════════════════════════════════════════════════════════

def steady_state_adstock(spend: np.ndarray, alpha: float | np.ndarray) -> np.ndarray:
    """
    Steady-state geometric adstock for constant weekly spend s:

        adstock_ss = s / (1 - alpha)

    This is the fixed point of the adstock recursion when spend is constant.
    It gives a clean, differentiable approximation suitable for optimisation.

    Parameters
    ----------
    spend : np.ndarray, shape (C,) — weekly spend per channel
    alpha : scalar or (C,) — adstock decay rates

    Returns
    -------
    np.ndarray, shape (C,) — steady-state adstock
    """
    return spend / (1.0 - alpha + 1e-8)


def hill_saturation_np(x: np.ndarray, k: np.ndarray,
                        ec: np.ndarray) -> np.ndarray:
    """Vectorised Hill saturation over arrays."""
    safe_x = np.where(x <= 0, 1e-10, x)
    return safe_x**k / (safe_x**k + ec**k)


def predict_revenue(spend_vec: np.ndarray,
                    alpha_vec: np.ndarray,
                    k_vec:     np.ndarray,
                    ec_vec:    np.ndarray,
                    beta_vec:  np.ndarray,
                    p95_vec:   np.ndarray) -> float:
    """
    Predict total media revenue for a given spend allocation.

    This is the objective function the optimiser maximises. It does NOT
    include baseline revenue (which is unaffected by spend allocation),
    so we are maximising incremental media-driven revenue.

    Parameters
    ----------
    spend_vec : (C,) — proposed weekly spend per channel
    alpha_vec : (C,) — adstock decay rates
    k_vec     : (C,) — Hill slope parameters
    ec_vec    : (C,) — Hill half-saturation parameters
    beta_vec  : (C,) — channel revenue coefficients
    p95_vec   : (C,) — p95 normalisation constants

    Returns
    -------
    float — total predicted media revenue contribution
    """
    adstock_ss   = steady_state_adstock(spend_vec, alpha_vec)
    adstock_norm = adstock_ss / (p95_vec + 1e-8)
    saturation   = hill_saturation_np(adstock_norm, k_vec, ec_vec)
    return float(np.sum(beta_vec * saturation))


# ══════════════════════════════════════════════════════════════════════════════
# 4. SINGLE-DRAW OPTIMISATION
# ══════════════════════════════════════════════════════════════════════════════

def optimise_single_draw(alpha_vec:    np.ndarray,
                          k_vec:        np.ndarray,
                          ec_vec:       np.ndarray,
                          beta_vec:     np.ndarray,
                          p95_vec:      np.ndarray,
                          current_spend: np.ndarray,
                          total_budget:  float,
                          spend_bounds:  list[tuple]) -> np.ndarray:
    """
    Solve the budget optimisation for a single posterior draw.

    Problem
    -------
    Maximise:   Σ_c beta_c × Hill(adstock_ss_c / p95_c ; k_c, ec_c)
    Subject to: Σ_c s_c = total_budget   (equality)
                lb_c ≤ s_c ≤ ub_c         (bounds per channel)

    Solver: SLSQP (Sequential Least Squares Programming) from SciPy.
    This handles both equality constraints and bounds natively and is
    well-suited to smooth nonlinear objectives of this form.

    Initialisation: proportional to current spend (feasible starting point).
    We also try a uniform initialisation and take the better result to reduce
    sensitivity to starting point.

    Parameters
    ----------
    spend_bounds : list of (lb, ub) per channel
        Lower bound: 10% of current spend (don't zero out any channel).
        Upper bound: 300% of current spend (prevent degenerate solutions).

    Returns
    -------
    np.ndarray, shape (C,) — optimal spend allocation for this draw
    """
    def neg_revenue(s):
        return -predict_revenue(s, alpha_vec, k_vec, ec_vec, beta_vec, p95_vec)

    constraints = [{"type": "eq", "fun": lambda s: s.sum() - total_budget}]

    # Initialisation 1: proportional to current spend (always feasible)
    x0_prop = current_spend * (total_budget / current_spend.sum())

    # Initialisation 2: uniform allocation
    x0_unif = np.full(N_CHANNELS, total_budget / N_CHANNELS)
    # Clip to bounds
    x0_unif = np.clip(x0_unif,
                       [b[0] for b in spend_bounds],
                       [b[1] for b in spend_bounds])
    x0_unif = x0_unif * (total_budget / x0_unif.sum())

    best_result = None
    best_val    = np.inf

    for x0 in [x0_prop, x0_unif]:
        result = minimize(
            neg_revenue,
            x0,
            method="SLSQP",
            bounds=spend_bounds,
            constraints=constraints,
            options={"ftol": 1e-9, "maxiter": 500, "disp": False},
        )
        if result.success and result.fun < best_val:
            best_val    = result.fun
            best_result = result

    if best_result is None or not best_result.success:
        # Fallback: return proportional allocation if optimiser fails
        return x0_prop

    return best_result.x


# ══════════════════════════════════════════════════════════════════════════════
# 5. POSTERIOR OPTIMISATION (main loop)
# ══════════════════════════════════════════════════════════════════════════════

def run_posterior_optimisation(samples:       dict,
                                p95_constants: dict,
                                current_budgets: dict,
                                budget_multiplier: float = 1.0) -> dict:
    """
    Run budget optimisation across all posterior draws for all regions.

    For each draw d and region r, we:
      1. Extract per-channel parameters (alpha, k, ec, beta).
      2. Define the total budget = budget_multiplier × current_total_spend[r].
      3. Define per-channel bounds = [10% current, 300% current] (capped at budget).
      4. Call optimise_single_draw to get optimal spend allocation.
      5. Compute predicted revenue at optimal vs. current allocation.

    Returns
    -------
    dict: region → {
        "optimal_spend":    (n_draws, C) — optimal spend per draw
        "optimal_revenue":  (n_draws,)   — predicted media revenue at optimal
        "current_revenue":  (n_draws,)   — predicted media revenue at current
        "revenue_uplift":   (n_draws,)   — optimal - current (absolute)
        "pct_uplift":       (n_draws,)   — uplift as % of current
        "current_spend":    (C,)         — mean current spend per channel
        "total_budget":     float        — total budget used
    }
    """
    ch_param_keys = {
        "tv":          ("alpha_tv",   "k_tv",   "ec_tv",   "beta_tv"),
        "paid_search": ("alpha_ps",   "k_ps",   "ec_ps",   "beta_ps"),
        "social":      ("alpha_so",   "k_so",   "ec_so",   "beta_so"),
        "display":     ("alpha_disp", "k_disp", "ec_disp", "beta_disp"),
    }

    n_draws = next(iter(samples.values())).shape[0]
    results = {}

    for r, region in enumerate(REGIONS):
        current_spend = np.array([
            current_budgets[region][ch] for ch in CHANNELS
        ])
        total_budget = float(current_spend.sum() * budget_multiplier)

        # Per-channel bounds: [10% current, 300% current], clipped to total_budget
        spend_bounds = [
            (max(0.10 * current_spend[c], 1.0),
             min(3.00 * current_spend[c], total_budget * 0.9))
            for c in range(N_CHANNELS)
        ]

        p95_vec = np.array([p95_constants[ch][r] for ch in CHANNELS])

        optimal_spend   = np.zeros((n_draws, N_CHANNELS))
        optimal_revenue = np.zeros(n_draws)
        current_revenue = np.zeros(n_draws)

        for d in range(n_draws):
            alpha_vec = np.array([
                float(samples[ch_param_keys[ch][0]][d, r]) for ch in CHANNELS
            ])
            k_vec = np.array([
                float(samples[ch_param_keys[ch][1]][d, r]) for ch in CHANNELS
            ])
            ec_vec = np.array([
                float(samples[ch_param_keys[ch][2]][d, r]) for ch in CHANNELS
            ])
            beta_vec = np.array([
                float(samples[ch_param_keys[ch][3]][d, r]) for ch in CHANNELS
            ])

            opt_spend = optimise_single_draw(
                alpha_vec, k_vec, ec_vec, beta_vec, p95_vec,
                current_spend, total_budget, spend_bounds,
            )

            opt_rev  = predict_revenue(opt_spend,    alpha_vec, k_vec, ec_vec, beta_vec, p95_vec)
            curr_rev = predict_revenue(current_spend, alpha_vec, k_vec, ec_vec, beta_vec, p95_vec)

            optimal_spend[d]   = opt_spend
            optimal_revenue[d] = opt_rev
            current_revenue[d] = curr_rev

        revenue_uplift = optimal_revenue - current_revenue
        pct_uplift     = revenue_uplift / (current_revenue + 1e-8) * 100

        results[region] = {
            "optimal_spend":   optimal_spend,
            "optimal_revenue": optimal_revenue,
            "current_revenue": current_revenue,
            "revenue_uplift":  revenue_uplift,
            "pct_uplift":      pct_uplift,
            "current_spend":   current_spend,
            "total_budget":    total_budget,
        }

        mean_uplift = float(revenue_uplift.mean())
        mean_pct    = float(pct_uplift.mean())
        print(f"    {REGION_LABELS[region]:>15s}: "
              f"mean uplift = ${mean_uplift:>8,.0f}/wk  "
              f"({mean_pct:+.1f}%)")

    return results


# ══════════════════════════════════════════════════════════════════════════════
# 6. BUDGET RESPONSE CURVES
# ══════════════════════════════════════════════════════════════════════════════

def run_budget_response_curves(samples:        dict,
                                p95_constants:  dict,
                                current_budgets: dict) -> dict:
    """
    Run optimisation across a range of total budget levels per region.

    For each budget scenario (50%–200% of current) and each posterior draw,
    we find the optimal allocation and record the resulting revenue.

    This answers: "What happens to optimal revenue as we increase or decrease
    the total marketing budget?" — the primary strategic planning question.

    We use a subset of draws (N_OPT_DRAWS // 2) per scenario to keep
    runtime manageable while preserving uncertainty estimates.

    Returns
    -------
    dict: region → {scenario_multiplier: {"mean_rev", "lo90_rev", "hi90_rev"}}
    """
    ch_param_keys = {
        "tv":          ("alpha_tv",   "k_tv",   "ec_tv",   "beta_tv"),
        "paid_search": ("alpha_ps",   "k_ps",   "ec_ps",   "beta_ps"),
        "social":      ("alpha_so",   "k_so",   "ec_so",   "beta_so"),
        "display":     ("alpha_disp", "k_disp", "ec_disp", "beta_disp"),
    }

    # Use half the draws per scenario — sufficient for smooth curves
    n_draws_rc = max(100, N_OPT_DRAWS // 2)
    n_draws    = next(iter(samples.values())).shape[0]
    rng        = np.random.default_rng(RANDOM_SEED + 1)
    draw_idx   = rng.choice(n_draws, size=min(n_draws_rc, n_draws), replace=False)

    response = {}

    for r, region in enumerate(REGIONS):
        response[region] = {}
        current_spend = np.array([
            current_budgets[region][ch] for ch in CHANNELS
        ])
        p95_vec = np.array([p95_constants[ch][r] for ch in CHANNELS])

        for mult in BUDGET_SCENARIOS:
            total_budget = float(current_spend.sum() * mult)
            spend_bounds = [
                (max(0.10 * current_spend[c], 1.0),
                 min(3.00 * current_spend[c], total_budget * 0.9))
                for c in range(N_CHANNELS)
            ]

            rev_draws = np.zeros(len(draw_idx))

            for i, d in enumerate(draw_idx):
                alpha_vec = np.array([float(samples[ch_param_keys[ch][0]][d, r]) for ch in CHANNELS])
                k_vec     = np.array([float(samples[ch_param_keys[ch][1]][d, r]) for ch in CHANNELS])
                ec_vec    = np.array([float(samples[ch_param_keys[ch][2]][d, r]) for ch in CHANNELS])
                beta_vec  = np.array([float(samples[ch_param_keys[ch][3]][d, r]) for ch in CHANNELS])

                opt_spend = optimise_single_draw(
                    alpha_vec, k_vec, ec_vec, beta_vec, p95_vec,
                    current_spend, total_budget, spend_bounds,
                )
                rev_draws[i] = predict_revenue(
                    opt_spend, alpha_vec, k_vec, ec_vec, beta_vec, p95_vec
                )

            response[region][mult] = {
                "mean_rev": float(rev_draws.mean()),
                "lo90_rev": float(np.percentile(rev_draws,  5)),
                "hi90_rev": float(np.percentile(rev_draws, 95)),
                "total_budget": total_budget,
            }

        print(f"    {REGION_LABELS[region]:>15s}: response curves complete.")

    return response


# ══════════════════════════════════════════════════════════════════════════════
# 7. VISUALISATION
# ══════════════════════════════════════════════════════════════════════════════

def plot_optimal_allocation(opt_results: dict,
                             save_path: str = "outputs/fig_optimal_allocation.png"):
    """
    Current vs. optimal spend per channel per region.

    Two panel types per region:
      Left:  Grouped bar chart — current spend (grey) vs posterior mean optimal (coloured).
             Error bars on optimal bars show 90% credible interval.
      Right: Net reallocation arrows — how much budget shifts from/to each channel.

    This is the primary business recommendation output.
    """
    print("\n  Plotting optimal allocation...")

    fig, axes = plt.subplots(N_REGIONS, 2, figsize=(14, 4.5 * N_REGIONS))
    fig.suptitle(
        "MapleThread — Current vs. Optimal Budget Allocation\n"
        "Grey = current spend  |  Coloured = posterior mean optimal  |  "
        "Error bar = 90% credible interval",
        fontsize=13, fontweight="bold", y=1.005,
    )

    for r, region in enumerate(REGIONS):
        res           = opt_results[region]
        current_spend = res["current_spend"]          # (C,)
        opt_draws     = res["optimal_spend"]           # (n_draws, C)

        opt_mean = opt_draws.mean(axis=0)
        opt_lo   = np.percentile(opt_draws,  5, axis=0)
        opt_hi   = np.percentile(opt_draws, 95, axis=0)

        x_pos = np.arange(N_CHANNELS)
        width = 0.35

        # ── Left: grouped bars ────────────────────────────────────────────────
        ax = axes[r, 0]
        ax.bar(x_pos - width / 2, current_spend / 1e3, width,
               color=PALETTE["current"], alpha=0.75, label="Current", zorder=3)
        ax.bar(x_pos + width / 2, opt_mean / 1e3, width,
               color=[PALETTE[ch] for ch in CHANNELS], alpha=0.82,
               label="Optimal (mean)", zorder=3)
        yerr_lo = np.clip((opt_mean - opt_lo) / 1e3, 0, None)
        yerr_hi = np.clip((opt_hi - opt_mean) / 1e3, 0, None)
        ax.errorbar(
            x_pos + width / 2, opt_mean / 1e3,
            yerr=[yerr_lo, yerr_hi],
            fmt="none", color="black", capsize=4, elinewidth=1.5,
            capthick=1.5, zorder=4,
        )

        ax.set_xticks(x_pos)
        ax.set_xticklabels([CHANNEL_LABELS[ch] for ch in CHANNELS],
                            fontsize=9, rotation=15, ha="right")
        ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x:.0f}K"))
        ax.set_ylabel("Weekly Spend ($K)", fontsize=9)
        ax.set_title(f"{REGION_LABELS[region]} — Spend Allocation",
                     fontsize=10, fontweight="bold", color=PALETTE[region])
        ax.legend(fontsize=8, loc="upper right")

        # ── Right: net reallocation ───────────────────────────────────────────
        ax2 = axes[r, 1]
        delta = (opt_mean - current_spend) / 1e3

        colors = [PALETTE[ch] if d >= 0 else PALETTE["current"]
                  for ch, d in zip(CHANNELS, delta)]
        bars = ax2.barh(np.arange(N_CHANNELS), delta, color=colors,
                        alpha=0.82, height=0.5, zorder=3)
        ax2.axvline(0, color="black", lw=1.2, alpha=0.7)

        for i, (d, lo, hi, ch) in enumerate(zip(
            delta,
            (opt_lo - current_spend) / 1e3,
            (opt_hi - current_spend) / 1e3,
            CHANNELS,
        )):
            xerr_lo = max(d - lo, 0)
            xerr_hi = max(hi - d, 0)
            ax2.errorbar(d, i,
                         xerr=[[xerr_lo], [xerr_hi]],
                         fmt="none", color="black",
                         capsize=4, elinewidth=1.5, capthick=1.5, zorder=4)
            sign = "+" if d >= 0 else ""
            ax2.text(d + (0.3 if d >= 0 else -0.3), i,
                     f"{sign}${d:.1f}K", va="center",
                     ha="left" if d >= 0 else "right",
                     fontsize=8, fontweight="bold", color=PALETTE[ch])

        ax2.set_yticks(np.arange(N_CHANNELS))
        ax2.set_yticklabels([CHANNEL_LABELS[ch] for ch in CHANNELS], fontsize=9)
        ax2.xaxis.set_major_formatter(
            mticker.FuncFormatter(lambda x, _: f"${x:+.0f}K"))
        ax2.set_xlabel("Weekly Spend Change ($K)", fontsize=9)
        ax2.set_title(f"{REGION_LABELS[region]} — Net Reallocation",
                      fontsize=10, fontweight="bold", color=PALETTE[region])

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Optimal allocation plot saved: {save_path}")


def plot_budget_response_curves(response: dict,
                                 current_budgets: dict,
                                 save_path: str = "outputs/fig_budget_response_curves.png"):
    """
    Optimal media revenue vs. total budget level for each region.

    The x-axis shows total budget as a multiple of current spend.
    The y-axis shows optimal media revenue contribution (not total revenue —
    baseline is excluded as it is budget-independent).

    The curve shape reveals:
      - Steep slope at low budgets = high marginal returns (underinvested)
      - Flattening at high budgets = diminishing returns at scale
      - The "elbow" = approximate efficient frontier point

    Shaded band = 90% credible interval across posterior draws.
    """
    print("\n  Plotting budget response curves...")

    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    axes_flat = axes.flatten()
    fig.suptitle(
        "MapleThread — Budget Response Curves\n"
        "Optimal media revenue at each total budget level  |  "
        "Shaded = 90% credible interval  |  ★ = current budget",
        fontsize=13, fontweight="bold",
    )

    for r, region in enumerate(REGIONS):
        ax    = axes_flat[r]
        color = PALETTE[region]

        current_total = sum(current_budgets[region].values())
        budgets       = [response[region][m]["total_budget"] for m in BUDGET_SCENARIOS]
        means         = [response[region][m]["mean_rev"] for m in BUDGET_SCENARIOS]
        lo90s         = [response[region][m]["lo90_rev"] for m in BUDGET_SCENARIOS]
        hi90s         = [response[region][m]["hi90_rev"] for m in BUDGET_SCENARIOS]

        budgets_k = [b / 1e3 for b in budgets]
        means_k   = [m / 1e3 for m in means]
        lo90s_k   = [l / 1e3 for l in lo90s]
        hi90s_k   = [h / 1e3 for h in hi90s]

        ax.fill_between(budgets_k, lo90s_k, hi90s_k, alpha=0.2, color=color)
        ax.plot(budgets_k, means_k, color=color, lw=2.5, marker="o",
                markersize=6, label="Mean optimal revenue")

        # Current budget marker
        current_idx = BUDGET_SCENARIOS.index(1.0)
        ax.scatter([budgets_k[current_idx]], [means_k[current_idx]],
                   color=color, s=200, marker="*", zorder=5,
                   label="Current budget", edgecolors="black", linewidths=0.8)

        ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x:.0f}K"))
        ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x:.0f}K"))
        ax.set_xlabel("Total Weekly Budget ($K)", fontsize=9)
        ax.set_ylabel("Optimal Media Revenue ($K)", fontsize=9)
        ax.set_title(REGION_LABELS[region], fontsize=11,
                     fontweight="bold", color=color)
        ax.legend(fontsize=8, loc="lower right")

    # Hide unused subplot (6th panel for 5 regions)
    axes_flat[-1].set_visible(False)

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Budget response curves saved: {save_path}")


def plot_allocation_uncertainty(opt_results: dict,
                                 save_path: str = "outputs/fig_allocation_uncertainty.png"):
    """
    Posterior distribution of optimal spend per channel per region.

    Violin plots showing the full posterior distribution of optimal spend
    for each channel, giving an honest picture of how much uncertainty
    exists in the recommendation.

    Wide violins = high parameter uncertainty → recommendation should be
    treated as directional, not prescriptive.
    Narrow violins = strong posterior agreement → high confidence in number.
    """
    print("\n  Plotting allocation uncertainty...")

    fig, axes = plt.subplots(1, N_REGIONS, figsize=(4.5 * N_REGIONS, 6),
                              sharey=False)
    fig.suptitle(
        "MapleThread — Posterior Distribution of Optimal Spend per Channel\n"
        "Width of violin = uncertainty in recommendation  |  "
        "White dot = posterior mean  |  Bar = 90% CI",
        fontsize=12, fontweight="bold",
    )

    for r, region in enumerate(REGIONS):
        ax        = axes[r]
        res       = opt_results[region]
        opt_draws = res["optimal_spend"]     # (n_draws, C)
        curr      = res["current_spend"]     # (C,)

        data_list = [opt_draws[:, c] / 1e3 for c in range(N_CHANNELS)]

        parts = ax.violinplot(
            data_list,
            positions=np.arange(N_CHANNELS),
            showmeans=False, showmedians=False, showextrema=False,
        )
        for i, pc in enumerate(parts["bodies"]):
            pc.set_facecolor(PALETTE[CHANNELS[i]])
            pc.set_alpha(0.65)

        # Mean and 90% CI markers
        for c in range(N_CHANNELS):
            mean_val = float(opt_draws[:, c].mean()) / 1e3
            lo_val   = float(np.percentile(opt_draws[:, c],  5)) / 1e3
            hi_val   = float(np.percentile(opt_draws[:, c], 95)) / 1e3
            ax.scatter([c], [mean_val], color="white", s=40, zorder=5)
            ax.vlines(c, lo_val, hi_val, color="black", lw=2, zorder=4)

        # Current spend as horizontal ticks
        for c in range(N_CHANNELS):
            ax.scatter([c], [curr[c] / 1e3], marker="_", color="black",
                       s=200, linewidths=2.5, zorder=5,
                       label="Current spend" if c == 0 else "")

        ax.set_xticks(np.arange(N_CHANNELS))
        ax.set_xticklabels([CHANNEL_LABELS[ch] for ch in CHANNELS],
                            fontsize=8, rotation=20, ha="right")
        ax.yaxis.set_major_formatter(
            mticker.FuncFormatter(lambda x, _: f"${x:.0f}K"))
        ax.set_ylabel("Weekly Spend ($K)" if r == 0 else "", fontsize=9)
        ax.set_title(REGION_LABELS[region], fontsize=10,
                     fontweight="bold", color=PALETTE[region])
        if r == 0:
            ax.legend(fontsize=8, loc="upper right")

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Allocation uncertainty plot saved: {save_path}")


# ══════════════════════════════════════════════════════════════════════════════
# 8. RESULTS TABLE
# ══════════════════════════════════════════════════════════════════════════════

def build_recommendation_table(opt_results: dict,
                                 save_path: str = "outputs/budget_recommendations.csv") -> pd.DataFrame:
    """
    Build and save the full budget recommendation table.

    Columns
    -------
    region, channel,
    current_spend_weekly,
    optimal_spend_mean, optimal_spend_lo90, optimal_spend_hi90,
    spend_delta_mean,               ← optimal - current
    spend_delta_pct,                ← % change from current
    revenue_uplift_mean_weekly,     ← additional weekly media revenue
    revenue_uplift_pct              ← % improvement over current allocation
    """
    rows = []

    print("\n  ── Budget Recommendation Table ──")
    print(f"  {'Region':<15} {'Channel':<12} {'Current':>10} "
          f"{'Optimal':>10} {'Change':>10} {'90% CI':>20}")
    print("  " + "─" * 80)

    for r, region in enumerate(REGIONS):
        res           = opt_results[region]
        current_spend = res["current_spend"]
        opt_draws     = res["optimal_spend"]
        uplift_draws  = res["pct_uplift"]

        opt_mean = opt_draws.mean(axis=0)
        opt_lo   = np.percentile(opt_draws,  5, axis=0)
        opt_hi   = np.percentile(opt_draws, 95, axis=0)

        mean_uplift_pct = float(uplift_draws.mean())
        mean_rev_uplift = float(res["revenue_uplift"].mean())

        for c, ch in enumerate(CHANNELS):
            delta      = opt_mean[c] - current_spend[c]
            delta_pct  = delta / current_spend[c] * 100

            rows.append({
                "region":                  region,
                "channel":                 ch,
                "current_spend_weekly":    round(current_spend[c],  0),
                "optimal_spend_mean":      round(opt_mean[c],       0),
                "optimal_spend_lo90":      round(opt_lo[c],         0),
                "optimal_spend_hi90":      round(opt_hi[c],         0),
                "spend_delta_mean":        round(delta,             0),
                "spend_delta_pct":         round(delta_pct,         1),
                "revenue_uplift_mean_wkly": round(mean_rev_uplift,  0),
                "revenue_uplift_pct":      round(mean_uplift_pct,   2),
            })

            sign = "+" if delta >= 0 else ""
            print(f"  {REGION_LABELS[region]:<15} {CHANNEL_LABELS[ch]:<12} "
                  f"${current_spend[c]/1e3:>7.1f}K  "
                  f"${opt_mean[c]/1e3:>7.1f}K  "
                  f"{sign}${delta/1e3:>6.1f}K  "
                  f"[${opt_lo[c]/1e3:.1f}K, ${opt_hi[c]/1e3:.1f}K]")

        print(f"  {'':15} {'Revenue uplift':12} "
              f"{'':10} {'':10}  "
              f"+${mean_rev_uplift/1e3:.1f}K/wk  ({mean_uplift_pct:+.1f}%)\n")

    df = pd.DataFrame(rows)
    df.to_csv(save_path, index=False)
    print(f"\n  ✓ Recommendations saved: {save_path}")
    return df


# ══════════════════════════════════════════════════════════════════════════════
# 9. ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

def run_phase6(
    idata_path:    str   = "idata_hierarchical.nc",
    raw_data_path: str   = "synthetic_raw.csv",
    n_opt_draws:   int   = N_OPT_DRAWS,
    run_response_curves: bool = True,
):
    """
    Full Phase 6 pipeline:
        1. Load InferenceData, raw spend, compute current budgets and p95 constants
        2. Extract posterior samples for optimisation
        3. Run posterior optimisation at current budget level
        4. Run budget response curves across 50%–200% of current spend
        5. Plot optimal allocation (current vs. optimal, net reallocation)
        6. Plot budget response curves
        7. Plot allocation uncertainty (violin plots)
        8. Build and save recommendation table

    Parameters
    ----------
    idata_path         : Path to Phase 4 InferenceData.
    raw_data_path      : Path to synthetic_raw.csv.
    n_opt_draws        : Number of posterior draws to use (default 500).
                         Increase to 1000+ for final results; 200 for quick test.
    run_response_curves: If True, run budget response curves (adds ~50% runtime).
                         Set to False for a quick allocation-only run.

    Quick smoke-test
    ----------------
        run_phase6(n_opt_draws=50, run_response_curves=False)
    """
    global N_OPT_DRAWS
    N_OPT_DRAWS = n_opt_draws

    print("=" * 70)
    print("MapleThread Outdoor Co. — Phase 6: Budget Optimisation")
    print(f"{N_REGIONS} regions  ×  {len(CHANNELS)} channels  ×  {n_opt_draws} posterior draws")
    print("=" * 70)

    # ── Step 1: Load data ─────────────────────────────────────────────────────
    print("\n[1/6] Loading data...")
    idata   = load_idata(idata_path)
    raw_df  = load_raw_data(raw_data_path)
    budgets = compute_current_budgets(raw_df)
    p95     = compute_p95_constants(raw_df)

    print("\n  Current mean weekly budgets:")
    for region in REGIONS:
        total = sum(budgets[region].values())
        parts = "  |  ".join(
            f"{CHANNEL_LABELS[ch]}: ${budgets[region][ch]/1e3:.1f}K"
            for ch in CHANNELS
        )
        print(f"    {REGION_LABELS[region]:<15}: {parts}  →  Total: ${total/1e3:.1f}K")

    # ── Step 2: Extract posterior samples ─────────────────────────────────────
    print(f"\n[2/6] Extracting {n_opt_draws} posterior draws...")
    samples = extract_posterior_samples(idata, n_draws=n_opt_draws)

    # ── Step 3: Posterior optimisation at current budget ──────────────────────
    print(f"\n[3/6] Running posterior optimisation (current budget)...")
    print(f"  This runs {n_opt_draws} SciPy optimisations per region "
          f"({n_opt_draws * N_REGIONS:,} total). May take several minutes.\n")
    opt_results = run_posterior_optimisation(samples, p95, budgets,
                                              budget_multiplier=1.0)

    # ── Step 4: Budget response curves ────────────────────────────────────────
    response = None
    if run_response_curves:
        print(f"\n[4/6] Running budget response curves "
              f"({len(BUDGET_SCENARIOS)} scenarios × {n_opt_draws // 2} draws)...")
        response = run_budget_response_curves(samples, p95, budgets)
    else:
        print("\n[4/6] Skipping budget response curves (run_response_curves=False).")

    # ── Step 5: Plot optimal allocation ───────────────────────────────────────
    print("\n[5/6] Plotting results...")
    plot_optimal_allocation(opt_results)

    if response is not None:
        plot_budget_response_curves(response, budgets)

    plot_allocation_uncertainty(opt_results)

    # ── Step 6: Recommendation table ──────────────────────────────────────────
    print("\n[6/6] Building recommendation table...")
    rec_df = build_recommendation_table(opt_results)

    print("\n" + "=" * 70)
    print("Phase 6 complete. ✓")
    print("Outputs:")
    print("  outputs/fig_optimal_allocation.png")
    print("  outputs/fig_allocation_uncertainty.png")
    if response is not None:
        print("  outputs/fig_budget_response_curves.png")
    print("  outputs/budget_recommendations.csv")
    print("Next step → Phase 7: Writeup and Presentation")
    print("=" * 70)

    return opt_results, response, rec_df


# ── Run ───────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    # Quick smoke-test: run_phase6(n_opt_draws=50, run_response_curves=False)
    opt_results, response, rec_df = run_phase6(
        idata_path="idata_hierarchical.nc",
        raw_data_path="synthetic_raw.csv",
        n_opt_draws=500,
        run_response_curves=True,
    )

