# -*- coding: utf-8 -*-
"""data_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Uma9Xd0s9laTOCuQde9ei1WBRMVy2VU
"""

# Commented out IPython magic to ensure Python compatibility.
"""
maplethread_mmm_phase1.py
=========================
MapleThread Outdoor Co. — MMM Phase 1: Data Generation + Visualisation
Combined, self-contained script for Google Colab.

Sections:
  1. Config       — ground truth parameters
  2. Data Gen     — synthetic dataset generation
  3. Visualisation — 6 diagnostic figures

Usage in Colab:
  Option A — Run everything at once:
#     %run maplethread_mmm_phase1.py

  Option B — Step by step (recommended):
    After uploading this file, run each numbered section cell by cell.
    The notebook version below uses #@title cell headers for Colab's
    table-of-contents sidebar.

Outputs:
  data/synthetic_raw.csv
  data/ground_truth.csv
  data/true_parameters.csv
  outputs/dag.png
  outputs/fig_baseline.png
  outputs/fig_spend.png
  outputs/fig_hill.png
  outputs/fig_contributions.png
  outputs/fig_adstock.png
"""

# ══════════════════════════════════════════════════════════════════════════════
# 0. INSTALL / IMPORTS
# ══════════════════════════════════════════════════════════════════════════════
# All libraries below are pre-installed in Colab. No pip installs needed.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import os

os.makedirs("data",    exist_ok=True)
os.makedirs("outputs", exist_ok=True)


# ══════════════════════════════════════════════════════════════════════════════
# 1. GROUND TRUTH CONFIG
#    MapleThread Outdoor Co. — MMM Ground Truth Parameters
# ══════════════════════════════════════════════════════════════════════════════

REGIONS  = ["canada", "united_states", "germany", "japan", "australia"]
CHANNELS = ["tv", "paid_search", "social", "display"]
N_WEEKS  = 156
RANDOM_SEED = 42

# ── Baseline Demand ──────────────────────────────────────────────────────────
# Fourier amplitudes: [sin1, cos1, sin2, cos2]
# Encodes outdoor apparel retail seasonality:
#   Peaks: fall hiking (Aug–Sep), holiday gifting (Nov–Dec), spring launch (Mar–Apr)
#   Trough: mid-summer (Jul) — heavy outerwear slow
#   Australia: inverted — SH winter (Jun–Aug) is outdoor peak

BASELINE = {
    "canada": {
        "intercept": 620_000,
        "trend_slope": 950,
        "seasonality_amplitudes": [-25_000, 40_000, 18_000, -8_000],
        "noise_std": 28_000,
    },
    "united_states": {
        "intercept": 430_000,
        "trend_slope": 700,
        "seasonality_amplitudes": [-18_000, 30_000, 14_000, -6_000],
        "noise_std": 20_000,
    },
    "germany": {
        "intercept": 180_000,
        "trend_slope": 350,
        "seasonality_amplitudes": [-10_000, 18_000, 7_000, -3_000],
        "noise_std": 9_000,
    },
    "japan": {
        "intercept": 150_000,
        "trend_slope": 400,
        "seasonality_amplitudes": [-8_000, 16_000, 6_000, -2_500],
        "noise_std": 8_000,
    },
    "australia": {
        "intercept": 55_000,
        "trend_slope": 280,
        "seasonality_amplitudes": [20_000, -12_000, 5_000, -2_000],
        "noise_std": 5_000,
    },
}

# ── Holiday / Retail Spikes ──────────────────────────────────────────────────
# (week_of_year, lift_multiplier, label)

HOLIDAY_SPIKES = [
    (13, 1.20, "Spring Outdoor Season Launch"),
    (14, 1.15, "Easter Long Weekend"),
    (26, 0.90, "Summer Trough — Heavy Outerwear Slow"),
    (34, 1.25, "Back-to-School / Fall Gear"),
    (35, 1.30, "Fall Hiking Peak"),
    (36, 1.20, "Fall Continuation"),
    (47, 1.35, "Pre-Black Friday Build"),
    (48, 1.75, "Black Friday / Cyber Monday"),
    (49, 1.40, "Cyber Week"),
    (50, 1.25, "Holiday Gifting Window"),
    (51, 1.30, "Christmas Gifting Peak"),
    (52, 1.15, "Boxing Day (Canada/AU)"),
]

# ── Spend Generation ─────────────────────────────────────────────────────────

SPEND_CONFIG = {
    "canada": {
        "tv":           {"base_spend": 120_000, "variance_scale": 0.55, "growth_rate": 0.000, "burst_multiplier": 3.2},
        "paid_search":  {"base_spend":  75_000, "variance_scale": 0.15, "growth_rate": 0.001, "burst_multiplier": 1.9},
        "social":       {"base_spend":  65_000, "variance_scale": 0.25, "growth_rate": 0.003, "burst_multiplier": 2.6},
        "display":      {"base_spend":  28_000, "variance_scale": 0.20, "growth_rate": 0.000, "burst_multiplier": 2.1},
    },
    "united_states": {
        "tv":           {"base_spend":  90_000, "variance_scale": 0.55, "growth_rate": 0.000, "burst_multiplier": 3.0},
        "paid_search":  {"base_spend":  60_000, "variance_scale": 0.15, "growth_rate": 0.001, "burst_multiplier": 1.9},
        "social":       {"base_spend":  55_000, "variance_scale": 0.25, "growth_rate": 0.003, "burst_multiplier": 2.5},
        "display":      {"base_spend":  22_000, "variance_scale": 0.20, "growth_rate": 0.000, "burst_multiplier": 2.0},
    },
    "germany": {
        "tv":           {"base_spend":  45_000, "variance_scale": 0.50, "growth_rate": 0.000, "burst_multiplier": 2.8},
        "paid_search":  {"base_spend":  28_000, "variance_scale": 0.15, "growth_rate": 0.001, "burst_multiplier": 1.7},
        "social":       {"base_spend":  22_000, "variance_scale": 0.25, "growth_rate": 0.003, "burst_multiplier": 2.4},
        "display":      {"base_spend":  10_000, "variance_scale": 0.20, "growth_rate": 0.000, "burst_multiplier": 2.0},
    },
    "japan": {
        "tv":           {"base_spend":  40_000, "variance_scale": 0.50, "growth_rate": 0.001, "burst_multiplier": 2.5},
        "paid_search":  {"base_spend":  22_000, "variance_scale": 0.15, "growth_rate": 0.002, "burst_multiplier": 1.8},
        "social":       {"base_spend":  20_000, "variance_scale": 0.28, "growth_rate": 0.004, "burst_multiplier": 2.6},
        "display":      {"base_spend":   8_000, "variance_scale": 0.20, "growth_rate": 0.000, "burst_multiplier": 1.9},
    },
    "australia": {
        "tv":           {"base_spend":  15_000, "variance_scale": 0.50, "growth_rate": 0.002, "burst_multiplier": 2.5},
        "paid_search":  {"base_spend":   9_000, "variance_scale": 0.15, "growth_rate": 0.002, "burst_multiplier": 1.6},
        "social":       {"base_spend":   8_000, "variance_scale": 0.30, "growth_rate": 0.005, "burst_multiplier": 2.8},
        "display":      {"base_spend":   3_500, "variance_scale": 0.20, "growth_rate": 0.000, "burst_multiplier": 1.8},
    },
}

# ── Promotional Calendar ─────────────────────────────────────────────────────
# (start_week_of_year, duration_weeks, label)

PROMO_CALENDAR = [
    (13, 2, "Spring Outdoor Launch"),
    (34, 3, "Fall Gear Up Campaign"),
    (47, 3, "Black Friday / Holiday Push"),
    (52, 1, "Boxing Day Sale"),
]

# ── Adstock Parameters ───────────────────────────────────────────────────────
# TV: long brand-building (α=0.75) | Paid Search: immediate demand (α=0.20)
# Social: medium carryover (α=0.45) | Display: very fast decay (α=0.15)

ADSTOCK_PARAMS = {
    "tv":           {"alpha": 0.75},
    "paid_search":  {"alpha": 0.20},
    "social":       {"alpha": 0.45},
    "display":      {"alpha": 0.15},
}

# ── Hill Saturation Parameters ───────────────────────────────────────────────
# TV: heavy saturation (k=2.5, ec=0.4) | Search: moderate (k=1.5, ec=0.6)
# Social: low saturation (k=1.2, ec=0.7) | Display: very high sat. (k=3.0, ec=0.3)

HILL_PARAMS = {
    "tv":           {"k": 2.5, "ec": 0.4},
    "paid_search":  {"k": 1.5, "ec": 0.6},
    "social":       {"k": 1.2, "ec": 0.7},
    "display":      {"k": 3.0, "ec": 0.3},
}

# ── Channel Coefficients (β) per Region ─────────────────────────────────────

CHANNEL_COEFFICIENTS = {
    "canada": {
        "tv":           320_000,
        "paid_search":  260_000,
        "social":       200_000,
        "display":       80_000,
    },
    "united_states": {
        "tv":           230_000,
        "paid_search":  185_000,
        "social":       145_000,
        "display":       58_000,
    },
    "germany": {
        "tv":            95_000,
        "paid_search":   80_000,
        "social":        65_000,
        "display":       26_000,
    },
    "japan": {
        "tv":            85_000,
        "paid_search":   70_000,
        "social":        58_000,
        "display":       22_000,
    },
    "australia": {
        "tv":            38_000,
        "paid_search":   32_000,
        "social":        26_000,
        "display":       10_000,
    },
}


# ══════════════════════════════════════════════════════════════════════════════
# 2. DATA GENERATION
#    DGP: Baseline → Spend → Adstock → Hill Saturation → Revenue
# ══════════════════════════════════════════════════════════════════════════════

# ── Transformations ──────────────────────────────────────────────────────────

def geometric_adstock(spend: np.ndarray, alpha: float) -> np.ndarray:
    """Geometric adstock: adstock[t] = spend[t] + alpha * adstock[t-1]"""
    adstock = np.zeros_like(spend, dtype=float)
    adstock[0] = spend[0]
    for t in range(1, len(spend)):
        adstock[t] = spend[t] + alpha * adstock[t - 1]
    return adstock


def hill_saturation(x: np.ndarray, k: float, ec: float) -> np.ndarray:
    """Hill saturation: S(x) = x^k / (x^k + ec^k) → returns value in [0, 1]"""
    x = np.where(x == 0, 1e-10, x)
    return x ** k / (x ** k + ec ** k)


def build_time_index(n_weeks: int, start_date: str = "2021-01-04") -> pd.DatetimeIndex:
    return pd.date_range(start=start_date, periods=n_weeks, freq="W-MON")


# ── Step 1: Baseline Demand ───────────────────────────────────────────────────

def generate_baseline(region: str, n_weeks: int, rng: np.random.Generator) -> np.ndarray:
    params = BASELINE[region]
    t = np.arange(n_weeks)
    week_of_year = (t % 52) + 1

    trend = params["intercept"] + params["trend_slope"] * t

    amps = params["seasonality_amplitudes"]
    seasonality = (
        amps[0] * np.sin(2 * np.pi * t / 52) +
        amps[1] * np.cos(2 * np.pi * t / 52) +
        amps[2] * np.sin(4 * np.pi * t / 52) +
        amps[3] * np.cos(4 * np.pi * t / 52)
    )

    holiday_multiplier = np.ones(n_weeks)
    for (holiday_week, lift, _label) in HOLIDAY_SPIKES:
        mask = (week_of_year == holiday_week)
        holiday_multiplier[mask] = lift

    baseline_signal = (trend + seasonality) * holiday_multiplier
    noise = rng.normal(0, params["noise_std"], n_weeks)
    return np.maximum(baseline_signal + noise, 0)


# ── Step 2: Raw Spend Generation ─────────────────────────────────────────────

def _is_promo_week(week_of_year: int) -> bool:
    for (start, duration, _label) in PROMO_CALENDAR:
        if start <= week_of_year < start + duration:
            return True
    return False


def generate_spend(region: str, channel: str, n_weeks: int, rng: np.random.Generator) -> np.ndarray:
    config = SPEND_CONFIG[region][channel]
    base       = config["base_spend"]
    var_scale  = config["variance_scale"]
    growth     = config["growth_rate"]
    burst_mult = config["burst_multiplier"]

    t = np.arange(n_weeks)
    week_of_year = (t % 52) + 1

    log_mean = np.log(base) - 0.5 * var_scale ** 2
    spend = rng.lognormal(log_mean, var_scale, n_weeks)
    spend = spend * (1 + growth) ** t

    for i, woy in enumerate(week_of_year):
        if _is_promo_week(woy):
            spend[i] *= burst_mult

    return np.maximum(spend, 0)


# ── Steps 3 & 4: Adstock + Hill Saturation ───────────────────────────────────

def transform_spend(spend: np.ndarray, channel: str) -> tuple:
    alpha = ADSTOCK_PARAMS[channel]["alpha"]
    k     = HILL_PARAMS[channel]["k"]
    ec    = HILL_PARAMS[channel]["ec"]

    adstock = geometric_adstock(spend, alpha)

    p95 = np.percentile(adstock, 95)
    adstock_norm = adstock / p95 if p95 > 0 else adstock

    saturated = hill_saturation(adstock_norm, k, ec)
    return adstock, saturated


# ── Step 5: Revenue Assembly ──────────────────────────────────────────────────

def compute_revenue(baseline: np.ndarray, saturated_effects: dict, region: str) -> tuple:
    betas = CHANNEL_COEFFICIENTS[region]
    contributions = {}
    channel_sum = np.zeros_like(baseline)

    for channel, effect in saturated_effects.items():
        contribution = betas[channel] * effect
        contributions[channel] = contribution
        channel_sum += contribution

    revenue = baseline + channel_sum
    return revenue, contributions


# ── Main: Full Dataset ────────────────────────────────────────────────────────

def generate_full_dataset() -> tuple:
    rng   = np.random.default_rng(RANDOM_SEED)
    dates = build_time_index(N_WEEKS)

    raw_rows, gt_rows = [], []

    for region in REGIONS:
        print(f"  Generating: {region}...")

        baseline = generate_baseline(region, N_WEEKS, rng)

        raw_spends, adstocks, saturated_effects = {}, {}, {}
        for channel in CHANNELS:
            raw_spend = generate_spend(region, channel, N_WEEKS, rng)
            adstock, saturated = transform_spend(raw_spend, channel)
            raw_spends[channel]        = raw_spend
            adstocks[channel]          = adstock
            saturated_effects[channel] = saturated

        revenue, contributions = compute_revenue(baseline, saturated_effects, region)

        for i, date in enumerate(dates):
            raw_row = {
                "date":         date,
                "region":       region,
                "revenue":      revenue[i],
                "week_of_year": date.isocalendar().week,
                "year":         date.year,
                "t":            i,
            }
            for ch in CHANNELS:
                raw_row[f"spend_{ch}"] = raw_spends[ch][i]
            raw_rows.append(raw_row)

            gt_row = {
                "date":          date,
                "region":        region,
                "true_baseline": baseline[i],
                "true_revenue":  revenue[i],
            }
            for ch in CHANNELS:
                gt_row[f"contrib_{ch}"]   = contributions[ch][i]
                gt_row[f"adstock_{ch}"]   = adstocks[ch][i]
                gt_row[f"saturated_{ch}"] = saturated_effects[ch][i]
            gt_rows.append(gt_row)

    return pd.DataFrame(raw_rows), pd.DataFrame(gt_rows)


def save_parameter_reference() -> pd.DataFrame:
    rows = []
    for region in REGIONS:
        for channel in CHANNELS:
            rows.append({
                "region":           region,
                "channel":          channel,
                "true_alpha":       ADSTOCK_PARAMS[channel]["alpha"],
                "true_k":           HILL_PARAMS[channel]["k"],
                "true_ec":          HILL_PARAMS[channel]["ec"],
                "true_beta":        CHANNEL_COEFFICIENTS[region][channel],
                "true_intercept":   BASELINE[region]["intercept"],
                "true_trend_slope": BASELINE[region]["trend_slope"],
            })
    return pd.DataFrame(rows)


def run_data_generation():
    print("=" * 60)
    print("MapleThread Outdoor Co. — Phase 1: Synthetic Data Generation")
    print("=" * 60)

    print("\nGenerating dataset...")
    raw_df, gt_df = generate_full_dataset()

    print("\nSaving parameter reference table...")
    param_df = save_parameter_reference()

    raw_df.to_csv("data/synthetic_raw.csv",   index=False)
    gt_df.to_csv("data/ground_truth.csv",     index=False)
    param_df.to_csv("data/true_parameters.csv", index=False)

    print("\n✓ data/synthetic_raw.csv")
    print("✓ data/ground_truth.csv")
    print("✓ data/true_parameters.csv")

    print(f"\n── Dataset: {len(raw_df):,} rows | {len(REGIONS)} regions × {N_WEEKS} weeks ──")
    print(f"   Date range: {raw_df['date'].min().date()} → {raw_df['date'].max().date()}")

    print("\n── Revenue Summary by Region ──")
    summary = raw_df.groupby("region")["revenue"].agg(["mean", "std", "min", "max"])
    summary.columns = ["Mean ($)", "Std ($)", "Min ($)", "Max ($)"]
    summary = summary.map(lambda x: f"{x:,.0f}")
    print(summary.to_string())

    print("\n── True Parameter Reference ──")
    print(param_df.to_string(index=False))
    print("\nData generation done. ✓")

    return raw_df, gt_df, param_df


# ══════════════════════════════════════════════════════════════════════════════
# 3. VISUALISATION
#    6 diagnostic figures: DAG, Baseline, Spend, Hill, Contributions, Adstock
# ══════════════════════════════════════════════════════════════════════════════

# ── Style ─────────────────────────────────────────────────────────────────────

PALETTE = {
    "tv":            "#E63946",
    "paid_search":   "#2A9D8F",
    "social":        "#F4A261",
    "display":       "#457B9D",
    "baseline":      "#A8DADC",
    "canada":        "#D62828",
    "united_states": "#4361EE",
    "germany":       "#F7B731",
    "japan":         "#E84393",
    "australia":     "#43AA8B",
}

REGION_LABELS = {
    "canada":        "Canada (Home)",
    "united_states": "United States",
    "germany":       "Germany (EU)",
    "japan":         "Japan",
    "australia":     "Australia (Newest)",
}

CHANNEL_LABELS = {
    "tv":          "TV",
    "paid_search": "Paid Search",
    "social":      "Social",
    "display":     "Display",
}

plt.rcParams.update({
    "font.family":       "DejaVu Sans",
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "axes.grid":         True,
    "grid.alpha":        0.3,
    "grid.linestyle":    "--",
    "figure.facecolor":  "#FAFAFA",
    "axes.facecolor":    "#FAFAFA",
})


# ── Figure 1: DAG ─────────────────────────────────────────────────────────────

def draw_dag(save_path: str = "outputs/dag.png"):
    fig, ax = plt.subplots(figsize=(16, 10))
    ax.set_xlim(0, 16)
    ax.set_ylim(0, 10)
    ax.axis("off")
    fig.patch.set_facecolor("#0D1B2A")
    ax.set_facecolor("#0D1B2A")

    nodes = {
        "time":       (1.2, 8.5, "Time\n(t = 0…156)",          "#4CC9F0", "round,pad=0.3"),
        "season":     (1.2, 6.8, "Fourier\nSeasonality",        "#4CC9F0", "round,pad=0.3"),
        "holidays":   (1.2, 5.1, "Retail Holiday\nCalendar",    "#4CC9F0", "round,pad=0.3"),
        "region":     (1.2, 3.4, "Region\nCharacteristics",     "#4CC9F0", "round,pad=0.3"),
        "promo":      (1.2, 1.7, "Promo\nCalendar",             "#F72585", "round,pad=0.3"),
        "budget":     (1.2, 0.3, "Budget\nConstraints",         "#F72585", "round,pad=0.3"),
        "baseline":   (4.5, 6.5, "Baseline\nDemand",            "#7B2D8B", "round,pad=0.3"),
        "spend_tv":   (4.5, 4.5, "TV\nSpend",                   "#E63946", "round,pad=0.3"),
        "spend_ps":   (4.5, 3.3, "Paid Search\nSpend",          "#2A9D8F", "round,pad=0.3"),
        "spend_so":   (4.5, 2.1, "Social\nSpend",               "#F4A261", "round,pad=0.3"),
        "spend_di":   (4.5, 0.9, "Display\nSpend",              "#457B9D", "round,pad=0.3"),
        "ads_tv":     (7.5, 4.5, "Adstock\nTV  α=0.75",        "#E63946", "round,pad=0.3"),
        "ads_ps":     (7.5, 3.3, "Adstock\nSearch α=0.20",     "#2A9D8F", "round,pad=0.3"),
        "ads_so":     (7.5, 2.1, "Adstock\nSocial α=0.45",     "#F4A261", "round,pad=0.3"),
        "ads_di":     (7.5, 0.9, "Adstock\nDisplay α=0.15",    "#457B9D", "round,pad=0.3"),
        "sat_tv":     (10.5, 4.5, "Hill Sat.\nTV  k=2.5",      "#E63946", "round,pad=0.3"),
        "sat_ps":     (10.5, 3.3, "Hill Sat.\nSearch k=1.5",   "#2A9D8F", "round,pad=0.3"),
        "sat_so":     (10.5, 2.1, "Hill Sat.\nSocial k=1.2",   "#F4A261", "round,pad=0.3"),
        "sat_di":     (10.5, 0.9, "Hill Sat.\nDisplay k=3.0",  "#457B9D", "round,pad=0.3"),
        "contrib":    (13.2, 2.7, "β × Effect\n(per channel)",  "#9B72CF", "round,pad=0.3"),
        "revenue":    (15.2, 5.0, "Revenue\n(observed)",         "#F8F9FA", "round,pad=0.3"),
        "confounders":(4.5, 8.8,  "⚠ Unobserved\nConfounders", "#888888", "round,pad=0.3"),
    }

    for key, (x, y, label, color, box_style) in nodes.items():
        unobserved = key == "confounders"
        ax.text(x, y, label, ha="center", va="center",
                fontsize=7.5, fontweight="bold",
                color="white" if not unobserved else "#AAAAAA",
                bbox=dict(boxstyle=box_style, facecolor=color,
                          edgecolor="white" if not unobserved else "#888888",
                          linewidth=1 if unobserved else 1.5,
                          alpha=0.4 if unobserved else 1.0),
                zorder=3)

    def arrow(x1, y1, x2, y2, color="white", lw=1.2, alpha=0.7, dashed=False):
        ax.annotate("", xy=(x2, y2), xytext=(x1, y1),
                    arrowprops=dict(arrowstyle="-|>", color=color, lw=lw,
                                   alpha=alpha, connectionstyle="arc3,rad=0.05",
                                   linestyle=(0, (4, 4)) if dashed else "solid"),
                    zorder=2)

    for (x1, y1) in [(1.9, 8.5), (1.9, 6.8), (1.9, 5.1), (1.9, 3.4)]:
        arrow(x1, y1, 3.7, 6.5, "#4CC9F0")

    for sy in [4.5, 3.3, 2.1, 0.9]:
        arrow(1.9, 1.7, 3.7, sy, "#F72585")
        arrow(1.9, 0.3, 3.7, sy, "#F72585")

    for ch, sy in [("tv", 4.5), ("paid_search", 3.3), ("social", 2.1), ("display", 0.9)]:
        c = PALETTE[ch]
        arrow(5.3, sy, 6.6, sy, c, lw=1.5, alpha=0.9)
        arrow(8.4, sy, 9.6, sy, c, lw=1.5, alpha=0.9)
        arrow(11.4, sy, 12.6, 2.7, c, lw=1.2, alpha=0.8)

    arrow(5.4, 6.5,  14.4, 5.3, "#7B2D8B", lw=1.5)
    arrow(13.9, 2.7, 14.4, 4.8, "#9B72CF", lw=1.5)
    arrow(4.5, 8.3,  4.5,  7.1, "#888888", dashed=True, alpha=0.5)
    arrow(5.0, 8.8,  14.4, 5.5, "#888888", dashed=True, alpha=0.4)

    for x, lbl, col in [
        (1.2,  "EXOGENOUS\nINPUTS",      "#4CC9F0"),
        (4.5,  "DEMAND &\nSPEND",        "#FFFFFF"),
        (7.5,  "ADSTOCK\n(Carryover)",   "#FFFFFF"),
        (10.5, "HILL\n(Saturation)",     "#FFFFFF"),
        (13.2, "CHANNEL\nCONTRIBUTION", "#9B72CF"),
        (15.2, "OBSERVED\nOUTPUT",       "#F8F9FA"),
    ]:
        ax.text(x, 9.6, lbl, ha="center", va="center",
                fontsize=7, fontweight="bold", color=col, alpha=0.7)

    ax.text(8.2, 9.95,
            "MapleThread Outdoor Co. — MMM Causal DAG (Data Generating Process)",
            ha="center", va="center", fontsize=13, fontweight="bold", color="white")

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.show()
    plt.close()
    print(f"  ✓ DAG saved: {save_path}")


# ── Figure 2: Baseline Demand ─────────────────────────────────────────────────

def plot_baseline_demand(gt_df: pd.DataFrame, save_path: str = "outputs/fig_baseline.png"):
    fig, axes = plt.subplots(5, 1, figsize=(14, 15), sharex=True)
    fig.suptitle(
        "MapleThread — Baseline Demand by Region\n"
        "(Trend + Fourier Seasonality + Retail Holiday Spikes)\n"
        "Note: Australia shows inverted seasonality — Southern Hemisphere winter = outdoor peak",
        fontsize=13, fontweight="bold", y=1.01,
    )
    for ax, region in zip(axes, REGIONS):
        df = gt_df[gt_df["region"] == region].copy()
        dates = pd.to_datetime(df["date"])
        color = PALETTE[region]
        ax.fill_between(dates, df["true_baseline"], alpha=0.25, color=color)
        ax.plot(dates, df["true_baseline"], color=color, lw=1.5)
        week_of_year = dates.dt.isocalendar().week
        for (hw, lift, _) in HOLIDAY_SPIKES:
            mask = (week_of_year == hw)
            if mask.any():
                ax.scatter(dates[mask], df["true_baseline"][mask],
                           color="white", edgecolors=color, s=50, zorder=5, linewidths=1.5)
        ax.set_ylabel("Revenue ($)", fontsize=9)
        ax.set_title(REGION_LABELS[region], fontsize=10, fontweight="bold", color=color)
        ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"${x/1e3:.0f}K"))
    axes[-1].set_xlabel("Date", fontsize=9)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Baseline demand saved: {save_path}")


# ── Figure 3: Spend Patterns ──────────────────────────────────────────────────

def plot_spend_patterns(raw_df: pd.DataFrame, save_path: str = "outputs/fig_spend.png"):
    fig, axes = plt.subplots(5, 4, figsize=(18, 16), sharex=True)
    fig.suptitle(
        "MapleThread — Raw Media Spend by Region & Channel\n"
        "(Log-normal base + Growth trend + Promo bursts)",
        fontsize=13, fontweight="bold", y=1.01,
    )
    for r_idx, region in enumerate(REGIONS):
        df = raw_df[raw_df["region"] == region].copy()
        dates = pd.to_datetime(df["date"])
        for c_idx, channel in enumerate(CHANNELS):
            ax = axes[r_idx][c_idx]
            color = PALETTE[channel]
            ax.fill_between(dates, df[f"spend_{channel}"] / 1000, alpha=0.3, color=color)
            ax.plot(dates, df[f"spend_{channel}"] / 1000, color=color, lw=1.0)
            if r_idx == 0:
                ax.set_title(CHANNEL_LABELS[channel], fontsize=10, fontweight="bold", color=color)
            if c_idx == 0:
                ax.set_ylabel(REGION_LABELS[region], fontsize=8, fontweight="bold")
            ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"${x:.0f}K"))
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Spend patterns saved: {save_path}")


# ── Figure 4: Hill Saturation Curves ─────────────────────────────────────────

def plot_hill_curves(save_path: str = "outputs/fig_hill.png"):
    fig, axes = plt.subplots(1, 4, figsize=(16, 5))
    fig.suptitle(
        "Hill Saturation Curves at True Parameters\n"
        "(Normalised spend: 0 = zero spend, 1 = 95th percentile of adstock)",
        fontsize=12, fontweight="bold",
    )
    x = np.linspace(0, 1.5, 500)
    for ax, channel in zip(axes, CHANNELS):
        k  = HILL_PARAMS[channel]["k"]
        ec = HILL_PARAMS[channel]["ec"]
        color = PALETTE[channel]
        y = hill_saturation(x, k, ec)
        ax.plot(x, y, color=color, lw=2.5)
        ax.axvline(ec, color=color, linestyle="--", alpha=0.5, lw=1.2)
        ax.axhline(0.5, color="grey", linestyle="--", alpha=0.4, lw=1.0)
        ax.scatter([ec], [0.5], color=color, s=80, zorder=5)
        ax.text(ec + 0.04, 0.48, f"ec={ec}", fontsize=8, color=color)
        ax.axvspan(0, 1.0, alpha=0.06, color=color)
        ax.text(0.5, 0.05, "Current\noperating\nzone", ha="center",
                fontsize=7, color=color, style="italic")
        ax.set_title(f"{CHANNEL_LABELS[channel]}\nk={k}, ec={ec}",
                     fontsize=10, fontweight="bold", color=color)
        ax.set_xlabel("Normalised Adstock Spend")
        ax.set_ylabel("Saturation Effect [0–1]")
        ax.set_xlim(0, 1.5)
        ax.set_ylim(0, 1.05)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Hill curves saved: {save_path}")


# ── Figure 5: Channel Contribution Decomposition ──────────────────────────────

def plot_contributions(gt_df: pd.DataFrame, save_path: str = "outputs/fig_contributions.png"):
    fig, axes = plt.subplots(5, 1, figsize=(16, 18), sharex=False)
    fig.suptitle(
        "MapleThread — True Channel Revenue Contributions (Ground Truth)\n"
        "Stacked area = total explained revenue | Remaining gap = baseline demand",
        fontsize=13, fontweight="bold", y=1.01,
    )
    for ax, region in zip(axes, REGIONS):
        df = gt_df[gt_df["region"] == region].copy().reset_index(drop=True)
        dates    = pd.to_datetime(df["date"])
        baseline = df["true_baseline"].values
        revenue  = df["true_revenue"].values
        contribs = np.column_stack([df[f"contrib_{ch}"].values for ch in CHANNELS])

        ax.fill_between(dates, 0, baseline, alpha=0.4, color=PALETTE["baseline"], label="Baseline")
        bottom = baseline.copy()
        for i, ch in enumerate(CHANNELS):
            top = bottom + contribs[:, i]
            ax.fill_between(dates, bottom, top, alpha=0.75,
                            color=PALETTE[ch], label=CHANNEL_LABELS[ch])
            bottom = top
        ax.plot(dates, revenue, color="white", lw=0.8, alpha=0.5)
        ax.set_title(REGION_LABELS[region], fontsize=11, fontweight="bold")
        ax.set_ylabel("Revenue ($)")
        ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"${x/1e3:.0f}K"))
        ax.legend(loc="upper left", fontsize=8, ncol=3, framealpha=0.7)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Contributions saved: {save_path}")


# ── Figure 6: Adstock Illustration ───────────────────────────────────────────

def plot_adstock_illustration(raw_df: pd.DataFrame, save_path: str = "outputs/fig_adstock.png"):
    df_ca = raw_df[raw_df["region"] == "canada"].copy().reset_index(drop=True)
    dates = pd.to_datetime(df_ca["date"])

    fig, axes = plt.subplots(len(CHANNELS), 1, figsize=(14, 12), sharex=True)
    fig.suptitle(
        "Adstock Transformation: Raw Spend vs Carryover-Adjusted Spend\n"
        "(Canada — all channels at their true decay rates)",
        fontsize=12, fontweight="bold",
    )
    for ax, channel in zip(axes, CHANNELS):
        spend   = df_ca[f"spend_{channel}"].values
        alpha   = ADSTOCK_PARAMS[channel]["alpha"]
        adstock = geometric_adstock(spend, alpha)
        color   = PALETTE[channel]
        ax.fill_between(dates, spend / 1000, alpha=0.3, color=color, label="Raw spend")
        ax.plot(dates, spend / 1000, color=color, lw=1.0, alpha=0.6)
        ax.plot(dates, adstock / 1000, color=color, lw=2.0, label=f"Adstock (α={alpha})")
        ax.fill_between(dates, spend / 1000, adstock / 1000, alpha=0.15,
                        color="white", label="Carryover contribution")
        ax.set_ylabel("$K", fontsize=9)
        ax.set_title(f"{CHANNEL_LABELS[channel]}  —  α = {alpha}",
                     fontsize=10, fontweight="bold", color=color)
        ax.legend(loc="upper left", fontsize=8, ncol=3, framealpha=0.7)
    axes[-1].set_xlabel("Date", fontsize=9)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Adstock saved: {save_path}")


def run_visualisation(raw_df: pd.DataFrame, gt_df: pd.DataFrame):
    print("\n" + "=" * 60)
    print("MapleThread Outdoor Co. — Phase 1: DGP Visualisation")
    print("=" * 60)
    print("\nRendering figures (each will display inline in Colab)...\n")
    draw_dag()
    plot_baseline_demand(gt_df)
    plot_spend_patterns(raw_df)
    plot_hill_curves()
    plot_contributions(gt_df)
    plot_adstock_illustration(raw_df)
    print("\nAll figures rendered and saved to outputs/. ✓")


# ══════════════════════════════════════════════════════════════════════════════
# 4. ENTRY POINT — runs everything when executed directly
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    raw_df, gt_df, param_df = run_data_generation()
    run_visualisation(raw_df, gt_df)