# -*- coding: utf-8 -*-
"""hierarchical_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fS8EEfkmFZ0mEo-FN4CHTASGQCOEQbYV
"""

!pip install numpyro

# -*- coding: utf-8 -*-
"""
hierarchical_model.py
=====================
MapleThread Outdoor Co. — MMM Phase 4: Hierarchical Bayesian Model (All Regions)

Extends Phase 3 (single-region Canada) to a full 5-region hierarchical model
with partial pooling. Each region shares population-level hyperpriors; per-region
parameters are drawn from those shared distributions via non-centered
parameterisation for sampler efficiency.

Model structure (per region r):
    Revenue[r, t] = Baseline[r, t]
                  + Σ_c β[r,c] × Hill(Adstock(spend[r,c,t]) / p95[r,c] ; k[r,c], ec[r,c])
                  + ε[r, t]

Hierarchical structure (example for TV decay):
    μ_α_tv ~ Beta(8, 3)                  ← population mean
    σ_α_tv ~ HalfNormal(0.15)            ← population spread
    z_α_tv[r] ~ Normal(0, 1)             ← per-region offset (non-centered)
    α_tv[r]  = clip(μ_α_tv + σ_α_tv × z_α_tv[r], 0.01, 0.99)

Sections
--------
  1. Imports & Config
  2. Ground Truth (recovery targets)
  3. Data Loading & Preprocessing
  4. PyTensor Media Transforms
  5. Model Definition
  6. Prior Predictive Check
  7. MCMC Sampling & Diagnostics
  8. Parameter Recovery
  9. Pooling Visualisation
  10. Posterior Contribution Decomposition
  11. Entry Point

Run with:
    python hierarchical_model.py

Outputs (saved to outputs/):
    fig_prior_predictive_hier.png
    fig_trace_hier.png
    fig_parameter_recovery_hier.png
    fig_pooling_shrinkage.png
    fig_posterior_contributions_hier.png
    idata_hierarchical.nc             ← ArviZ InferenceData (full posterior)
"""

from __future__ import annotations

import os
import warnings
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import arviz as az
import pymc as pm
import pytensor.tensor as pt

warnings.filterwarnings("ignore", category=UserWarning, module="pymc")
warnings.filterwarnings("ignore", category=FutureWarning)

os.makedirs("outputs", exist_ok=True)
os.makedirs("data",    exist_ok=True)


# ══════════════════════════════════════════════════════════════════════════════
# 1. CONFIG
# ══════════════════════════════════════════════════════════════════════════════

REGIONS  = ["canada", "united_states", "germany", "japan", "australia"]
CHANNELS = ["tv", "paid_search", "social", "display"]
N_REGIONS = len(REGIONS)
N_WEEKS   = 156
MAX_LAG   = 52
RANDOM_SEED = 42

REGION_IDX   = {r: i for i, r in enumerate(REGIONS)}
REGION_LABELS = {
    "canada":        "Canada",
    "united_states": "United States",
    "germany":       "Germany",
    "japan":         "Japan",
    "australia":     "Australia",
}
CHANNEL_LABELS = {
    "tv":          "TV",
    "paid_search": "Paid Search",
    "social":      "Social",
    "display":     "Display",
}

HOLIDAY_WEEKS = [13, 14, 26, 34, 35, 36, 47, 48, 49, 50, 51, 52]

PALETTE = {
    "tv":             "#E63946",
    "paid_search":    "#2A9D8F",
    "social":         "#F4A261",
    "display":        "#457B9D",
    "baseline":       "#A8DADC",
    "revenue":        "#1D3557",
    "canada":         "#E63946",
    "united_states":  "#2A9D8F",
    "germany":        "#F4A261",
    "japan":          "#6A4C93",
    "australia":      "#E9C46A",
    "population":     "#1D3557",
}

plt.rcParams.update({
    "font.family":       "DejaVu Sans",
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "axes.grid":         True,
    "grid.alpha":        0.3,
    "grid.linestyle":    "--",
    "figure.facecolor":  "#FAFAFA",
    "axes.facecolor":    "#FAFAFA",
})


# ══════════════════════════════════════════════════════════════════════════════
# 2. GROUND TRUTH (recovery targets — mirrors data_generation.py)
# ══════════════════════════════════════════════════════════════════════════════

TRUE_PARAMS = {
    # Adstock decay rates (shared across regions in DGP)
    "adstock": {
        "tv":          0.75,
        "paid_search": 0.20,
        "social":      0.45,
        "display":     0.15,
    },
    # Hill slope k
    "hill_k": {
        "tv":          2.5,
        "paid_search": 1.5,
        "social":      1.2,
        "display":     3.0,
    },
    # Hill half-saturation ec
    "hill_ec": {
        "tv":          0.4,
        "paid_search": 0.6,
        "social":      0.7,
        "display":     0.3,
    },
    # Per-region channel betas (max revenue contribution when saturated)
    "beta": {
        "canada": {
            "tv": 320_000, "paid_search": 260_000,
            "social": 200_000, "display": 80_000,
        },
        "united_states": {
            "tv": 240_000, "paid_search": 195_000,
            "social": 150_000, "display": 60_000,
        },
        "germany": {
            "tv": 110_000, "paid_search":  90_000,
            "social":  70_000, "display": 28_000,
        },
        "japan": {
            "tv":  95_000, "paid_search":  78_000,
            "social":  60_000, "display": 24_000,
        },
        "australia": {
            "tv":  35_000, "paid_search":  29_000,
            "social":  22_000, "display":  9_000,
        },
    },
    # Per-region baseline intercepts and trend slopes
    "intercept": {
        "canada": 620_000, "united_states": 430_000, "germany": 180_000,
        "japan": 150_000, "australia": 55_000,
    },
    "trend_slope": {
        "canada": 950, "united_states": 700, "germany": 350,
        "japan": 400, "australia": 280,
    },
    "noise_std": {
        "canada": 28_000, "united_states": 20_000, "germany": 9_000,
        "japan": 8_000, "australia": 5_000,
    },
}


# ══════════════════════════════════════════════════════════════════════════════
# 3. DATA LOADING & PREPROCESSING
# ══════════════════════════════════════════════════════════════════════════════

def load_all_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Load synthetic_raw.csv and ground_truth.csv for all 5 regions.

    Returns
    -------
    raw_df : pd.DataFrame  — spend + observed revenue for all regions
    gt_df  : pd.DataFrame  — true baseline, contributions, parameters
    """
    raw_df = pd.read_csv("synthetic_raw.csv", parse_dates=["date"])
    gt_df  = pd.read_csv("ground_truth.csv",  parse_dates=["date"])

    print(f"  Loaded {len(raw_df)} total rows ({N_REGIONS} regions × {N_WEEKS} weeks).")
    for region in REGIONS:
        sub = raw_df[raw_df["region"] == region]
        print(f"    {REGION_LABELS[region]:>15s}: "
              f"${sub['revenue'].min():>10,.0f} – ${sub['revenue'].max():>10,.0f}")
    return raw_df, gt_df


def _build_lag_matrix(spend: np.ndarray, max_lag: int = MAX_LAG) -> np.ndarray:
    """
    Build (T, max_lag) lag matrix from a 1-D spend array.

    lag_matrix[t, l] = spend[t - l]  (zero-padded for t < l)

    Enables vectorised geometric adstock as a single dot product inside PyMC:
        adstock[t] = lag_matrix[t] · (alpha^0, alpha^1, ..., alpha^{L-1})
    """
    T = len(spend)
    lag_mat = np.zeros((T, max_lag), dtype=float)
    for l in range(max_lag):
        lag_mat[l:, l] = spend[:T - l]
    return lag_mat


def build_hierarchical_inputs(raw_df: pd.DataFrame) -> dict:
    """
    Construct all numpy arrays the hierarchical PyMC model needs.

    Arrays are indexed [region, time] or [region, time, lag] so the model
    can operate over all regions simultaneously.

    Key outputs
    -----------
    revenue       : (R, T)          — observed weekly revenue
    lag_matrices  : {ch: (R, T, L)} — precomputed lag matrices per channel
    p95           : {ch: (R,)}      — p95 normalisation constants per channel/region
    fourier       : (T, 4)          — Fourier features (same for all regions / same dates)
    holiday_matrix: (T, H)          — holiday indicator matrix
    t_std         : (T,)            — standardised time index [0, 1]
    lags          : (L,)            — integer lag indices [0..L-1]
    """
    T    = N_WEEKS
    lags = np.arange(MAX_LAG, dtype=float)

    # ── Time and Fourier features (identical across regions — same date range) ──
    t     = np.arange(T, dtype=float)
    t_std = t / (T - 1)

    fourier = np.column_stack([
        np.sin(2 * np.pi * 1 * t / 52),
        np.cos(2 * np.pi * 1 * t / 52),
        np.sin(2 * np.pi * 2 * t / 52),
        np.cos(2 * np.pi * 2 * t / 52),
    ])  # (T, 4)

    # Use the first region's dates for holiday matrix (same calendar for all)
    first_region_df = raw_df[raw_df["region"] == REGIONS[0]].reset_index(drop=True)
    week_of_year    = first_region_df["date"].dt.isocalendar().week.values.astype(int)
    holiday_matrix  = np.zeros((T, len(HOLIDAY_WEEKS)), dtype=float)
    for j, hw in enumerate(HOLIDAY_WEEKS):
        holiday_matrix[:, j] = (week_of_year == hw).astype(float)

    # ── Per-region spend preprocessing ─────────────────────────────────────────
    revenue_list      = []
    lag_matrices_list = {ch: [] for ch in CHANNELS}
    p95_list          = {ch: [] for ch in CHANNELS}
    dates_list        = []

    for region in REGIONS:
        df = raw_df[raw_df["region"] == region].reset_index(drop=True)
        revenue_list.append(df["revenue"].values.astype(float))
        dates_list.append(df["date"].values)

        for ch in CHANNELS:
            spend   = df[f"spend_{ch}"].values.astype(float)
            lag_mat = _build_lag_matrix(spend, MAX_LAG)
            lag_matrices_list[ch].append(lag_mat)

            # p95 normalisation: computed at the true alpha so Hill ec stays
            # interpretable on [0, 1]. Same logic as Phase 3 — fixed constant.
            alpha_true = TRUE_PARAMS["adstock"][ch]
            weights    = alpha_true ** lags
            ads_true   = lag_mat @ weights
            p95_list[ch].append(float(np.percentile(ads_true, 95)))

    revenue = np.stack(revenue_list)  # (R, T)

    # Stack to (R, T, L) for lag matrices, (R,) for p95
    lag_matrices = {ch: np.stack(lag_matrices_list[ch]) for ch in CHANNELS}
    p95          = {ch: np.array(p95_list[ch])           for ch in CHANNELS}

    return {
        "R":              N_REGIONS,
        "T":              T,
        "t":              t,
        "t_std":          t_std,
        "fourier":        fourier,
        "holiday_matrix": holiday_matrix,
        "week_of_year":   week_of_year,
        "revenue":        revenue,
        "lag_matrices":   lag_matrices,
        "p95":            p95,
        "lags":           lags,
        "dates":          dates_list[0],   # same for all regions
    }


# ══════════════════════════════════════════════════════════════════════════════
# 4. PYTENSOR MEDIA TRANSFORMS (vectorised, no scan)
# ══════════════════════════════════════════════════════════════════════════════

def pytensor_geometric_adstock_vec(lag_matrix: pt.TensorVariable,
                                    lags: np.ndarray,
                                    alpha: pt.TensorVariable) -> pt.TensorVariable:
    """
    Vectorised geometric adstock via lag-matrix dot product — no scan required.

    adstock[t] = Σ_{l=0}^{L-1} alpha^l × spend[t-l]
               = lag_matrix[t] · weight_vector

    Parameters
    ----------
    lag_matrix : (T, MAX_LAG) — fixed data constant
    lags       : (MAX_LAG,)  — integer lag indices
    alpha      : scalar symbolic decay rate in [0, 1)

    Returns
    -------
    pt.TensorVariable of shape (T,)
    """
    weights = alpha ** pt.as_tensor_variable(lags)
    return pt.dot(lag_matrix, weights)


def pytensor_hill(x: pt.TensorVariable,
                  k: pt.TensorVariable,
                  ec: pt.TensorVariable) -> pt.TensorVariable:
    """
    Hill saturation: S(x) = x^k / (x^k + ec^k)

    Numerically safe: replaces x=0 with a small epsilon so gradients are
    well-defined. The result is effectively 0 at x ≈ 0.
    """
    safe_x = pt.switch(pt.eq(x, 0.0), 1e-10, x)
    return safe_x**k / (safe_x**k + ec**k)


# ══════════════════════════════════════════════════════════════════════════════
# 5. MODEL DEFINITION
# ══════════════════════════════════════════════════════════════════════════════

def build_hierarchical_model(inputs: dict) -> pm.Model:
    """
    Build the hierarchical Bayesian MMM for all 5 regions.

    Parameterisation
    ----------------
    All per-region parameters use the non-centered parameterisation:

        param[r] = μ_param + σ_param × z_param[r]
        z_param[r] ~ Normal(0, 1)

    This improves NUTS geometry by decoupling the population-level parameters
    from the per-region offsets, reducing funnel-shaped posteriors.

    For parameters constrained to (0, 1) — alpha, ec — the raw non-centered
    value is clipped after shifting. An alternative is to work in logit space,
    but clipping is simpler and adequate when σ_param is small.

    For parameters constrained to (0, ∞) — k, beta — we use a log-normal
    non-centered parameterisation:
        log_param[r] = μ_log_param + σ_log_param × z_param[r]
        param[r]     = exp(log_param[r])

    Baseline parameters (intercept, trend_slope) also get partial pooling
    across regions, which is particularly valuable for Australia (smallest
    market, shortest effective data series).

    Baseline structure (per region)
    --------------------------------
    Baseline[r, t] = intercept[r]
                   + trend_slope[r] × t_std[t]
                   + fourier[t] · fourier_coefs[r, :]
                   + holiday_matrix[t] · holiday_deltas[r, :]
    """
    R              = inputs["R"]
    T              = inputs["T"]
    lags           = inputs["lags"]
    t_std          = pt.as_tensor_variable(inputs["t_std"].astype("float64"))
    fourier        = pt.as_tensor_variable(inputs["fourier"].astype("float64"))
    holiday_matrix = pt.as_tensor_variable(inputs["holiday_matrix"].astype("float64"))
    revenue_obs    = inputs["revenue"].astype("float64")   # (R, T)

    with pm.Model() as model:

        # ════════════════════════════════════════════════════════════════════
        # HYPERPRIORS — population-level distributions
        # ════════════════════════════════════════════════════════════════════

        # ── Adstock decay rates ───────────────────────────────────────────────
        # Population mean: channel-informed (same as Phase 3 per-channel priors).
        # Population spread σ ~ HalfNormal(0.15): most of the mass puts
        # cross-region variation within ±0.3 of the mean — regions share the
        # same channel type, so extreme divergence is not expected.

        mu_alpha_tv    = pm.Beta("mu_alpha_tv",   alpha=8,  beta=3)    # mean≈0.73
        mu_alpha_ps    = pm.Beta("mu_alpha_ps",   alpha=2,  beta=8)    # mean≈0.20
        mu_alpha_so    = pm.Beta("mu_alpha_so",   alpha=5,  beta=6)    # mean≈0.45
        mu_alpha_disp  = pm.Beta("mu_alpha_disp", alpha=2,  beta=10)   # mean≈0.17

        sigma_alpha_tv   = pm.HalfNormal("sigma_alpha_tv",   sigma=0.15)
        sigma_alpha_ps   = pm.HalfNormal("sigma_alpha_ps",   sigma=0.10)
        sigma_alpha_so   = pm.HalfNormal("sigma_alpha_so",   sigma=0.12)
        sigma_alpha_disp = pm.HalfNormal("sigma_alpha_disp", sigma=0.08)

        # ── Hill slope k ───────────────────────────────────────────────────────
        # Log-normal NCP: log(k) ~ Normal(μ_log_k, σ_log_k)
        # Priors on μ_log_k centred at log(true_k) for each channel.

        mu_log_k_tv   = pm.Normal("mu_log_k_tv",   mu=np.log(2.5), sigma=0.5)
        mu_log_k_ps   = pm.Normal("mu_log_k_ps",   mu=np.log(1.5), sigma=0.5)
        mu_log_k_so   = pm.Normal("mu_log_k_so",   mu=np.log(1.2), sigma=0.5)
        mu_log_k_disp = pm.Normal("mu_log_k_disp", mu=np.log(3.0), sigma=0.5)

        sigma_log_k_tv   = pm.HalfNormal("sigma_log_k_tv",   sigma=0.3)
        sigma_log_k_ps   = pm.HalfNormal("sigma_log_k_ps",   sigma=0.3)
        sigma_log_k_so   = pm.HalfNormal("sigma_log_k_so",   sigma=0.3)
        sigma_log_k_disp = pm.HalfNormal("sigma_log_k_disp", sigma=0.3)

        # ── Hill half-saturation ec ────────────────────────────────────────────
        # ec lives in (0, 1). Same NCP structure as alpha.

        mu_ec_tv   = pm.Beta("mu_ec_tv",   alpha=4, beta=6)    # mean≈0.40
        mu_ec_ps   = pm.Beta("mu_ec_ps",   alpha=6, beta=4)    # mean≈0.60
        mu_ec_so   = pm.Beta("mu_ec_so",   alpha=7, beta=3)    # mean≈0.70
        mu_ec_disp = pm.Beta("mu_ec_disp", alpha=3, beta=7)    # mean≈0.30

        sigma_ec_tv   = pm.HalfNormal("sigma_ec_tv",   sigma=0.10)
        sigma_ec_ps   = pm.HalfNormal("sigma_ec_ps",   sigma=0.10)
        sigma_ec_so   = pm.HalfNormal("sigma_ec_so",   sigma=0.10)
        sigma_ec_disp = pm.HalfNormal("sigma_ec_disp", sigma=0.10)

        # ── Channel coefficients β ─────────────────────────────────────────────
        # Log-normal NCP. Population means anchored near the largest market (Canada).
        # σ_log_beta ~ HalfNormal(0.5) allows ~2× variation across regions, which
        # matches the DGP (Canada beta ≈ 3.4× Australia beta for TV).

        mu_log_beta_tv   = pm.Normal("mu_log_beta_tv",   mu=np.log(200_000), sigma=0.8)
        mu_log_beta_ps   = pm.Normal("mu_log_beta_ps",   mu=np.log(160_000), sigma=0.8)
        mu_log_beta_so   = pm.Normal("mu_log_beta_so",   mu=np.log(120_000), sigma=0.8)
        mu_log_beta_disp = pm.Normal("mu_log_beta_disp", mu=np.log( 48_000), sigma=0.8)

        sigma_log_beta_tv   = pm.HalfNormal("sigma_log_beta_tv",   sigma=0.6)
        sigma_log_beta_ps   = pm.HalfNormal("sigma_log_beta_ps",   sigma=0.6)
        sigma_log_beta_so   = pm.HalfNormal("sigma_log_beta_so",   sigma=0.6)
        sigma_log_beta_disp = pm.HalfNormal("sigma_log_beta_disp", sigma=0.6)

        # ── Baseline: intercept ────────────────────────────────────────────────
        # Log-normal NCP. Population mean near log($200K) — a diffuse centre
        # between Australia ($55K) and Canada ($620K).

        mu_log_intercept    = pm.Normal("mu_log_intercept",    mu=np.log(250_000), sigma=1.0)
        sigma_log_intercept = pm.HalfNormal("sigma_log_intercept", sigma=0.8)

        # ── Baseline: trend slope ─────────────────────────────────────────────
        # Log-normal NCP. Positive slopes are correct (growing brand).
        # Population mean near log($500) = mid-range of true slopes.

        mu_log_trend    = pm.Normal("mu_log_trend",    mu=np.log(500), sigma=0.8)
        sigma_log_trend = pm.HalfNormal("sigma_log_trend", sigma=0.5)

        # ── Revenue noise σ ────────────────────────────────────────────────────
        # Separate σ per region: noise scales with market size.
        # HalfNormal(50_000) is diffuse; data-driven estimate expected.

        sigma_rev = pm.HalfNormal("sigma_rev", sigma=50_000, shape=R)

        # ── Fourier seasonality coefficients ───────────────────────────────────
        # Partial pooling across regions: population mean ~ Normal(0, 30_000),
        # per-region offsets add additional flexibility.
        # Shape: (4,) for population mean, (R, 4) for per-region offsets.

        mu_fourier    = pm.Normal("mu_fourier",    mu=0, sigma=30_000, shape=4)
        sigma_fourier = pm.HalfNormal("sigma_fourier", sigma=15_000, shape=4)
        z_fourier     = pm.Normal("z_fourier", mu=0, sigma=1, shape=(R, 4))
        fourier_coefs = pm.Deterministic(
            "fourier_coefs", mu_fourier[None, :] + sigma_fourier[None, :] * z_fourier
        )  # (R, 4)

        # ── Holiday deltas ─────────────────────────────────────────────────────
        # Pooled across regions: all regions experience the same promotional
        # calendar (Black Friday, spring launch, etc.) with shared direction.
        # HalfNormal on σ: cross-region variation exists but is moderate.

        mu_holidays    = pm.Normal("mu_holidays",    mu=0, sigma=0.25, shape=len(HOLIDAY_WEEKS))
        sigma_holidays = pm.HalfNormal("sigma_holidays", sigma=0.10,  shape=len(HOLIDAY_WEEKS))
        z_holidays     = pm.Normal("z_holidays", mu=0, sigma=1, shape=(R, len(HOLIDAY_WEEKS)))
        holiday_deltas = pm.Deterministic(
            "holiday_deltas",
            mu_holidays[None, :] + sigma_holidays[None, :] * z_holidays
        )  # (R, H)


        # ════════════════════════════════════════════════════════════════════
        # NON-CENTERED PER-REGION PARAMETERS
        # ════════════════════════════════════════════════════════════════════

        # ── Adstock offsets ────────────────────────────────────────────────────
        z_alpha_tv   = pm.Normal("z_alpha_tv",   mu=0, sigma=1, shape=R)
        z_alpha_ps   = pm.Normal("z_alpha_ps",   mu=0, sigma=1, shape=R)
        z_alpha_so   = pm.Normal("z_alpha_so",   mu=0, sigma=1, shape=R)
        z_alpha_disp = pm.Normal("z_alpha_disp", mu=0, sigma=1, shape=R)

        alpha_tv   = pm.Deterministic("alpha_tv",
            pt.clip(mu_alpha_tv   + sigma_alpha_tv   * z_alpha_tv,   0.01, 0.99))
        alpha_ps   = pm.Deterministic("alpha_ps",
            pt.clip(mu_alpha_ps   + sigma_alpha_ps   * z_alpha_ps,   0.01, 0.99))
        alpha_so   = pm.Deterministic("alpha_so",
            pt.clip(mu_alpha_so   + sigma_alpha_so   * z_alpha_so,   0.01, 0.99))
        alpha_disp = pm.Deterministic("alpha_disp",
            pt.clip(mu_alpha_disp + sigma_alpha_disp * z_alpha_disp, 0.01, 0.99))

        alphas = {"tv": alpha_tv, "paid_search": alpha_ps,
                  "social": alpha_so, "display": alpha_disp}

        # ── Hill k offsets (log-normal NCP) ───────────────────────────────────
        z_k_tv   = pm.Normal("z_k_tv",   mu=0, sigma=1, shape=R)
        z_k_ps   = pm.Normal("z_k_ps",   mu=0, sigma=1, shape=R)
        z_k_so   = pm.Normal("z_k_so",   mu=0, sigma=1, shape=R)
        z_k_disp = pm.Normal("z_k_disp", mu=0, sigma=1, shape=R)

        k_tv   = pm.Deterministic("k_tv",   pt.exp(mu_log_k_tv   + sigma_log_k_tv   * z_k_tv))
        k_ps   = pm.Deterministic("k_ps",   pt.exp(mu_log_k_ps   + sigma_log_k_ps   * z_k_ps))
        k_so   = pm.Deterministic("k_so",   pt.exp(mu_log_k_so   + sigma_log_k_so   * z_k_so))
        k_disp = pm.Deterministic("k_disp", pt.exp(mu_log_k_disp + sigma_log_k_disp * z_k_disp))

        ks = {"tv": k_tv, "paid_search": k_ps, "social": k_so, "display": k_disp}

        # ── Hill ec offsets ────────────────────────────────────────────────────
        z_ec_tv   = pm.Normal("z_ec_tv",   mu=0, sigma=1, shape=R)
        z_ec_ps   = pm.Normal("z_ec_ps",   mu=0, sigma=1, shape=R)
        z_ec_so   = pm.Normal("z_ec_so",   mu=0, sigma=1, shape=R)
        z_ec_disp = pm.Normal("z_ec_disp", mu=0, sigma=1, shape=R)

        ec_tv   = pm.Deterministic("ec_tv",
            pt.clip(mu_ec_tv   + sigma_ec_tv   * z_ec_tv,   0.01, 0.99))
        ec_ps   = pm.Deterministic("ec_ps",
            pt.clip(mu_ec_ps   + sigma_ec_ps   * z_ec_ps,   0.01, 0.99))
        ec_so   = pm.Deterministic("ec_so",
            pt.clip(mu_ec_so   + sigma_ec_so   * z_ec_so,   0.01, 0.99))
        ec_disp = pm.Deterministic("ec_disp",
            pt.clip(mu_ec_disp + sigma_ec_disp * z_ec_disp, 0.01, 0.99))

        ecs = {"tv": ec_tv, "paid_search": ec_ps, "social": ec_so, "display": ec_disp}

        # ── Beta offsets (log-normal NCP) ──────────────────────────────────────
        z_beta_tv   = pm.Normal("z_beta_tv",   mu=0, sigma=1, shape=R)
        z_beta_ps   = pm.Normal("z_beta_ps",   mu=0, sigma=1, shape=R)
        z_beta_so   = pm.Normal("z_beta_so",   mu=0, sigma=1, shape=R)
        z_beta_disp = pm.Normal("z_beta_disp", mu=0, sigma=1, shape=R)

        beta_tv   = pm.Deterministic("beta_tv",
            pt.exp(mu_log_beta_tv   + sigma_log_beta_tv   * z_beta_tv))
        beta_ps   = pm.Deterministic("beta_ps",
            pt.exp(mu_log_beta_ps   + sigma_log_beta_ps   * z_beta_ps))
        beta_so   = pm.Deterministic("beta_so",
            pt.exp(mu_log_beta_so   + sigma_log_beta_so   * z_beta_so))
        beta_disp = pm.Deterministic("beta_disp",
            pt.exp(mu_log_beta_disp + sigma_log_beta_disp * z_beta_disp))

        betas = {"tv": beta_tv, "paid_search": beta_ps,
                 "social": beta_so, "display": beta_disp}

        # ── Intercept offsets (log-normal NCP) ────────────────────────────────
        z_intercept = pm.Normal("z_intercept", mu=0, sigma=1, shape=R)
        intercept   = pm.Deterministic("intercept",
            pt.exp(mu_log_intercept + sigma_log_intercept * z_intercept))   # (R,)

        # ── Trend slope offsets (log-normal NCP) ──────────────────────────────
        z_trend    = pm.Normal("z_trend",    mu=0, sigma=1, shape=R)
        trend_slope = pm.Deterministic("trend_slope",
            pt.exp(mu_log_trend + sigma_log_trend * z_trend))   # (R,)


        # ════════════════════════════════════════════════════════════════════
        # DETERMINISTIC QUANTITIES — built region by region, then stacked
        # ════════════════════════════════════════════════════════════════════

        region_mus = []

        for r, region in enumerate(REGIONS):

            # ── Baseline ──────────────────────────────────────────────────────
            # intercept[r] and trend_slope[r] are (R,) deterministics — slice.
            trend_r      = intercept[r] + trend_slope[r] * t_std   # (T,)
            seasonal_r   = pt.dot(fourier, fourier_coefs[r])        # (T,)
            holiday_r    = pt.dot(holiday_matrix, holiday_deltas[r]) * intercept[r]  # (T,)
            baseline_r   = pm.Deterministic(
                f"baseline_{region}", trend_r + seasonal_r + holiday_r
            )

            # ── Media contributions ───────────────────────────────────────────
            region_contribs = []
            for ch in CHANNELS:
                lag_mat_r = pt.as_tensor_variable(
                    inputs["lag_matrices"][ch][r].astype("float64")
                )   # (T, MAX_LAG)
                p95_r = inputs["p95"][ch][r]   # fixed scalar

                adstock_r      = pytensor_geometric_adstock_vec(
                    lag_mat_r, inputs["lags"], alphas[ch][r]
                )   # (T,)
                adstock_norm_r = adstock_r / p95_r
                saturated_r    = pytensor_hill(adstock_norm_r, ks[ch][r], ecs[ch][r])
                contrib_r      = pm.Deterministic(
                    f"contrib_{ch}_{region}", betas[ch][r] * saturated_r
                )   # (T,)
                region_contribs.append(contrib_r)

            total_media_r = sum(region_contribs)
            mu_r          = baseline_r + total_media_r   # (T,)
            region_mus.append(mu_r)

        # Stack all regions: (R, T)
        mu = pm.Deterministic("mu", pt.stack(region_mus, axis=0))   # (R, T)

        # ── Likelihood ────────────────────────────────────────────────────────
        # sigma_rev is (R,) — broadcast to (R, T) via [:, None]
        revenue_rv = pm.Normal(
            "revenue",
            mu=mu,
            sigma=sigma_rev[:, None],
            observed=revenue_obs,
        )

    return model


# ══════════════════════════════════════════════════════════════════════════════
# 6. PRIOR PREDICTIVE CHECK
# ══════════════════════════════════════════════════════════════════════════════

def run_prior_predictive(model: pm.Model,
                          inputs: dict,
                          n_samples: int = 300,
                          save_path: str = "outputs/fig_prior_predictive_hier.png"):
    """
    Sample from the prior only and plot implied revenue distributions for all regions.

    A well-calibrated prior should:
      - Comfortably cover each region's observed revenue range
      - Not put appreciable mass below $0 or above $5M (for the smallest markets,
        upper bounds are much lower — Australia max ~$200K)
    """
    print("\n  Running prior predictive check...")
    with model:
        prior_pred = pm.sample_prior_predictive(samples=n_samples, random_seed=RANDOM_SEED)

    # prior_predictive["revenue"] shape: (1, n_samples, R, T) — squeeze chain dim
    prior_draws = prior_pred.prior_predictive["revenue"].values[0]   # (n_samples, R, T)
    dates        = pd.to_datetime(inputs["dates"])

    fig, axes = plt.subplots(N_REGIONS, 2, figsize=(16, 4 * N_REGIONS))
    fig.suptitle(
        "Prior Predictive Check — All Regions\n"
        "Do the hierarchical priors allow plausible revenue trajectories?",
        fontsize=13, fontweight="bold",
    )

    for r, region in enumerate(REGIONS):
        draws_r  = prior_draws[:, r, :]   # (n_samples, T)
        observed = inputs["revenue"][r]

        p05 = np.percentile(draws_r,  5, axis=0)
        p25 = np.percentile(draws_r, 25, axis=0)
        p50 = np.percentile(draws_r, 50, axis=0)
        p75 = np.percentile(draws_r, 75, axis=0)
        p95 = np.percentile(draws_r, 95, axis=0)

        color = PALETTE[region]

        # ── Fan chart ─────────────────────────────────────────────────────────
        ax = axes[r, 0]
        ax.fill_between(dates, p05, p95, alpha=0.20, color=color, label="5–95th pct")
        ax.fill_between(dates, p25, p75, alpha=0.35, color=color, label="25–75th pct")
        ax.plot(dates, p50,      color=color,    lw=1.5, label="Median prior")
        ax.plot(dates, observed, color="#1D3557", lw=1.2, alpha=0.9, label="Observed")
        ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x/1e3:.0f}K"))
        ax.set_title(f"{REGION_LABELS[region]} — Prior fan", fontsize=10, color=color,
                     fontweight="bold")
        ax.set_ylabel("Revenue")
        ax.legend(fontsize=7, loc="upper left", ncol=2)

        # ── Marginal histogram ────────────────────────────────────────────────
        ax = axes[r, 1]
        flat    = draws_r.flatten()
        clipped = flat[(flat > -2e6) & (flat < observed.max() * 5)]
        ax.hist(clipped / 1e3, bins=60, color=color, alpha=0.65,
                edgecolor="white", linewidth=0.3)
        obs_min, obs_max = observed.min() / 1e3, observed.max() / 1e3
        ax.axvspan(obs_min, obs_max, alpha=0.25, color="#1D3557",
                   label=f"Observed range\n(${obs_min:.0f}K–${obs_max:.0f}K)")
        ax.axvline(0, color="black", lw=1.2, linestyle="--", alpha=0.6)
        ax.set_xlabel("Revenue ($K)")
        ax.set_ylabel("Count")
        ax.set_title("Marginal prior distribution", fontsize=10)
        ax.legend(fontsize=7)

        pct_neg  = (draws_r < 0).mean() * 100
        print(f"    {REGION_LABELS[region]:>15s}: "
              f"median prior ${np.median(draws_r):>9,.0f} | "
              f"{pct_neg:.1f}% draws < $0")

    plt.tight_layout()
    plt.savefig(save_path, dpi=130, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Prior predictive saved: {save_path}")

    return prior_pred


# ══════════════════════════════════════════════════════════════════════════════
# 7. MCMC SAMPLING & DIAGNOSTICS
# ══════════════════════════════════════════════════════════════════════════════

def run_sampling(model: pm.Model,
                 draws: int = 1000,
                 tune: int = 1000,
                 chains: int = 4,
                 target_accept: float = 0.92) -> az.InferenceData:
    """
    Sample the posterior with NUTS.

    Sampler settings
    ----------------
    tune=1000         : Generous warmup. Hierarchical models need more tuning
                        steps than single-region models because the hyperprior
                        geometry requires careful mass-matrix adaptation.
    target_accept=0.92: Slightly higher than Phase 3 (0.90) to handle the
                        more complex posterior geometry of the hierarchical model.
                        If divergences appear, increase to 0.95.
    chains=4          : 4 independent chains allow reliable R-hat computation
                        and chain-level stationarity checks.
    """
    print(f"\n  Sampling posterior (chains={chains}, draws={draws}, tune={tune})...")
    print(f"  Hierarchical models are slower than single-region.")
    print(f"  Expect ~5–15 minutes depending on your hardware.\n")

    with model:
        idata = pm.sample(
            draws=draws,
            tune=tune,
            chains=chains,
            target_accept=target_accept,
            random_seed=RANDOM_SEED,
            progressbar=True,
            nuts_sampler="numpyro",
            idata_kwargs={"log_likelihood": True},
        )

    return idata


def run_diagnostics(idata: az.InferenceData,
                    save_path: str = "outputs/fig_trace_hier.png"):
    """
    Run ArviZ diagnostics and save trace plots for key population-level parameters.

    Convergence criteria
    --------------------
    R-hat < 1.01  : Strong convergence (< 1.05 acceptable minimum).
    ESS > 400     : Enough effective samples for reliable inference.
    Divergences   : Any divergences indicate model geometry problems.
                    Common fixes: increase target_accept, tighten σ hyperpriors,
                    or switch alpha/ec to full logit-normal parameterisation.
    """
    print("\n  Running diagnostics...")

    # ── R-hat / ESS summary on population-level parameters ───────────────────
    pop_vars = [
        "mu_alpha_tv", "mu_alpha_ps", "mu_alpha_so", "mu_alpha_disp",
        "sigma_alpha_tv", "sigma_alpha_ps",
        "mu_log_k_tv", "mu_log_k_ps", "mu_log_k_so", "mu_log_k_disp",
        "mu_ec_tv", "mu_ec_ps", "mu_ec_so", "mu_ec_disp",
        "mu_log_beta_tv", "mu_log_beta_ps", "mu_log_beta_so", "mu_log_beta_disp",
        "mu_log_intercept", "mu_log_trend",
    ]

    # Per-region parameter arrays (shape R per param)
    region_vars = [
        "alpha_tv", "alpha_ps", "alpha_so", "alpha_disp",
        "k_tv", "k_ps", "k_so", "k_disp",
        "ec_tv", "ec_ps", "ec_so", "ec_disp",
        "beta_tv", "beta_ps", "beta_so", "beta_disp",
        "intercept", "trend_slope",
    ]

    all_diag_vars = pop_vars + region_vars
    summary = az.summary(idata, var_names=all_diag_vars, round_to=4)

    print("\n  ── Population-Level Posterior Summary ──")
    pop_summary = az.summary(idata, var_names=pop_vars, round_to=4)
    print(pop_summary[["mean", "sd", "hdi_3%", "hdi_97%", "r_hat", "ess_bulk"]].to_string())

    n_divergences = int(idata.sample_stats["diverging"].values.sum())
    print(f"\n  Divergences: {n_divergences}")
    if n_divergences > 0:
        print("  ⚠ Divergences detected.")
        print("    → Try: higher target_accept (0.95+), tighter sigma hyperpriors,")
        print("           or logit-normal parameterisation for alpha/ec.")
    else:
        print("  ✓ No divergences.")

    max_rhat = summary["r_hat"].dropna().max()
    n_bad    = (summary["r_hat"].dropna() > 1.01).sum()
    min_ess  = summary["ess_bulk"].min()
    print(f"\n  Max R-hat across all params: {max_rhat:.4f}  (target: < 1.01)")
    print(f"  Parameters with R-hat > 1.01: {n_bad}")
    print(f"  Min bulk ESS: {min_ess:.0f}  (target: > 400)")

    # ── Trace plots — population-level only (per-region arrays too large) ─────
    trace_vars = [
        "mu_alpha_tv", "mu_alpha_ps",
        "mu_log_k_tv", "mu_log_k_ps",
        "mu_ec_tv", "mu_ec_ps",
        "mu_log_beta_tv", "mu_log_beta_ps",
        "mu_log_intercept", "mu_log_trend",
    ]

    axes = az.plot_trace(
        idata,
        var_names=trace_vars,
        figsize=(14, 22),
        compact=True,
    )
    fig = axes.ravel()[0].get_figure()
    fig.suptitle(
        "MCMC Trace Plots — Population-Level Hyperparameters\n"
        "Left: posterior density  |  Right: sample trace (should look like 'fuzzy caterpillar')",
        fontsize=11, fontweight="bold", y=1.005,
    )
    plt.tight_layout()
    plt.savefig(save_path, dpi=120, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Trace plot saved: {save_path}")

    return summary


# ══════════════════════════════════════════════════════════════════════════════
# 8. PARAMETER RECOVERY
# ══════════════════════════════════════════════════════════════════════════════

def plot_parameter_recovery(idata: az.InferenceData,
                             save_path: str = "outputs/fig_parameter_recovery_hier.png"):
    """
    Plot posterior distributions against true DGP values for all regions.

    Layout: one column per region, one row per parameter group (alpha, k, ec, beta).
    The true DGP adstock/Hill parameters are shared across regions — individual
    region posteriors should all be near the same true value.
    Betas differ per region — each panel shows that region's true value.

    Expected pattern
    ----------------
    - Large markets (Canada, US): narrower posteriors, closer to true value.
    - Small market (Australia): wider posteriors, more shrinkage toward population mean.
    - This differential posterior width IS the partial pooling working correctly.
    """
    print("\n  Plotting parameter recovery...")

    posterior = idata.posterior

    # Parameters with a single true value shared across all regions
    shared_params = {
        "alpha_tv":   TRUE_PARAMS["adstock"]["tv"],
        "alpha_ps":   TRUE_PARAMS["adstock"]["paid_search"],
        "alpha_so":   TRUE_PARAMS["adstock"]["social"],
        "alpha_disp": TRUE_PARAMS["adstock"]["display"],
        "k_tv":       TRUE_PARAMS["hill_k"]["tv"],
        "k_ps":       TRUE_PARAMS["hill_k"]["paid_search"],
        "k_so":       TRUE_PARAMS["hill_k"]["social"],
        "k_disp":     TRUE_PARAMS["hill_k"]["display"],
        "ec_tv":      TRUE_PARAMS["hill_ec"]["tv"],
        "ec_ps":      TRUE_PARAMS["hill_ec"]["paid_search"],
        "ec_so":      TRUE_PARAMS["hill_ec"]["social"],
        "ec_disp":    TRUE_PARAMS["hill_ec"]["display"],
    }
    shared_labels = {
        "alpha_tv": "α TV", "alpha_ps": "α Paid Search",
        "alpha_so": "α Social", "alpha_disp": "α Display",
        "k_tv": "k TV", "k_ps": "k Paid Search",
        "k_so": "k Social", "k_disp": "k Display",
        "ec_tv": "ec TV", "ec_ps": "ec Paid Search",
        "ec_so": "ec Social", "ec_disp": "ec Display",
    }
    ch_colors = {
        "tv": PALETTE["tv"], "paid_search": PALETTE["paid_search"],
        "social": PALETTE["social"], "display": PALETTE["display"],
    }
    param_colors = {
        "alpha_tv": ch_colors["tv"], "alpha_ps": ch_colors["paid_search"],
        "alpha_so": ch_colors["social"], "alpha_disp": ch_colors["display"],
        "k_tv": ch_colors["tv"], "k_ps": ch_colors["paid_search"],
        "k_so": ch_colors["social"], "k_disp": ch_colors["display"],
        "ec_tv": ch_colors["tv"], "ec_ps": ch_colors["paid_search"],
        "ec_so": ch_colors["social"], "ec_disp": ch_colors["display"],
    }

    n_params = len(shared_params)
    n_cols   = N_REGIONS
    n_rows   = n_params

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(4 * N_REGIONS, 3 * n_rows))

    recovery_count = 0
    total_checks   = 0

    for row_i, (param, true_val) in enumerate(shared_params.items()):
        color = param_colors[param]
        for col_i, region in enumerate(REGIONS):
            ax = axes[row_i, col_i]

            # posterior[param] shape: (chains, draws, R) — select region index
            samples = posterior[param].values[:, :, col_i].flatten()

            az.plot_kde(
                samples,
                ax=ax,
                plot_kwargs={"color": color, "linewidth": 1.8},
                fill_kwargs={"alpha": 0.25, "color": color},
            )
            ax.axvline(true_val, color="black", lw=1.8, linestyle="--",
                       label=f"True: {true_val:.2f}")

            hdi = az.hdi(samples, hdi_prob=0.94)
            ax.axvspan(hdi[0], hdi[1], alpha=0.10, color=color)

            inside = hdi[0] <= true_val <= hdi[1]
            marker = "✓" if inside else "✗"
            if inside:
                recovery_count += 1
            total_checks += 1

            if row_i == 0:
                ax.set_title(REGION_LABELS[region], fontsize=9, fontweight="bold",
                             color=PALETTE[region])
            if col_i == 0:
                ax.set_ylabel(shared_labels[param], fontsize=8)

            ax.set_xlabel("")
            ax.tick_params(labelsize=6)
            ax.set_title(
                (ax.get_title() + "\n" if row_i == 0 else "") + marker,
                fontsize=8 if row_i > 0 else 9,
                fontweight="bold" if row_i == 0 else "normal",
                color=PALETTE[region] if row_i == 0 else color,
            )

    fig.suptitle(
        f"Parameter Recovery — All Regions  ({recovery_count}/{total_checks} true values inside 94% HDI)\n"
        "Black dashed = true DGP value  |  ✓ inside HDI  |  ✗ outside HDI\n"
        "Wider posteriors for smaller markets (Australia, Japan) = partial pooling working correctly",
        fontsize=11, fontweight="bold", y=1.01,
    )
    plt.tight_layout()
    plt.savefig(save_path, dpi=120, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Parameter recovery saved: {save_path}")
    print(f"  Recovery rate: {recovery_count}/{total_checks} inside 94% HDI")


# ══════════════════════════════════════════════════════════════════════════════
# 9. POOLING SHRINKAGE VISUALISATION
# ══════════════════════════════════════════════════════════════════════════════

def plot_pooling_shrinkage(idata: az.InferenceData,
                            raw_df: pd.DataFrame,
                            save_path: str = "outputs/fig_pooling_shrinkage.png"):
    """
    Visualise the partial pooling (shrinkage) effect for channel betas and alpha_tv.

    For each parameter, we plot:
      - The per-region posterior mean (coloured dot)
      - The per-region 94% HDI (horizontal error bar)
      - The population posterior mean (vertical dashed line)

    The expected pattern: regions with less data (Australia) have wider credible
    intervals AND their posterior mean is pulled closer to the population mean
    than data-rich regions (Canada, United States). This is partial pooling.

    We also show a separate panel comparing per-region data volume (total spend
    weeks × channels) as a proxy for information content.
    """
    print("\n  Plotting pooling shrinkage...")

    posterior = idata.posterior

    # Parameters to visualise (per-region arrays) + their population mean
    shrinkage_params = [
        ("beta_tv",   "mu_log_beta_tv",   "β TV ($)",          True,  PALETTE["tv"]),
        ("beta_ps",   "mu_log_beta_ps",   "β Paid Search ($)",  True,  PALETTE["paid_search"]),
        ("beta_so",   "mu_log_beta_so",   "β Social ($)",       True,  PALETTE["social"]),
        ("beta_disp", "mu_log_beta_disp", "β Display ($)",      True,  PALETTE["display"]),
        ("alpha_tv",  "mu_alpha_tv",      "α TV",               False, PALETTE["tv"]),
        ("alpha_ps",  "mu_alpha_ps",      "α Paid Search",      False, PALETTE["paid_search"]),
    ]

    n_rows = len(shrinkage_params)
    fig, axes = plt.subplots(n_rows, 1, figsize=(12, 3.5 * n_rows))
    fig.suptitle(
        "Partial Pooling (Shrinkage) — Per-Region vs Population Mean\n"
        "Smaller markets should be pulled toward the population mean\n"
        "Error bars = 94% HDI  |  Dashed line = population posterior mean",
        fontsize=12, fontweight="bold", y=1.01,
    )

    for ax, (param, pop_param, label, is_lognormal, color) in zip(axes, shrinkage_params):

        region_means = []
        region_lo    = []
        region_hi    = []

        for r, region in enumerate(REGIONS):
            samples_r = posterior[param].values[:, :, r].flatten()
            region_means.append(float(samples_r.mean()))
            hdi_r = az.hdi(samples_r, hdi_prob=0.94)
            region_lo.append(float(hdi_r[0]))
            region_hi.append(float(hdi_r[1]))

        # Population mean (for log-normal params, exp of the log-mean)
        pop_samples = posterior[pop_param].values.flatten()
        if is_lognormal:
            pop_mean = float(np.exp(pop_samples.mean()))
        else:
            pop_mean = float(pop_samples.mean())

        # True values per region (for beta; shared for alpha)
        true_vals = []
        for region in REGIONS:
            if "beta" in param:
                ch = param.replace("beta_", "").replace("ps", "paid_search").replace(
                    "so", "social").replace("disp", "display")
                true_vals.append(TRUE_PARAMS["beta"][region][ch])
            else:
                ch = param.replace("alpha_", "").replace("ps", "paid_search").replace(
                    "so", "social").replace("disp", "display")
                true_vals.append(TRUE_PARAMS["adstock"][ch])

        y_pos = np.arange(N_REGIONS)

        # Error bars
        xerr_lo = [m - lo for m, lo in zip(region_means, region_lo)]
        xerr_hi = [hi - m  for m, hi in zip(region_means, region_hi)]

        ax.barh(y_pos, region_means, xerr=[xerr_lo, xerr_hi],
                color=[PALETTE[r] for r in REGIONS], alpha=0.75,
                error_kw={"elinewidth": 1.5, "capsize": 4, "ecolor": "grey"},
                height=0.5, zorder=3)

        # True values as black crosses
        for i, tv in enumerate(true_vals):
            ax.scatter([tv], [y_pos[i]], marker="x", color="black",
                       s=80, zorder=5, linewidths=2)

        # Population mean line
        ax.axvline(pop_mean, color=color, lw=2, linestyle="--",
                   alpha=0.8, label=f"Population mean: {pop_mean:,.0f}")

        ax.set_yticks(y_pos)
        ax.set_yticklabels([REGION_LABELS[r] for r in REGIONS], fontsize=9)
        ax.set_xlabel(label, fontsize=9)
        ax.set_title(f"{label}  (× = true DGP value)", fontsize=10, fontweight="bold")
        ax.legend(fontsize=8, loc="lower right")

        if "beta" in param or "intercept" in param:
            ax.xaxis.set_major_formatter(
                mticker.FuncFormatter(lambda x, _: f"${x/1e3:.0f}K")
            )

    plt.tight_layout()
    plt.savefig(save_path, dpi=130, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Pooling shrinkage plot saved: {save_path}")


# ══════════════════════════════════════════════════════════════════════════════
# 10. POSTERIOR CONTRIBUTION DECOMPOSITION
# ══════════════════════════════════════════════════════════════════════════════

def plot_posterior_contributions(idata: az.InferenceData,
                                  inputs: dict,
                                  save_path: str = "outputs/fig_posterior_contributions_hier.png"):
    """
    Plot posterior mean channel contributions vs. observed revenue for all regions.

    Two panels per region:
      Top:    Stacked area chart — baseline + per-channel contributions.
      Bottom: Posterior predicted revenue (mean + 94% band) vs. observed.

    This is the key business-readable output: how much is each channel contributing
    to revenue, with honest uncertainty (credible bands) around the decomposition.
    """
    print("\n  Plotting posterior contributions...")

    posterior = idata.posterior
    dates     = pd.to_datetime(inputs["dates"])
    T         = inputs["T"]

    fig, axes = plt.subplots(N_REGIONS, 2, figsize=(18, 5 * N_REGIONS), sharex=False)
    fig.suptitle(
        "MapleThread — Posterior Revenue Decomposition (All Regions)\n"
        "Left: stacked contributions  |  Right: posterior predicted vs. observed",
        fontsize=13, fontweight="bold", y=1.005,
    )

    for r, region in enumerate(REGIONS):
        observed = inputs["revenue"][r]
        color    = PALETTE[region]

        # ── Left: stacked contributions ───────────────────────────────────────
        ax_left = axes[r, 0]

        baseline_post = posterior[f"baseline_{region}"].values.reshape(-1, T)
        baseline_mean = baseline_post.mean(axis=0)
        ax_left.fill_between(dates, 0, baseline_mean, alpha=0.5,
                             color=PALETTE["baseline"], label="Baseline")
        bottom = baseline_mean.copy()

        for ch in CHANNELS:
            contrib_post = posterior[f"contrib_{ch}_{region}"].values.reshape(-1, T)
            c_mean = contrib_post.mean(axis=0)
            ax_left.fill_between(dates, bottom, bottom + c_mean, alpha=0.75,
                                 color=PALETTE[ch], label=CHANNEL_LABELS[ch])
            bottom = bottom + c_mean

        ax_left.plot(dates, observed, color="white", lw=0.8, alpha=0.5,
                     label="Observed revenue")
        ax_left.set_title(f"{REGION_LABELS[region]} — Contribution decomposition",
                          fontsize=10, fontweight="bold", color=color)
        ax_left.set_ylabel("Revenue ($)")
        ax_left.yaxis.set_major_formatter(
            mticker.FuncFormatter(lambda x, _: f"${x/1e3:.0f}K"))
        ax_left.legend(loc="upper left", fontsize=7, ncol=3, framealpha=0.7)

        # ── Right: posterior predicted vs. observed ───────────────────────────
        ax_right = axes[r, 1]

        # mu shape: (chains, draws, R, T) — select region r
        mu_post = posterior["mu"].values[:, :, r, :].reshape(-1, T)
        mu_mean = mu_post.mean(axis=0)
        mu_lo   = np.percentile(mu_post,  3, axis=0)
        mu_hi   = np.percentile(mu_post, 97, axis=0)

        ax_right.fill_between(dates, mu_lo, mu_hi, alpha=0.25, color="#4361EE",
                              label="94% posterior band")
        ax_right.plot(dates, mu_mean,  color="#4361EE", lw=1.5, label="Posterior mean")
        ax_right.plot(dates, observed, color="#E63946", lw=1.2, alpha=0.85,
                      label="Observed revenue")
        ax_right.set_title(f"{REGION_LABELS[region]} — Predicted vs. observed",
                           fontsize=10, fontweight="bold", color=color)
        ax_right.set_ylabel("Revenue ($)")
        ax_right.yaxis.set_major_formatter(
            mticker.FuncFormatter(lambda x, _: f"${x/1e3:.0f}K"))
        ax_right.legend(loc="upper left", fontsize=7)

    plt.tight_layout()
    plt.savefig(save_path, dpi=130, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Posterior contributions saved: {save_path}")


# ══════════════════════════════════════════════════════════════════════════════
# 11. ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

def run_phase4(
    sampling_draws:  int   = 1000,
    sampling_tune:   int   = 1000,
    sampling_chains: int   = 4,
    target_accept:   float = 0.92,
    prior_samples:   int   = 300,
    save_idata:      bool  = True,
):
    """
    Full Phase 4 pipeline:
        1. Load all-region data
        2. Build hierarchical model inputs
        3. Build hierarchical PyMC model
        4. Prior predictive check
        5. MCMC sampling
        6. Diagnostics
        7. Parameter recovery (all regions)
        8. Pooling shrinkage visualisation
        9. Posterior contribution decomposition

    Parameters
    ----------
    sampling_draws  : Posterior draws per chain.
    sampling_tune   : Warmup steps per chain (more than Phase 3 due to model complexity).
    sampling_chains : Number of independent MCMC chains.
    target_accept   : NUTS target acceptance rate (higher than Phase 3).
    prior_samples   : Prior predictive samples per region.
    save_idata      : If True, save InferenceData to outputs/idata_hierarchical.nc.

    Quick smoke-test
    ----------------
    To validate the pipeline before a full run:
        run_phase4(sampling_draws=200, sampling_tune=200, sampling_chains=2)
    """
    print("=" * 70)
    print("MapleThread Outdoor Co. — Phase 4: Hierarchical Bayesian MMM")
    print(f"{N_REGIONS} regions  ×  {N_WEEKS} weeks  ×  {len(CHANNELS)} channels")
    print("=" * 70)

    # ── Step 1: Load data ─────────────────────────────────────────────────────
    print("\n[1/8] Loading data...")
    raw_df, gt_df = load_all_data()

    # ── Step 2: Build model inputs ────────────────────────────────────────────
    print("\n[2/8] Building hierarchical model inputs...")
    inputs = build_hierarchical_inputs(raw_df)
    print(f"  Revenue array shape:     {inputs['revenue'].shape}")
    print(f"  Lag matrix shape (TV):   {inputs['lag_matrices']['tv'].shape}")
    for ch in CHANNELS:
        p95s = inputs["p95"][ch]
        print(f"  p95 ({ch:>12s}): " +
              " | ".join(f"{r[:3].upper()} ${v:>8,.0f}" for r, v in
                          zip(REGIONS, p95s)))

    # ── Step 3: Build model ───────────────────────────────────────────────────
    print("\n[3/8] Building hierarchical PyMC model...")
    model = build_hierarchical_model(inputs)
    print(f"  Free parameters:  {len(model.free_RVs)}")
    print(f"  (Phase 3 Canada had ~20 free params; expect ~120+ here)")

    # ── Step 4: Prior predictive check ────────────────────────────────────────
    print("\n[4/8] Prior predictive check...")
    prior_pred = run_prior_predictive(model, inputs, n_samples=prior_samples)

    # ── Step 5: MCMC sampling ─────────────────────────────────────────────────
    print("\n[5/8] MCMC sampling...")
    idata = run_sampling(
        model,
        draws=sampling_draws,
        tune=sampling_tune,
        chains=sampling_chains,
        target_accept=target_accept,
    )

    # ── Step 6: Diagnostics ───────────────────────────────────────────────────
    print("\n[6/8] Diagnostics...")
    summary = run_diagnostics(idata)

    # ── Step 7: Parameter recovery ────────────────────────────────────────────
    print("\n[7/8] Parameter recovery...")
    plot_parameter_recovery(idata)

    # ── Step 8: Pooling shrinkage ─────────────────────────────────────────────
    print("\n[8/8] Pooling shrinkage + posterior contributions...")
    plot_pooling_shrinkage(idata, raw_df)
    plot_posterior_contributions(idata, inputs)

    # ── Save InferenceData ────────────────────────────────────────────────────
    if save_idata:
        idata_path = "outputs/idata_hierarchical.nc"
        idata.to_netcdf(idata_path)
        print(f"\n  ✓ InferenceData saved: {idata_path}")

    print("\n" + "=" * 70)
    print("Phase 4 complete. ✓")
    print("Next step → Phase 5: Posterior Analysis and Channel Attribution")
    print("=" * 70)

    return model, idata, inputs


# ── Run ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    # For a quick smoke-test, pass smaller values:
    #   run_phase4(sampling_draws=200, sampling_tune=200, sampling_chains=2)
    model, idata, inputs = run_phase4(
        sampling_draws=1000,
        sampling_tune=1000,
        sampling_chains=4,
        target_accept=0.92,
        prior_samples=300,
    )