# -*- coding: utf-8 -*-
"""posterior_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uZQo7yaBTqGoJPE4hEG7OzPERsAfesD4
"""

# -*- coding: utf-8 -*-
"""
posterior_analysis.py
=====================
MapleThread Outdoor Co. — MMM Phase 5: Posterior Analysis & Channel Attribution

Loads the saved InferenceData from Phase 4 (idata_hierarchical.nc) and
translates posterior samples into business-readable insights:

  1. Channel contribution decomposition  — probabilistic attribution with
     credible intervals, stacked area charts, and bar summaries per region.
  2. Response curves                     — posterior mean Hill saturation curves
     with 90% credible bands, showing current operating point per channel.
  3. Marginal ROAS                       — analytical derivative of the Hill
     function at current spend levels, with full posterior uncertainty.
  4. ROAS summary table                  — mean + 90% CI per channel per region,
     saved as CSV for downstream use in Phase 6 optimisation.

Sections
--------
  1. Imports & Config
  2. Data Loading (InferenceData + raw spend)
  3. Posterior Utility Functions
  4. Channel Contribution Decomposition
  5. Response Curves
  6. Marginal ROAS
  7. ROAS Summary Table
  8. Entry Point

Run with:
    python posterior_analysis.py

Dependencies:
    outputs/idata_hierarchical.nc  ← saved by Phase 4
    synthetic_raw.csv              ← raw spend data (same directory as Phase 4)

Outputs (saved to outputs/):
    fig_contribution_stacked.png
    fig_contribution_bars.png
    fig_response_curves.png
    fig_roas_uncertainty.png
    roas_summary.csv
"""

from __future__ import annotations

import os
import warnings
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib.lines import Line2D
import arviz as az

warnings.filterwarnings("ignore", category=FutureWarning)

os.makedirs("outputs", exist_ok=True)


# ══════════════════════════════════════════════════════════════════════════════
# 1. CONFIG
# ══════════════════════════════════════════════════════════════════════════════

REGIONS  = ["canada", "united_states", "germany", "japan", "australia"]
CHANNELS = ["tv", "paid_search", "social", "display"]
N_REGIONS = len(REGIONS)
N_WEEKS   = 156
MAX_LAG   = 52
RANDOM_SEED = 42

REGION_LABELS = {
    "canada":        "Canada",
    "united_states": "United States",
    "germany":       "Germany",
    "japan":         "Japan",
    "australia":     "Australia",
}
CHANNEL_LABELS = {
    "tv":          "TV",
    "paid_search": "Paid Search",
    "social":      "Social",
    "display":     "Display",
}

# Ground truth parameters — used for response curve overlays
TRUE_PARAMS = {
    "adstock": {
        "tv": 0.75, "paid_search": 0.20, "social": 0.45, "display": 0.15,
    },
    "hill_k": {
        "tv": 2.5, "paid_search": 1.5, "social": 1.2, "display": 3.0,
    },
    "hill_ec": {
        "tv": 0.4, "paid_search": 0.6, "social": 0.7, "display": 0.3,
    },
    "beta": {
        "canada":        {"tv": 320_000, "paid_search": 260_000, "social": 200_000, "display":  80_000},
        "united_states": {"tv": 240_000, "paid_search": 195_000, "social": 150_000, "display":  60_000},
        "germany":       {"tv": 110_000, "paid_search":  90_000, "social":  70_000, "display":  28_000},
        "japan":         {"tv":  95_000, "paid_search":  78_000, "social":  60_000, "display":  24_000},
        "australia":     {"tv":  35_000, "paid_search":  29_000, "social":  22_000, "display":   9_000},
    },
}

PALETTE = {
    "tv":            "#E63946",
    "paid_search":   "#2A9D8F",
    "social":        "#F4A261",
    "display":       "#457B9D",
    "baseline":      "#A8DADC",
    "canada":        "#E63946",
    "united_states": "#2A9D8F",
    "germany":       "#F4A261",
    "japan":         "#6A4C93",
    "australia":     "#E9C46A",
}

plt.rcParams.update({
    "font.family":       "DejaVu Sans",
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "axes.grid":         True,
    "grid.alpha":        0.3,
    "grid.linestyle":    "--",
    "figure.facecolor":  "#FAFAFA",
    "axes.facecolor":    "#FAFAFA",
})


# ══════════════════════════════════════════════════════════════════════════════
# 2. DATA LOADING
# ══════════════════════════════════════════════════════════════════════════════

def load_idata(path: str = "outputs/idata_hierarchical.nc") -> az.InferenceData:
    """Load the Phase 4 InferenceData from disk."""
    print(f"  Loading InferenceData from {path}...")
    idata = az.from_netcdf(path)
    print(f"  Chains: {idata.posterior.dims['chain']}  "
          f"Draws: {idata.posterior.dims['draw']}")
    return idata


def load_raw_data(path: str = "synthetic_raw.csv") -> pd.DataFrame:
    """Load raw spend and revenue data for all regions."""
    raw_df = pd.read_csv(path, parse_dates=["date"])
    print(f"  Loaded {len(raw_df)} rows from {path}.")
    return raw_df


def build_analysis_inputs(raw_df: pd.DataFrame) -> dict:
    """
    Reconstruct the inputs dictionary needed for response curves and ROAS.

    Replicates the p95 normalisation constants from Phase 4 exactly, using
    the true alpha values. These are fixed constants — not model parameters —
    so they are identical to what the model used during sampling.
    """
    lags = np.arange(MAX_LAG, dtype=float)
    p95  = {ch: [] for ch in CHANNELS}
    revenue_obs  = []
    spend_arrays = {ch: [] for ch in CHANNELS}
    dates = None

    for region in REGIONS:
        df = raw_df[raw_df["region"] == region].reset_index(drop=True)
        revenue_obs.append(df["revenue"].values.astype(float))
        if dates is None:
            dates = df["date"].values

        for ch in CHANNELS:
            spend = df[f"spend_{ch}"].values.astype(float)
            spend_arrays[ch].append(spend)

            # Lag matrix for p95 computation
            T = len(spend)
            lag_mat = np.zeros((T, MAX_LAG), dtype=float)
            for l in range(MAX_LAG):
                lag_mat[l:, l] = spend[:T - l]

            alpha_true = TRUE_PARAMS["adstock"][ch]
            weights    = alpha_true ** lags
            ads_true   = lag_mat @ weights
            p95[ch].append(float(np.percentile(ads_true, 95)))

    return {
        "revenue":      np.stack(revenue_obs),           # (R, T)
        "spend":        {ch: np.stack(spend_arrays[ch])  # (R, T)
                         for ch in CHANNELS},
        "p95":          {ch: np.array(p95[ch])           # (R,)
                         for ch in CHANNELS},
        "dates":        pd.to_datetime(dates),
        "T":            N_WEEKS,
    }


# ══════════════════════════════════════════════════════════════════════════════
# 3. POSTERIOR UTILITY FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

def get_posterior_samples(idata: az.InferenceData) -> dict:
    """
    Extract and flatten posterior samples for all per-region parameters.

    Returns a dict mapping parameter name → np.ndarray of shape (n_draws, R)
    for vector parameters, or (n_draws,) for scalars.

    Flattening chains × draws into a single draw dimension simplifies all
    downstream computation — we treat the joint posterior as a single set
    of samples.
    """
    posterior = idata.posterior
    chains    = posterior.dims["chain"]
    draws     = posterior.dims["draw"]
    D         = chains * draws   # total posterior draws

    samples = {}

    # Per-region parameters: shape (chains, draws, R) → (D, R)
    per_region_params = [
        "alpha_tv", "alpha_ps", "alpha_so", "alpha_disp",
        "k_tv",     "k_ps",     "k_so",     "k_disp",
        "ec_tv",    "ec_ps",    "ec_so",    "ec_disp",
        "beta_tv",  "beta_ps",  "beta_so",  "beta_disp",
        "intercept", "trend_slope",
    ]
    for p in per_region_params:
        if p in posterior:
            arr = posterior[p].values   # (chains, draws, R)
            samples[p] = arr.reshape(D, N_REGIONS)

    # Contribution deterministics: shape (chains, draws, T) — one per region/channel
    for region in REGIONS:
        for ch in CHANNELS:
            key = f"contrib_{ch}_{region}"
            if key in posterior:
                arr = posterior[key].values   # (chains, draws, T)
                samples[key] = arr.reshape(D, N_WEEKS)

        key_bl = f"baseline_{region}"
        if key_bl in posterior:
            samples[key_bl] = posterior[key_bl].values.reshape(D, N_WEEKS)

    # mu: shape (chains, draws, R, T) → (D, R, T)
    if "mu" in posterior:
        samples["mu"] = posterior["mu"].values.reshape(D, N_REGIONS, N_WEEKS)

    print(f"  Extracted {D} posterior draws ({chains} chains × {draws} draws).")
    return samples


def hill_saturation_np(x: np.ndarray, k: float | np.ndarray,
                        ec: float | np.ndarray) -> np.ndarray:
    """Numpy Hill saturation — vectorised over arbitrary shapes."""
    safe_x = np.where(x == 0.0, 1e-10, x)
    return safe_x**k / (safe_x**k + ec**k)


def hill_derivative_np(x: np.ndarray, k: float | np.ndarray,
                        ec: float | np.ndarray) -> np.ndarray:
    """
    Analytical derivative of Hill function w.r.t. x.

        dS/dx = k * ec^k * x^(k-1) / (x^k + ec^k)^2

    Used to compute marginal ROAS at current spend levels.
    """
    safe_x      = np.where(x <= 0, 1e-10, x)
    numerator   = k * (ec**k) * (safe_x ** (k - 1))
    denominator = (safe_x**k + ec**k) ** 2
    return np.where(x <= 0, 0.0, numerator / denominator)


def compute_current_adstock_norm(spend_r: np.ndarray, alpha: float,
                                  p95_val: float) -> np.ndarray:
    """
    Compute geometric adstock for a single region/channel spend series,
    normalised by p95. Pure numpy — used for ROAS computation.
    """
    T       = len(spend_r)
    adstock = np.empty(T, dtype=float)
    adstock[0] = spend_r[0]
    for t in range(1, T):
        adstock[t] = spend_r[t] + alpha * adstock[t - 1]
    return adstock / p95_val if p95_val > 0 else adstock


# ══════════════════════════════════════════════════════════════════════════════
# 4. CHANNEL CONTRIBUTION DECOMPOSITION
# ══════════════════════════════════════════════════════════════════════════════

def plot_contribution_stacked(samples: dict,
                               inputs: dict,
                               save_path: str = "outputs/fig_contribution_stacked.png"):
    """
    Stacked area chart of posterior mean channel contributions over time.

    For each region, the chart decomposes observed revenue into:
        Baseline (trend + seasonality + holidays)
        + TV contribution
        + Paid Search contribution
        + Social contribution
        + Display contribution

    Shading uses posterior means — uncertainty is shown separately in the
    bar chart. The white line is the observed revenue series.

    This is the primary attribution output stakeholders will read first.
    """
    print("\n  Plotting stacked contribution decomposition...")

    dates = inputs["dates"]
    T     = inputs["T"]

    fig, axes = plt.subplots(N_REGIONS, 1, figsize=(16, 5 * N_REGIONS), sharex=False)
    fig.suptitle(
        "MapleThread — Posterior Mean Revenue Decomposition (All Regions)\n"
        "Stacked areas = model attribution  |  White line = observed revenue",
        fontsize=14, fontweight="bold", y=1.005,
    )

    for r, region in enumerate(REGIONS):
        ax = axes[r]

        # Baseline
        baseline_draws = samples[f"baseline_{region}"]   # (D, T)
        baseline_mean  = baseline_draws.mean(axis=0)

        ax.fill_between(dates, 0, baseline_mean, alpha=0.55,
                        color=PALETTE["baseline"], label="Baseline")
        bottom = baseline_mean.copy()

        for ch in CHANNELS:
            contrib_draws = samples[f"contrib_{ch}_{region}"]   # (D, T)
            c_mean = contrib_draws.mean(axis=0)
            ax.fill_between(dates, bottom, bottom + c_mean, alpha=0.78,
                            color=PALETTE[ch], label=CHANNEL_LABELS[ch])
            bottom = bottom + c_mean

        # Observed revenue
        observed = inputs["revenue"][r]
        ax.plot(dates, observed, color="white", lw=1.0, alpha=0.7,
                label="Observed revenue")

        ax.yaxis.set_major_formatter(
            mticker.FuncFormatter(lambda x, _: f"${x/1e3:.0f}K"))
        ax.set_ylabel("Revenue ($)", fontsize=9)
        ax.set_title(REGION_LABELS[region], fontsize=11, fontweight="bold",
                     color=PALETTE[region])
        ax.legend(loc="upper left", fontsize=8, ncol=3, framealpha=0.7)

    axes[-1].set_xlabel("Date", fontsize=9)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Stacked decomposition saved: {save_path}")


def plot_contribution_bars(samples: dict,
                            inputs: dict,
                            save_path: str = "outputs/fig_contribution_bars.png"):
    """
    Bar chart of total channel contribution as % of total revenue, with
    90% credible intervals.

    For each posterior draw d, we compute:
        share_{ch,r,d} = sum_t(contrib_{ch,r,d,t}) / sum_t(revenue_{r,t})

    The posterior distribution of this share gives us probabilistic attribution.

    Layout: one panel per region, grouped bars per channel.
    Error bars are 5th–95th percentile (90% credible interval).
    """
    print("\n  Plotting contribution bar chart...")

    fig, axes = plt.subplots(1, N_REGIONS, figsize=(4 * N_REGIONS, 6), sharey=False)
    fig.suptitle(
        "MapleThread — Channel Revenue Attribution\n"
        "Bar = posterior mean % of total revenue  |  Error bar = 90% credible interval",
        fontsize=13, fontweight="bold",
    )

    summary_rows = []

    for r, region in enumerate(REGIONS):
        ax    = axes[r]
        color = PALETTE[region]

        total_obs_revenue = inputs["revenue"][r].sum()   # scalar

        means = []
        lo90  = []
        hi90  = []
        ch_labels = []

        for ch in CHANNELS:
            contrib_draws = samples[f"contrib_{ch}_{region}"]   # (D, T)
            # Total contribution per draw as % of observed revenue
            share_draws = contrib_draws.sum(axis=1) / total_obs_revenue * 100

            m  = float(share_draws.mean())
            lo = float(np.percentile(share_draws,  5))
            hi = float(np.percentile(share_draws, 95))

            means.append(m)
            lo90.append(m - lo)
            hi90.append(hi - m)
            ch_labels.append(CHANNEL_LABELS[ch])

            summary_rows.append({
                "region":  region,
                "channel": ch,
                "mean_share_pct":  round(m,  2),
                "lo90_share_pct":  round(lo, 2),
                "hi90_share_pct":  round(hi, 2),
            })

        x_pos = np.arange(len(CHANNELS))
        bars  = ax.bar(x_pos, means,
                       color=[PALETTE[ch] for ch in CHANNELS],
                       alpha=0.82, width=0.6, zorder=3)
        ax.errorbar(x_pos, means, yerr=[lo90, hi90],
                    fmt="none", color="black", capsize=5,
                    elinewidth=1.5, capthick=1.5, zorder=4)

        ax.set_xticks(x_pos)
        ax.set_xticklabels(ch_labels, fontsize=9, rotation=20, ha="right")
        ax.set_ylabel("% of total revenue" if r == 0 else "", fontsize=9)
        ax.set_title(REGION_LABELS[region], fontsize=10, fontweight="bold", color=color)
        ax.set_ylim(0, max(means) * 1.5)

        for bar, m in zip(bars, means):
            ax.text(bar.get_x() + bar.get_width() / 2, m + 0.3,
                    f"{m:.1f}%", ha="center", va="bottom", fontsize=7.5,
                    fontweight="bold")

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Contribution bars saved: {save_path}")

    return pd.DataFrame(summary_rows)


# ══════════════════════════════════════════════════════════════════════════════
# 5. RESPONSE CURVES
# ══════════════════════════════════════════════════════════════════════════════

def plot_response_curves(samples: dict,
                          inputs: dict,
                          save_path: str = "outputs/fig_response_curves.png"):
    """
    Posterior Hill saturation curves with 90% credible bands.

    For each channel × region combination, we:
      1. Draw the posterior mean response curve (Hill function at posterior mean k, ec).
      2. Shade the 5th–95th percentile band across all posterior draws.
      3. Mark the current operating point — the mean normalised adstock at
         current spend levels — as a vertical line.
      4. Overlay the true DGP curve (dashed black) for validation.

    The current operating point relative to the curve shape directly answers:
        "Are we in the diminishing returns zone for this channel?"

    If the operating point is to the right of the inflection point (roughly
    where the curve bends from convex to concave), the channel is saturating
    and marginal returns are declining. This motivates the optimisation in
    Phase 6.
    """
    print("\n  Plotting response curves...")

    x_grid = np.linspace(0, 2.0, 300)   # normalised adstock axis

    # Channel → region parameter index mapping
    ch_param = {
        "tv":          ("alpha_tv",   "k_tv",   "ec_tv",   "beta_tv"),
        "paid_search": ("alpha_ps",   "k_ps",   "ec_ps",   "beta_ps"),
        "social":      ("alpha_so",   "k_so",   "ec_so",   "beta_so"),
        "display":     ("alpha_disp", "k_disp", "ec_disp", "beta_disp"),
    }

    fig, axes = plt.subplots(N_REGIONS, len(CHANNELS),
                              figsize=(5 * len(CHANNELS), 4 * N_REGIONS))
    fig.suptitle(
        "MapleThread — Posterior Response Curves (Hill Saturation)\n"
        "Shaded band = 90% credible interval  |  Dashed black = true DGP curve\n"
        "Vertical line = current mean operating point (normalised adstock)",
        fontsize=13, fontweight="bold", y=1.01,
    )

    for r, region in enumerate(REGIONS):
        for c, ch in enumerate(CHANNELS):
            ax = axes[r, c]
            color = PALETTE[ch]

            a_key, k_key, ec_key, b_key = ch_param[ch]

            # Posterior samples for this region's parameters
            alpha_draws = samples[a_key][:, r]   # (D,)
            k_draws     = samples[k_key][:, r]
            ec_draws    = samples[ec_key][:, r]

            # Evaluate Hill curve for every posterior draw across x_grid
            # Shape broadcast: (D, 1) op (1, 300) → (D, 300)
            k_2d  = k_draws[:, None]
            ec_2d = ec_draws[:, None]
            x_2d  = x_grid[None, :]

            curves = hill_saturation_np(x_2d, k_2d, ec_2d)   # (D, 300)

            curve_mean = curves.mean(axis=0)
            curve_lo   = np.percentile(curves,  5, axis=0)
            curve_hi   = np.percentile(curves, 95, axis=0)

            ax.fill_between(x_grid, curve_lo, curve_hi,
                            alpha=0.25, color=color)
            ax.plot(x_grid, curve_mean, color=color, lw=2.0,
                    label="Posterior mean")

            # True DGP curve
            k_true  = TRUE_PARAMS["hill_k"][ch]
            ec_true = TRUE_PARAMS["hill_ec"][ch]
            true_curve = hill_saturation_np(x_grid, k_true, ec_true)
            ax.plot(x_grid, true_curve, color="black", lw=1.5,
                    linestyle="--", alpha=0.7, label="True DGP")

            # Current operating point: mean adstock_norm at posterior mean alpha
            alpha_mean = float(alpha_draws.mean())
            p95_val    = inputs["p95"][ch][r]
            spend_r    = inputs["spend"][ch][r]
            adstock_norm = compute_current_adstock_norm(spend_r, alpha_mean, p95_val)
            current_x    = float(adstock_norm.mean())

            ax.axvline(current_x, color=color, lw=1.8, linestyle=":",
                       alpha=0.85, label=f"Current x̄={current_x:.2f}")

            # Half-saturation reference lines
            ax.axhline(0.5, color="grey", lw=0.8, linestyle="--", alpha=0.5)

            if r == 0:
                ax.set_title(CHANNEL_LABELS[ch], fontsize=11,
                             fontweight="bold", color=color)
            if c == 0:
                ax.set_ylabel(REGION_LABELS[region], fontsize=9,
                              fontweight="bold")

            ax.set_xlim(0, 2.0)
            ax.set_ylim(0, 1.05)
            ax.set_xlabel("Normalised adstock", fontsize=8)
            ax.legend(fontsize=6.5, loc="lower right")

    plt.tight_layout()
    plt.savefig(save_path, dpi=130, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Response curves saved: {save_path}")


# ══════════════════════════════════════════════════════════════════════════════
# 6. MARGINAL ROAS
# ══════════════════════════════════════════════════════════════════════════════

def compute_marginal_roas(samples: dict, inputs: dict) -> pd.DataFrame:
    """
    Compute marginal ROAS for each channel × region at current spend levels.

    Marginal ROAS answers: "If I spend $1 more on this channel right now,
    how much additional revenue do I expect?"

    Derivation
    ----------
    Revenue contribution from channel c in region r:

        revenue_c = beta_c × Hill(adstock_norm_c ; k_c, ec_c)

    The marginal revenue per unit of *raw spend* is obtained via the chain rule:

        dRevenue/dSpend = beta_c × (dHill/dx) × (dx_norm/dSpend)

    where:
        dHill/dx     = k * ec^k * x^(k-1) / (x^k + ec^k)^2   [Hill derivative]
        dx_norm/dSpend ≈ 1 / p95_c                             [normalisation chain]
        x            = current normalised adstock

    The result is dollars of revenue per dollar of additional spend — marginal ROAS.

    Note: This is the *instantaneous* marginal ROAS at the current operating
    point, not the average ROAS. It will always be lower than average ROAS
    for channels operating in the diminishing returns region.

    We compute this for every posterior draw to get a full posterior
    distribution of marginal ROAS, then summarise with mean and 90% CI.
    """
    print("\n  Computing marginal ROAS...")

    ch_param = {
        "tv":          ("alpha_tv",   "k_tv",   "ec_tv",   "beta_tv"),
        "paid_search": ("alpha_ps",   "k_ps",   "ec_ps",   "beta_ps"),
        "social":      ("alpha_so",   "k_so",   "ec_so",   "beta_so"),
        "display":     ("alpha_disp", "k_disp", "ec_disp", "beta_disp"),
    }

    rows = []

    for r, region in enumerate(REGIONS):
        for ch in CHANNELS:
            a_key, k_key, ec_key, b_key = ch_param[ch]

            alpha_draws = samples[a_key][:, r]   # (D,)
            k_draws     = samples[k_key][:, r]
            ec_draws    = samples[ec_key][:, r]
            beta_draws  = samples[b_key][:, r]

            p95_val = inputs["p95"][ch][r]
            spend_r = inputs["spend"][ch][r]

            # For each draw, compute current adstock_norm using that draw's alpha
            # then evaluate the Hill derivative at that point.
            # Vectorising over draws is memory-intensive for large D; we batch.
            D = len(alpha_draws)
            marginal_roas_draws = np.empty(D, dtype=float)

            for d in range(D):
                ads_norm = compute_current_adstock_norm(
                    spend_r, float(alpha_draws[d]), p95_val
                )
                # Use mean normalised adstock as the "current operating point"
                x_current = float(ads_norm.mean())

                # Hill derivative at current x
                dhill_dx = hill_derivative_np(
                    np.array([x_current]),
                    k_draws[d],
                    ec_draws[d],
                )[0]

                # Marginal ROAS = beta × dHill/dx × (1/p95)
                marginal_roas_draws[d] = float(
                    beta_draws[d] * dhill_dx * (1.0 / p95_val)
                )

            mean_roas = float(marginal_roas_draws.mean())
            lo90      = float(np.percentile(marginal_roas_draws,  5))
            hi90      = float(np.percentile(marginal_roas_draws, 95))
            median    = float(np.median(marginal_roas_draws))

            rows.append({
                "region":          region,
                "channel":         ch,
                "marginal_roas_mean":   round(mean_roas, 3),
                "marginal_roas_median": round(median,    3),
                "marginal_roas_lo90":   round(lo90,      3),
                "marginal_roas_hi90":   round(hi90,      3),
            })

            print(f"    {REGION_LABELS[region]:>15s} | {CHANNEL_LABELS[ch]:>12s}: "
                  f"mROAS = {mean_roas:.2f}  "
                  f"[{lo90:.2f}, {hi90:.2f}] 90% CI")

    return pd.DataFrame(rows)


def plot_roas_uncertainty(roas_df: pd.DataFrame,
                           save_path: str = "outputs/fig_roas_uncertainty.png"):
    """
    Dot-and-whisker plot of marginal ROAS with 90% credible intervals.

    Layout: one panel per region, channels on y-axis, marginal ROAS on x-axis.
    This makes it easy to rank channels within a region and compare uncertainty.

    A marginal ROAS > 1 means the channel is generating more revenue than its
    marginal spend cost. A marginal ROAS < 1 suggests the channel is oversaturated
    at current spend levels and budget should be reallocated.
    """
    print("\n  Plotting ROAS uncertainty...")

    fig, axes = plt.subplots(1, N_REGIONS, figsize=(4 * N_REGIONS, 5), sharey=True)
    fig.suptitle(
        "MapleThread — Marginal ROAS at Current Spend Levels\n"
        "Dot = posterior mean  |  Whisker = 90% credible interval\n"
        "mROAS > 1: generating more revenue than marginal cost  |  "
        "mROAS < 1: channel oversaturated",
        fontsize=12, fontweight="bold",
    )

    for r, region in enumerate(REGIONS):
        ax    = axes[r]
        color = PALETTE[region]
        sub   = roas_df[roas_df["region"] == region].reset_index(drop=True)

        y_pos = np.arange(len(CHANNELS))

        for i, row in sub.iterrows():
            ch    = row["channel"]
            mean  = row["marginal_roas_mean"]
            lo90  = row["marginal_roas_lo90"]
            hi90  = row["marginal_roas_hi90"]

            ax.plot([lo90, hi90], [i, i], color=PALETTE[ch], lw=2.5, alpha=0.7)
            ax.scatter([mean], [i], color=PALETTE[ch], s=80, zorder=5)
            ax.text(hi90 + 0.02, i, f"{mean:.2f}", va="center",
                    fontsize=8, color=PALETTE[ch], fontweight="bold")

        ax.axvline(1.0, color="black", lw=1.2, linestyle="--",
                   alpha=0.6, label="mROAS = 1")
        ax.set_yticks(y_pos)
        ax.set_yticklabels([CHANNEL_LABELS[ch] for ch in CHANNELS], fontsize=9)
        ax.set_xlabel("Marginal ROAS", fontsize=9)
        ax.set_title(REGION_LABELS[region], fontsize=10,
                     fontweight="bold", color=color)
        ax.set_xlim(left=0)

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ ROAS uncertainty plot saved: {save_path}")


# ══════════════════════════════════════════════════════════════════════════════
# 7. ROAS SUMMARY TABLE
# ══════════════════════════════════════════════════════════════════════════════

def build_roas_summary_table(roas_df: pd.DataFrame,
                              contrib_df: pd.DataFrame,
                              save_path: str = "outputs/roas_summary.csv") -> pd.DataFrame:
    """
    Merge marginal ROAS and contribution share into a single summary table.

    Columns
    -------
    region, channel,
    mean_share_pct, lo90_share_pct, hi90_share_pct   ← contribution as % revenue
    marginal_roas_mean, marginal_roas_lo90, hi90      ← marginal ROAS

    This table is the primary input to Phase 6 budget optimisation. Channels
    with high marginal ROAS and low contribution share are underfunded.
    Channels with low marginal ROAS and high contribution share are saturated.
    """
    merged = roas_df.merge(contrib_df, on=["region", "channel"], how="left")

    # Reorder columns for readability
    col_order = [
        "region", "channel",
        "mean_share_pct", "lo90_share_pct", "hi90_share_pct",
        "marginal_roas_mean", "marginal_roas_median",
        "marginal_roas_lo90", "marginal_roas_hi90",
    ]
    merged = merged[col_order]

    merged.to_csv(save_path, index=False)
    print(f"\n  ✓ ROAS summary table saved: {save_path}")

    # Print a formatted view
    print("\n  ── ROAS Summary Table ──")
    print(f"  {'Region':<15} {'Channel':<12} {'Share%':>7} "
          f"{'mROAS':>7} {'90% CI':>15}")
    print("  " + "─" * 62)
    for _, row in merged.iterrows():
        print(f"  {REGION_LABELS[row['region']]:<15} "
              f"{CHANNEL_LABELS[row['channel']]:<12} "
              f"{row['mean_share_pct']:>6.1f}%  "
              f"{row['marginal_roas_mean']:>6.2f}   "
              f"[{row['marginal_roas_lo90']:.2f}, {row['marginal_roas_hi90']:.2f}]")

    return merged


# ══════════════════════════════════════════════════════════════════════════════
# 8. ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

def run_phase5(
    idata_path: str = "outputs/idata_hierarchical.nc",
    raw_data_path: str = "synthetic_raw.csv",
):
    """
    Full Phase 5 pipeline:
        1. Load InferenceData and raw spend data
        2. Extract and flatten posterior samples
        3. Channel contribution decomposition (stacked area + bar charts)
        4. Response curves (Hill saturation with credible bands)
        5. Marginal ROAS computation and visualisation
        6. ROAS summary table (CSV output for Phase 6)

    Parameters
    ----------
    idata_path    : Path to InferenceData saved by Phase 4.
    raw_data_path : Path to synthetic_raw.csv (raw spend + revenue).
    """
    print("=" * 70)
    print("MapleThread Outdoor Co. — Phase 5: Posterior Analysis & Attribution")
    print(f"{N_REGIONS} regions  ×  {N_WEEKS} weeks  ×  {len(CHANNELS)} channels")
    print("=" * 70)

    # ── Step 1: Load data ─────────────────────────────────────────────────────
    print("\n[1/6] Loading data...")
    idata  = load_idata(idata_path)
    raw_df = load_raw_data(raw_data_path)
    inputs = build_analysis_inputs(raw_df)
    print(f"  Revenue array shape: {inputs['revenue'].shape}")

    # ── Step 2: Extract posterior samples ─────────────────────────────────────
    print("\n[2/6] Extracting posterior samples...")
    samples = get_posterior_samples(idata)

    # ── Step 3: Contribution decomposition ────────────────────────────────────
    print("\n[3/6] Channel contribution decomposition...")
    plot_contribution_stacked(samples, inputs)
    contrib_df = plot_contribution_bars(samples, inputs)

    # ── Step 4: Response curves ───────────────────────────────────────────────
    print("\n[4/6] Response curves...")
    plot_response_curves(samples, inputs)

    # ── Step 5: Marginal ROAS ─────────────────────────────────────────────────
    print("\n[5/6] Marginal ROAS...")
    roas_df = compute_marginal_roas(samples, inputs)
    plot_roas_uncertainty(roas_df)

    # ── Step 6: Summary table ─────────────────────────────────────────────────
    print("\n[6/6] Building ROAS summary table...")
    summary_df = build_roas_summary_table(roas_df, contrib_df)

    print("\n" + "=" * 70)
    print("Phase 5 complete. ✓")
    print("Outputs:")
    print("  outputs/fig_contribution_stacked.png")
    print("  outputs/fig_contribution_bars.png")
    print("  outputs/fig_response_curves.png")
    print("  outputs/fig_roas_uncertainty.png")
    print("  outputs/roas_summary.csv  ← input for Phase 6 optimisation")
    print("Next step → Phase 6: Budget Optimisation")
    print("=" * 70)

    return samples, inputs, roas_df, summary_df


# ── Run ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    samples, inputs, roas_df, summary_df = run_phase5(
        idata_path="idata_hierarchical.nc",
        raw_data_path="synthetic_raw.csv",
    )