# -*- coding: utf-8 -*-
"""single_region_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBLuR6fPHmDG8cmxn4owSIQU0CQIHLg_
"""

# -*- coding: utf-8 -*-
"""
model_single_region.py
======================
MapleThread Outdoor Co. — MMM Phase 3: Bayesian Model (Single Region)

Region: Canada
Model structure:
    Revenue[t] = Baseline[t] + Σ_c (β_c × Hill(Adstock(spend_c[t]))) + ε[t]

where:
    Baseline[t]  = intercept + trend_slope × t
                   + Σ_{f=1}^{2} [A_f sin(2πft/52) + B_f cos(2πft/52)]
                   + holiday_multiplier[t]

Sections
--------
  1. Imports & Config
  2. Data Loading & Preprocessing
  3. Media Transformations (adstock normalisation, pytensor-compatible adstock)
  4. Model Definition
  5. Prior Predictive Check
  6. MCMC Sampling & Diagnostics
  7. Parameter Recovery
  8. Entry Point

Run with:
    python model_single_region.py

Outputs (saved to outputs/):
    fig_prior_predictive.png
    fig_trace.png
    fig_parameter_recovery.png
    fig_posterior_contributions.png
    idata_canada.nc             ← ArviZ InferenceData (full posterior)
"""

from __future__ import annotations

import os
import warnings
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import arviz as az
import pymc as pm
import pytensor.tensor as pt

warnings.filterwarnings("ignore", category=UserWarning, module="pymc")
warnings.filterwarnings("ignore", category=FutureWarning)

os.makedirs("outputs", exist_ok=True)
os.makedirs("data",    exist_ok=True)

# ══════════════════════════════════════════════════════════════════════════════
# 1. CONFIG  — mirrors data_generation.py ground truth
# ══════════════════════════════════════════════════════════════════════════════

REGION   = "canada"
CHANNELS = ["tv", "paid_search", "social", "display"]
N_WEEKS  = 156
RANDOM_SEED = 42

# ── Ground truth (recovery targets) ──────────────────────────────────────────
TRUE_PARAMS = {
    "intercept":   620_000,
    "trend_slope": 950,
    # Fourier amplitudes [sin1, cos1, sin2, cos2]
    "seasonality_amplitudes": [-25_000, 40_000, 18_000, -8_000],
    "noise_std":   28_000,
    "adstock": {
        "tv":          0.75,
        "paid_search": 0.20,
        "social":      0.45,
        "display":     0.15,
    },
    "hill_k": {
        "tv":          2.5,
        "paid_search": 1.5,
        "social":      1.2,
        "display":     3.0,
    },
    "hill_ec": {
        "tv":          0.4,
        "paid_search": 0.6,
        "social":      0.7,
        "display":     0.3,
    },
    "beta": {
        "tv":          320_000,
        "paid_search": 260_000,
        "social":      200_000,
        "display":      80_000,
    },
}

HOLIDAY_WEEKS = [13, 14, 26, 34, 35, 36, 47, 48, 49, 50, 51, 52]

# ── Plot style ────────────────────────────────────────────────────────────────
PALETTE = {
    "tv":          "#E63946",
    "paid_search": "#2A9D8F",
    "social":      "#F4A261",
    "display":     "#457B9D",
    "baseline":    "#A8DADC",
    "revenue":     "#1D3557",
}
CHANNEL_LABELS = {
    "tv":          "TV",
    "paid_search": "Paid Search",
    "social":      "Social",
    "display":     "Display",
}

plt.rcParams.update({
    "font.family":       "DejaVu Sans",
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "axes.grid":         True,
    "grid.alpha":        0.3,
    "grid.linestyle":    "--",
    "figure.facecolor":  "#FAFAFA",
    "axes.facecolor":    "#FAFAFA",
})


# ══════════════════════════════════════════════════════════════════════════════
# 2. DATA LOADING & PREPROCESSING
# ══════════════════════════════════════════════════════════════════════════════

def load_canada_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Load synthetic_raw.csv and ground_truth.csv, filter to Canada.

    Returns
    -------
    raw_df : pd.DataFrame
        156-row frame with spend columns and observed revenue.
    gt_df : pd.DataFrame
        156-row frame with true baseline, contributions, adstock, saturated.
    """
    raw_df = pd.read_csv("synthetic_raw.csv", parse_dates=["date"])
    gt_df  = pd.read_csv("ground_truth.csv",  parse_dates=["date"])

    raw_df = raw_df[raw_df["region"] == REGION].reset_index(drop=True)
    gt_df  = gt_df[gt_df["region"]  == REGION].reset_index(drop=True)

    print(f"  Loaded {len(raw_df)} weeks of Canada data.")
    print(f"  Revenue range: ${raw_df['revenue'].min():,.0f} – ${raw_df['revenue'].max():,.0f}")
    return raw_df, gt_df


def build_model_inputs(raw_df: pd.DataFrame) -> dict:
    """
    Construct all numpy arrays the PyMC model needs.

    Preprocessing steps
    -------------------
    1. Time index t = 0, 1, …, 155 (standardised to [0, 1] for trend prior).
    2. Fourier features for annual and semi-annual cycles (4 columns).
    3. Holiday indicator matrix (T × 12) — one column per holiday week.
    4. Geometric adstock per channel, normalised by p95 (fixed constant,
       computed on observed data — this is what the model will see).

    Notes on adstock normalisation
    -------------------------------
    The DGP normalises each channel's adstock by its 95th percentile before
    applying Hill. We replicate this exactly: compute p95 on the observed
    spend series, store it as a fixed constant, and use it in both the
    preprocessing and the PyTensor adstock node inside the model.
    """
    T = len(raw_df)
    t = np.arange(T, dtype=float)

    # ── Trend (standardised for numerical stability) ──────────────────────────
    # The model estimates trend_slope in units of revenue-per-standardised-week.
    # We undo the standardisation when comparing to true_slope in recovery plots.
    t_std = t / (T - 1)  # maps [0, 155] → [0, 1]

    # ── Fourier seasonality features ─────────────────────────────────────────
    # Two harmonics (annual + semi-annual): sin1, cos1, sin2, cos2
    fourier = np.column_stack([
        np.sin(2 * np.pi * 1 * t / 52),
        np.cos(2 * np.pi * 1 * t / 52),
        np.sin(2 * np.pi * 2 * t / 52),
        np.cos(2 * np.pi * 2 * t / 52),
    ])  # shape (T, 4)

    # ── Holiday indicator matrix ──────────────────────────────────────────────
    week_of_year = raw_df["date"].dt.isocalendar().week.values.astype(int)
    holiday_matrix = np.zeros((T, len(HOLIDAY_WEEKS)), dtype=float)
    for j, hw in enumerate(HOLIDAY_WEEKS):
        holiday_matrix[:, j] = (week_of_year == hw).astype(float)
    # holiday_matrix[t, j] = 1 if week t falls in holiday j, else 0

    # ── Adstock preprocessing (numpy, pre-model) ──────────────────────────────
    # We pre-apply geometric adstock at the TRUE alpha values to generate the
    # normalisation constants (p95). During model fitting, adstock is recomputed
    # inside the PyMC model using PyTensor scan — the p95 constants are then
    # used to normalise that symbolic adstock.
    #
    # This is equivalent to what the DGP does and ensures the Hill ec parameter
    # remains in a [0,1]-interpretable range during sampling.
    # Adstock: precomputed lag matrices (vectorised, no scan)
    #
    # Instead of computing adstock inside the model with a recursive loop
    # (pytensor.scan), we precompute a lagged spend matrix of shape (T, MAX_LAG)
    # where column l contains spend shifted l periods into the past (zero-padded).
    #
    # Inside the model, adstock is then a single matrix-vector product:
    #
    #     adstock[t] = sum_{l=0}^{L-1} alpha^l * spend[t-l]
    #                = lag_matrix[t] . (alpha^0, alpha^1, ..., alpha^{L-1})
    #
    # This is mathematically equivalent to geometric adstock (truncation error
    # is alpha^L, which is negligible for L=52 even at alpha=0.75: ~3e-7).
    #
    # The lag matrix is a fixed numpy constant — the only symbolic operation
    # inside PyMC is the dot product with the weight vector, which PyTensor
    # vectorises efficiently and GPUs handle natively. No scan, no loop.
    MAX_LAG = 52
    lags = np.arange(MAX_LAG, dtype=float)   # [0, 1, 2, ..., 51]

    raw_spend     = {}
    lag_matrices  = {}
    p95_constants = {}

    for ch in CHANNELS:
        spend = raw_df[f"spend_{ch}"].values.astype(float)
        raw_spend[ch] = spend

        # Build (T, MAX_LAG) lag matrix: column l = spend shifted l steps back
        lag_mat = np.zeros((T, MAX_LAG), dtype=float)
        for l in range(MAX_LAG):
            lag_mat[l:, l] = spend[:T - l]
        lag_matrices[ch] = lag_mat

        # p95 normalisation constant: computed at true alpha for scale reference.
        # The model sees adstock / p95, keeping Hill ec interpretable on [0, 1].
        alpha_true = TRUE_PARAMS["adstock"][ch]
        weights    = alpha_true ** lags
        ads_true   = lag_mat @ weights
        p95_constants[ch] = float(np.percentile(ads_true, 95))

    return {
        "T":              T,
        "t":              t,
        "t_std":          t_std,
        "fourier":        fourier,
        "holiday_matrix": holiday_matrix,
        "week_of_year":   week_of_year,
        "revenue":        raw_df["revenue"].values.astype(float),
        "raw_spend":      raw_spend,
        "lag_matrices":   lag_matrices,
        "lags":           lags,
        "p95":            p95_constants,
        "dates":          raw_df["date"].values,
    }


def _numpy_geometric_adstock(spend: np.ndarray, alpha: float) -> np.ndarray:
    """Pure numpy geometric adstock — used only for preprocessing."""
    ads = np.empty_like(spend, dtype=float)
    ads[0] = spend[0]
    for t in range(1, len(spend)):
        ads[t] = spend[t] + alpha * ads[t - 1]
    return ads


# ══════════════════════════════════════════════════════════════════════════════
# 3. PYTENSOR MEDIA TRANSFORMS (vectorised, no scan)
# ══════════════════════════════════════════════════════════════════════════════

def pytensor_geometric_adstock_vec(lag_matrix: pt.TensorVariable,
                                    lags: np.ndarray,
                                    alpha: pt.TensorVariable) -> pt.TensorVariable:
    """
    Vectorised geometric adstock via lag-matrix dot product — no scan required.

    adstock[t] = sum_{l=0}^{L-1} alpha^l * spend[t-l]
               = lag_matrix[t] . weight_vector

    where weight_vector[l] = alpha^l, shape (MAX_LAG,).

    lag_matrix is a fixed (T, MAX_LAG) numpy array precomputed in
    build_model_inputs. Inside PyMC, only the dot product is symbolic,
    making this ~100x faster than pytensor.scan for 156 time steps.

    Parameters
    ----------
    lag_matrix : pt.TensorVariable, shape (T, MAX_LAG)
        Precomputed lagged spend matrix (fixed data constant).
    lags : np.ndarray, shape (MAX_LAG,)
        Integer lag indices [0, 1, ..., MAX_LAG-1].
    alpha : pt.TensorVariable, scalar
        Symbolic decay rate in [0, 1).

    Returns
    -------
    pt.TensorVariable, shape (T,)
        Adstock time series.
    """
    weights = alpha ** pt.as_tensor_variable(lags)   # (MAX_LAG,) symbolic
    return pt.dot(lag_matrix, weights)                # (T,)


def pytensor_hill(x: pt.TensorVariable,
                  k: pt.TensorVariable,
                  ec: pt.TensorVariable) -> pt.TensorVariable:
    """
    Hill saturation: S(x) = x^k / (x^k + ec^k)

    Numerically safe: replaces x=0 with a small epsilon so gradients are
    well-defined. The result is still effectively 0 at x≈0.
    """
    safe_x = pt.switch(pt.eq(x, 0.0), 1e-10, x)
    return safe_x**k / (safe_x**k + ec**k)


# ══════════════════════════════════════════════════════════════════════════════
# 4. MODEL DEFINITION
# ══════════════════════════════════════════════════════════════════════════════

def build_model(inputs: dict) -> pm.Model:
    """
    Build the single-region Bayesian MMM for Canada.

    Model structure
    ---------------
    Revenue[t] = Baseline[t]
               + Σ_c β_c × Hill(Adstock(spend_c[t]) / p95_c ; k_c, ec_c)
               + ε[t]

    where ε[t] ~ Normal(0, σ²)

    Baseline[t] = intercept
                + trend_slope × t_std[t]
                + A1×sin1[t] + B1×cos1[t] + A2×sin2[t] + B2×cos2[t]
                + Σ_j δ_j × holiday_matrix[t, j]

    Prior justifications (each commented inline)
    --------------------------------------------
    All revenue quantities are scaled to Canada's range:
        mean ~$780K, std ~$100K, min ~$540K, max ~$1.15M
    """
    T              = inputs["T"]
    t_std          = pt.as_tensor_variable(inputs["t_std"].astype("float64"))
    fourier        = pt.as_tensor_variable(inputs["fourier"].astype("float64"))
    holiday_matrix = pt.as_tensor_variable(inputs["holiday_matrix"].astype("float64"))
    revenue_obs    = inputs["revenue"].astype("float64")

    with pm.Model() as model:

        # ── PRIORS: Baseline ─────────────────────────────────────────────────

        # Intercept: Canada's weekly baseline revenue is ~$620K with growth.
        # HalfNormal(1_000_000) puts 99% of prior mass below ~$2.3M — diffuse
        # but bounded positive (revenue can't be negative).
        intercept = pm.HalfNormal("intercept", sigma=1_000_000)

        # Trend slope: revenue grows ~$950/week at true params. Over 155 weeks
        # (t_std range = 1), trend contribution is ~$147K total.
        # HalfNormal(300_000) is diffuse but enforces a positive trend assumption
        # (outdoor brand growing over 3 years is reasonable).
        trend_slope = pm.HalfNormal("trend_slope", sigma=300_000)

        # Fourier coefficients: each amplitude is ~[-25K, +40K] at ground truth.
        # Normal(0, 50_000) covers this range well while allowing both signs.
        # The prior is symmetric — we have no directional prior on seasonality.
        fourier_coefs = pm.Normal("fourier_coefs", mu=0, sigma=50_000, shape=4)

        # Holiday deltas: revenue lift/drag around key retail weeks.
        # True multipliers range from 0.90 (summer trough) to 1.75 (Black Friday).
        # We model as δ_j ~ Normal(0, 0.3) centred at zero (no lift assumed a priori).
        # The final holiday effect is baseline × (1 + Σ δ_j × I[holiday j]).
        holiday_deltas = pm.Normal("holiday_deltas", mu=0, sigma=0.3,
                                   shape=len(HOLIDAY_WEEKS))

        # ── PRIORS: Noise ────────────────────────────────────────────────────

        # Revenue noise: true DGP adds Gaussian noise with std ~$28K, plus
        # unmodelled variation. HalfNormal(100_000) is diffuse enough to let
        # the data speak, while being bounded positive.
        sigma = pm.HalfNormal("sigma", sigma=100_000)

        # ── PRIORS: Adstock decay rates ───────────────────────────────────────

        # Alpha lives in [0,1) — Beta distribution is the natural choice.
        # Priors informed by channel type:
        #   TV:          long carryover → Beta(8, 3)  → mean=0.73, mode≈0.78
        #   Paid Search: short          → Beta(2, 8)  → mean=0.20, mode≈0.13
        #   Social:      medium         → Beta(5, 6)  → mean=0.45, mode≈0.44
        #   Display:     very short     → Beta(2, 10) → mean=0.17, mode≈0.11
        alpha_tv   = pm.Beta("alpha_tv",   alpha=8,  beta=3)
        alpha_ps   = pm.Beta("alpha_ps",   alpha=2,  beta=8)
        alpha_so   = pm.Beta("alpha_so",   alpha=5,  beta=6)
        alpha_disp = pm.Beta("alpha_disp", alpha=2,  beta=10)

        alphas = {"tv": alpha_tv, "paid_search": alpha_ps,
                  "social": alpha_so, "display": alpha_disp}

        # ── PRIORS: Hill saturation (k and ec) ───────────────────────────────

        # k (Hill slope): must be > 0. HalfNormal(2) puts most mass in (0, 4),
        # covering the full range of plausible curvatures (1=hyperbolic, 3=sharp S).
        # We use slightly different scales per channel based on our DGP knowledge,
        # but keep them broad enough to not over-constrain the model.
        k_tv   = pm.HalfNormal("k_tv",   sigma=3.0)
        k_ps   = pm.HalfNormal("k_ps",   sigma=2.5)
        k_so   = pm.HalfNormal("k_so",   sigma=2.0)
        k_disp = pm.HalfNormal("k_disp", sigma=3.5)

        ks = {"tv": k_tv, "paid_search": k_ps,
              "social": k_so, "display": k_disp}

        # ec (half-saturation): must be > 0. Since adstock is normalised to [0,~1]
        # by p95, ec is interpretable on a [0,1] scale.
        # Beta(4, 6) → mean≈0.4, Beta(6, 4) → mean≈0.6 — channel-informed priors
        # that keep ec in a sensible [0,1] range.
        ec_tv   = pm.Beta("ec_tv",   alpha=4, beta=6)   # mean=0.40 → saturates fast
        ec_ps   = pm.Beta("ec_ps",   alpha=6, beta=4)   # mean=0.60 → moderate
        ec_so   = pm.Beta("ec_so",   alpha=7, beta=3)   # mean=0.70 → room to grow
        ec_disp = pm.Beta("ec_disp", alpha=3, beta=7)   # mean=0.30 → very fast sat

        ecs = {"tv": ec_tv, "paid_search": ec_ps,
               "social": ec_so, "display": ec_disp}

        # ── PRIORS: Channel coefficients (β) ─────────────────────────────────

        # β_c is the maximum revenue contribution of channel c (when saturated = 1).
        # Canada's true values: TV=$320K, Search=$260K, Social=$200K, Display=$80K.
        # HalfNormal(400_000) puts 99% of mass below ~$925K — diffuse but positive.
        # Positive constraint is correct: more spend cannot reduce expected revenue.
        beta_tv   = pm.HalfNormal("beta_tv",   sigma=400_000)
        beta_ps   = pm.HalfNormal("beta_ps",   sigma=400_000)
        beta_so   = pm.HalfNormal("beta_so",   sigma=400_000)
        beta_disp = pm.HalfNormal("beta_disp", sigma=150_000)

        betas = {"tv": beta_tv, "paid_search": beta_ps,
                 "social": beta_so, "display": beta_disp}

        # ── DETERMINISTIC: Baseline ───────────────────────────────────────────

        trend      = intercept + trend_slope * t_std
        seasonality = pm.math.dot(fourier, fourier_coefs)

        # Holiday effect: additive lift/drag expressed as revenue amount.
        # holiday_matrix is (T, 12); holiday_deltas is (12,).
        # dot product gives (T,) — the total holiday revenue delta each week.
        holiday_effect = pm.math.dot(holiday_matrix, holiday_deltas) * intercept

        baseline = pm.Deterministic("baseline", trend + seasonality + holiday_effect)

        # ── DETERMINISTIC: Media contributions ───────────────────────────────

        channel_contributions = []
        for ch in CHANNELS:
            # Fixed lag matrix and lags passed in as data constants
            lag_mat = pt.as_tensor_variable(
                inputs["lag_matrices"][ch].astype("float64")
            )
            p95_val = inputs["p95"][ch]   # fixed scalar from preprocessing

            # Vectorised adstock: single dot product, no scan loop
            adstock_ch = pytensor_geometric_adstock_vec(
                lag_mat, inputs["lags"], alphas[ch]
            )

            # Normalise by fixed p95 constant (same as DGP)
            adstock_norm_ch = adstock_ch / p95_val

            # Hill saturation
            saturated_ch = pytensor_hill(adstock_norm_ch, ks[ch], ecs[ch])

            # Channel revenue contribution
            contrib_ch = pm.Deterministic(
                f"contrib_{ch}", betas[ch] * saturated_ch
            )
            channel_contributions.append(contrib_ch)

        total_media = sum(channel_contributions)

        # ── DETERMINISTIC: Predicted revenue ────────────────────────────────
        mu = pm.Deterministic("mu", baseline + total_media)

        # ── LIKELIHOOD ───────────────────────────────────────────────────────
        revenue = pm.Normal("revenue", mu=mu, sigma=sigma, observed=revenue_obs)

    return model


# ══════════════════════════════════════════════════════════════════════════════
# 5. PRIOR PREDICTIVE CHECK
# ══════════════════════════════════════════════════════════════════════════════

def run_prior_predictive(model: pm.Model,
                          inputs: dict,
                          n_samples: int = 500,
                          save_path: str = "outputs/fig_prior_predictive.png"):
    """
    Sample from the prior only and plot implied revenue distribution.

    The goal: verify the prior allows a plausible range of revenues without
    permitting absurdities (e.g. negative billions or positive trillions).
    Canada's observed revenue range: ~$540K–$1.15M.

    A good prior predictive should:
      - Cover the observed range comfortably
      - Not put appreciable mass below $0 or above $5M
    """
    print("\n  Running prior predictive check...")
    with model:
        prior_pred = pm.sample_prior_predictive(
            samples=n_samples,
            random_seed=RANDOM_SEED,
        )

    observed    = inputs["revenue"]
    dates       = pd.to_datetime(inputs["dates"])
    prior_draws = prior_pred.prior_predictive["revenue"].values  # (1, n_samples, T)
    prior_draws = prior_draws[0]  # → (n_samples, T)

    p05  = np.percentile(prior_draws, 5,  axis=0)
    p25  = np.percentile(prior_draws, 25, axis=0)
    p50  = np.percentile(prior_draws, 50, axis=0)
    p75  = np.percentile(prior_draws, 75, axis=0)
    p95  = np.percentile(prior_draws, 95, axis=0)

    fig, axes = plt.subplots(1, 2, figsize=(16, 5))
    fig.suptitle(
        "Prior Predictive Check — Canada\n"
        "Do the priors allow plausible revenue trajectories?",
        fontsize=13, fontweight="bold",
    )

    # ── Left: time-series fan chart ───────────────────────────────────────────
    ax = axes[0]
    ax.fill_between(dates, p05, p95, alpha=0.20, color="#4361EE", label="5–95th pct")
    ax.fill_between(dates, p25, p75, alpha=0.35, color="#4361EE", label="25–75th pct")
    ax.plot(dates, p50,      color="#4361EE", lw=1.5, label="Median prior")
    ax.plot(dates, observed, color="#E63946", lw=1.5, alpha=0.9, label="Observed revenue")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x/1e6:.1f}M"))
    ax.set_title("Prior predictive fan vs. observed", fontsize=11)
    ax.set_xlabel("Date")
    ax.set_ylabel("Revenue")
    ax.legend(fontsize=8, loc="upper left")

    # ── Right: marginal distribution of prior revenue ─────────────────────────
    ax = axes[1]
    flat = prior_draws.flatten()
    # Clip to ±$5M for display — extreme tails are less informative
    clipped = flat[(flat > -5e6) & (flat < 5e6)]
    ax.hist(clipped / 1e6, bins=80, color="#4361EE", alpha=0.65,
            edgecolor="white", linewidth=0.3)
    obs_min, obs_max = observed.min() / 1e6, observed.max() / 1e6
    ax.axvspan(obs_min, obs_max, alpha=0.25, color="#E63946",
               label=f"Observed range\n(${obs_min:.2f}M – ${obs_max:.2f}M)")
    ax.axvline(0, color="black", lw=1.2, linestyle="--", alpha=0.6, label="Zero revenue")
    ax.set_xlabel("Revenue ($M)")
    ax.set_ylabel("Count (prior draws)")
    ax.set_title("Marginal distribution of prior draws", fontsize=11)
    ax.legend(fontsize=8)

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()

    # ── Summary statistics ────────────────────────────────────────────────────
    pct_negative = (prior_draws < 0).mean() * 100
    pct_above_5m = (prior_draws > 5e6).mean() * 100
    print(f"  Prior predictive summary:")
    print(f"    Median prior revenue: ${np.median(prior_draws):,.0f}")
    print(f"    Prior 5–95th range:   ${p05.mean():,.0f} – ${p95.mean():,.0f} (avg per week)")
    print(f"    % draws < $0:         {pct_negative:.2f}%  (target: < 5%)")
    print(f"    % draws > $5M:        {pct_above_5m:.2f}%  (target: < 1%)")
    print(f"  ✓ Prior predictive saved: {save_path}")

    return prior_pred


# ══════════════════════════════════════════════════════════════════════════════
# 6. MCMC SAMPLING & DIAGNOSTICS
# ══════════════════════════════════════════════════════════════════════════════

def run_sampling(model: pm.Model,
                 draws: int = 1000,
                 tune: int = 1000,
                 chains: int = 4,
                 target_accept: float = 0.90) -> az.InferenceData:
    """
    Sample the posterior with NUTS.

    Sampler settings
    ----------------
    tune=1000   : Warmup steps for step-size and mass-matrix adaptation.
                  More than default (500) because MMM models have correlated
                  geometry (beta-alpha-k-ec are partially identifiable).
    draws=1000  : Posterior samples per chain. 4 chains × 1000 = 4000 total.
    target_accept=0.90 : Higher than default (0.8) to reduce divergences in
                  regions of high curvature (Hill function near saturation).

    Returns
    -------
    az.InferenceData with posterior, log_likelihood, and observed_data groups.
    """
    print(f"\n  Sampling posterior (chains={chains}, draws={draws}, tune={tune})...")
    print(f"  This may take several minutes for a 156-week model.\n")

    with model:
        idata = pm.sample(
            draws=draws,
            tune=tune,
            chains=chains,
            target_accept=target_accept,
            random_seed=RANDOM_SEED,
            progressbar=True,
            idata_kwargs={"log_likelihood": True},
        )

    return idata


def run_diagnostics(idata: az.InferenceData,
                    save_path: str = "outputs/fig_trace.png"):
    """
    Run ArviZ diagnostics and save trace plots for key parameters.

    Checks
    ------
    - R-hat: should be < 1.01 for all parameters (< 1.05 is acceptable).
    - Effective Sample Size (ESS): bulk and tail ESS should be > 400.
    - Divergences: any divergences warrant investigation.
    - MCSE: Monte Carlo standard error should be small relative to posterior sd.

    Parameters plotted
    ------------------
    We plot a curated subset: one representative parameter per type.
    Full trace plots for all 20+ parameters would be unreadable.
    """
    print("\n  Running MCMC diagnostics...")

    # ── R-hat and ESS summary ────────────────────────────────────────────────
    scalar_vars = [
        "intercept", "trend_slope", "sigma",
        "alpha_tv", "alpha_ps", "alpha_so", "alpha_disp",
        "k_tv", "k_ps", "k_so", "k_disp",
        "ec_tv", "ec_ps", "ec_so", "ec_disp",
        "beta_tv", "beta_ps", "beta_so", "beta_disp",
    ]

    summary = az.summary(idata, var_names=scalar_vars, round_to=4)
    print("\n  ── Posterior Summary ──")
    print(summary[["mean", "sd", "hdi_3%", "hdi_97%", "r_hat", "ess_bulk"]].to_string())

    n_divergences = int(idata.sample_stats["diverging"].values.sum())
    print(f"\n  Divergences: {n_divergences}")
    if n_divergences > 0:
        print("  ⚠ Divergences detected — consider reparameterisation or higher target_accept.")
    else:
        print("  ✓ No divergences.")

    rhat_vals = summary["r_hat"].dropna()
    max_rhat  = rhat_vals.max()
    n_bad     = (rhat_vals > 1.01).sum()
    print(f"\n  Max R-hat:        {max_rhat:.4f}  (target: < 1.01)")
    print(f"  Parameters > 1.01: {n_bad}")

    min_ess = summary["ess_bulk"].min()
    print(f"  Min bulk ESS:     {min_ess:.0f}  (target: > 400)")

    # ── Trace plots ──────────────────────────────────────────────────────────
    # Plot 8 representative parameters — one from each prior family
    trace_vars = [
        "intercept", "trend_slope", "sigma",
        "alpha_tv", "alpha_ps",
        "k_tv", "ec_tv", "beta_tv",
    ]

    axes = az.plot_trace(
        idata,
        var_names=trace_vars,
        figsize=(14, 18),
        compact=True,
    )
    fig = axes.ravel()[0].get_figure()
    fig.suptitle(
        "MCMC Trace Plots — Canada (Representative Parameters)\n"
        "Left: posterior density  |  Right: sample trace (should look like 'fuzzy caterpillar')",
        fontsize=11, fontweight="bold", y=1.005,
    )
    plt.tight_layout()
    plt.savefig(save_path, dpi=120, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"\n  ✓ Trace plot saved: {save_path}")

    return summary


# ══════════════════════════════════════════════════════════════════════════════
# 7. PARAMETER RECOVERY
# ══════════════════════════════════════════════════════════════════════════════

def plot_parameter_recovery(idata: az.InferenceData,
                             save_path: str = "outputs/fig_parameter_recovery.png"):
    """
    Plot posterior distributions against true parameter values.

    This is the core model validation step. For each key parameter, we plot:
      - The marginal posterior density (KDE from ArviZ)
      - A vertical line marking the true DGP value
      - The 94% HDI (ArviZ default)

    A well-identified model should have the true value inside the 94% HDI
    for most parameters. Near-perfect recovery on all parameters would be
    suspicious (overfit); some uncertainty is expected and correct.

    Parameters shown
    ----------------
    Adstock decays (α), Hill slopes (k), Hill half-saturation (ec),
    channel betas (β), intercept, trend_slope, sigma.

    Note on beta recovery
    ----------------------
    β and k are partially identified — a high β with low k can produce
    similar predicted revenue to a lower β with higher k. Expect wider
    posteriors here and possible mild bias, which is a genuine model
    limitation to discuss in the writeup.
    """
    print("\n  Plotting parameter recovery...")

    # ── True values for each recoverable scalar parameter ────────────────────
    true_values = {
        "intercept":   TRUE_PARAMS["intercept"],
        # trend_slope: posterior is in ($/unit t_std). True equivalent = 950 × 155.
        # Both sides are multiplied by (N_WEEKS-1) so the comparison is consistent.
        "trend_slope": TRUE_PARAMS["trend_slope"] * (N_WEEKS - 1),
        "sigma":       TRUE_PARAMS["noise_std"],
        "alpha_tv":    TRUE_PARAMS["adstock"]["tv"],
        "alpha_ps":    TRUE_PARAMS["adstock"]["paid_search"],
        "alpha_so":    TRUE_PARAMS["adstock"]["social"],
        "alpha_disp":  TRUE_PARAMS["adstock"]["display"],
        "k_tv":        TRUE_PARAMS["hill_k"]["tv"],
        "k_ps":        TRUE_PARAMS["hill_k"]["paid_search"],
        "k_so":        TRUE_PARAMS["hill_k"]["social"],
        "k_disp":      TRUE_PARAMS["hill_k"]["display"],
        "ec_tv":       TRUE_PARAMS["hill_ec"]["tv"],
        "ec_ps":       TRUE_PARAMS["hill_ec"]["paid_search"],
        "ec_so":       TRUE_PARAMS["hill_ec"]["social"],
        "ec_disp":     TRUE_PARAMS["hill_ec"]["display"],
        "beta_tv":     TRUE_PARAMS["beta"]["tv"],
        "beta_ps":     TRUE_PARAMS["beta"]["paid_search"],
        "beta_so":     TRUE_PARAMS["beta"]["social"],
        "beta_disp":   TRUE_PARAMS["beta"]["display"],
    }

    param_labels = {
        "intercept":   "Intercept ($)",
        "trend_slope": "Trend slope (total $ over 3yr)",
        "sigma":       "Noise σ ($)",
        "alpha_tv":    "α TV",
        "alpha_ps":    "α Paid Search",
        "alpha_so":    "α Social",
        "alpha_disp":  "α Display",
        "k_tv":        "k TV",
        "k_ps":        "k Paid Search",
        "k_so":        "k Social",
        "k_disp":      "k Display",
        "ec_tv":       "ec TV",
        "ec_ps":       "ec Paid Search",
        "ec_so":       "ec Social",
        "ec_disp":     "ec Display",
        "beta_tv":     "β TV ($)",
        "beta_ps":     "β Paid Search ($)",
        "beta_so":     "β Social ($)",
        "beta_disp":   "β Display ($)",
    }

    param_colors = {
        "intercept": "#6A4C93", "trend_slope": "#6A4C93", "sigma": "#6A4C93",
        "alpha_tv": PALETTE["tv"], "alpha_ps": PALETTE["paid_search"],
        "alpha_so": PALETTE["social"], "alpha_disp": PALETTE["display"],
        "k_tv": PALETTE["tv"], "k_ps": PALETTE["paid_search"],
        "k_so": PALETTE["social"], "k_disp": PALETTE["display"],
        "ec_tv": PALETTE["tv"], "ec_ps": PALETTE["paid_search"],
        "ec_so": PALETTE["social"], "ec_disp": PALETTE["display"],
        "beta_tv": PALETTE["tv"], "beta_ps": PALETTE["paid_search"],
        "beta_so": PALETTE["social"], "beta_disp": PALETTE["display"],
    }

    params = list(true_values.keys())
    n_params = len(params)
    n_cols = 4
    n_rows = int(np.ceil(n_params / n_cols))

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(18, n_rows * 3.2))
    axes_flat = axes.flatten()

    posterior = idata.posterior

    for i, param in enumerate(params):
        ax = axes_flat[i]
        color = param_colors[param]

        # Extract posterior samples (all chains, all draws)
        samples = posterior[param].values.flatten()

        # Special case: trend_slope was estimated on t_std ∈ [0,1], so the
        # posterior is in units of ($/unit of t_std). Multiply by (T-1) to
        # convert back to $/week for a fair comparison to the true value.
        if param == "trend_slope":
            samples = samples * (N_WEEKS - 1)

        # KDE via ArviZ
        az.plot_kde(
            samples,
            ax=ax,
            plot_kwargs={"color": color, "linewidth": 2},
            fill_kwargs={"alpha": 0.25, "color": color},
        )

        # True value line
        true_val = true_values[param]
        ax.axvline(true_val, color="black", lw=2, linestyle="--",
                   label=f"True: {true_val:,.0f}" if abs(true_val) > 1 else f"True: {true_val:.3f}")

        # 94% HDI
        hdi = az.hdi(samples, hdi_prob=0.94)
        ax.axvspan(hdi[0], hdi[1], alpha=0.10, color=color, label="94% HDI")

        # Check recovery
        inside_hdi = hdi[0] <= true_val <= hdi[1]
        recovery_marker = "✓" if inside_hdi else "✗"
        ax.set_title(f"{param_labels[param]}  {recovery_marker}", fontsize=8.5,
                     fontweight="bold", color=color)
        ax.tick_params(labelsize=7)
        ax.legend(fontsize=6.5, loc="upper right")

        # Format x-axis for dollar values
        if param in ("intercept", "trend_slope", "sigma", "beta_tv",
                     "beta_ps", "beta_so", "beta_disp"):
            ax.xaxis.set_major_formatter(
                mticker.FuncFormatter(lambda x, _: f"${x/1e3:.0f}K")
            )

    # Hide unused subplots
    for j in range(n_params, len(axes_flat)):
        axes_flat[j].set_visible(False)

    # Count recovery rate
    n_recovered = sum(
        az.hdi(
            (posterior[p].values.flatten() * (N_WEEKS - 1)
             if p == "trend_slope"
             else posterior[p].values.flatten()),
            hdi_prob=0.94
        )[0] <= true_values[p] <=
        az.hdi(
            (posterior[p].values.flatten() * (N_WEEKS - 1)
             if p == "trend_slope"
             else posterior[p].values.flatten()),
            hdi_prob=0.94
        )[1]
        for p in params
    )

    fig.suptitle(
        f"Parameter Recovery — Canada  ({n_recovered}/{n_params} true values inside 94% HDI)\n"
        "Black dashed = true DGP value  |  ✓ = inside HDI  |  ✗ = outside HDI",
        fontsize=12, fontweight="bold", y=1.01,
    )
    plt.tight_layout()
    plt.savefig(save_path, dpi=130, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Parameter recovery saved: {save_path}")
    print(f"  Recovery rate: {n_recovered}/{n_params} parameters inside 94% HDI")


# ══════════════════════════════════════════════════════════════════════════════
# 8. POSTERIOR CONTRIBUTION DECOMPOSITION
# ══════════════════════════════════════════════════════════════════════════════

def plot_posterior_contributions(idata: az.InferenceData,
                                  inputs: dict,
                                  save_path: str = "outputs/fig_posterior_contributions.png"):
    """
    Plot posterior mean channel contributions vs. ground-truth contributions.

    This produces a stacked area chart using the posterior mean of each
    channel's deterministic contribution. Shaded bands show the 94% credible
    interval, giving an honest uncertainty representation.
    """
    print("\n  Plotting posterior contributions...")

    posterior = idata.posterior
    dates     = pd.to_datetime(inputs["dates"])
    revenue   = inputs["revenue"]

    fig, axes = plt.subplots(2, 1, figsize=(15, 11), sharex=True)
    fig.suptitle(
        "Canada — Posterior Revenue Decomposition\n"
        "Top: posterior mean contributions  |  Bottom: observed vs. predicted",
        fontsize=13, fontweight="bold",
    )

    # ── Top panel: stacked contribution areas ─────────────────────────────────
    ax = axes[0]
    baseline_post = posterior["baseline"].values  # (chains, draws, T)
    baseline_mean = baseline_post.reshape(-1, inputs["T"]).mean(axis=0)

    ax.fill_between(dates, 0, baseline_mean, alpha=0.5,
                    color=PALETTE["baseline"], label="Baseline")
    bottom = baseline_mean.copy()

    for ch in CHANNELS:
        contrib = posterior[f"contrib_{ch}"].values.reshape(-1, inputs["T"])
        c_mean  = contrib.mean(axis=0)
        c_lo    = np.percentile(contrib, 3, axis=0)
        c_hi    = np.percentile(contrib, 97, axis=0)

        ax.fill_between(dates, bottom, bottom + c_mean, alpha=0.75,
                        color=PALETTE[ch], label=CHANNEL_LABELS[ch])
        bottom += c_mean

    ax.plot(dates, revenue, color="white", lw=0.8, alpha=0.6, label="Observed revenue")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x/1e3:.0f}K"))
    ax.set_ylabel("Revenue ($)")
    ax.legend(loc="upper left", fontsize=9, ncol=3)

    # ── Bottom panel: posterior predicted vs. observed ────────────────────────
    ax = axes[1]
    mu_post = posterior["mu"].values.reshape(-1, inputs["T"])  # (total_draws, T)
    mu_mean = mu_post.mean(axis=0)
    mu_lo   = np.percentile(mu_post, 3,  axis=0)
    mu_hi   = np.percentile(mu_post, 97, axis=0)

    ax.fill_between(dates, mu_lo, mu_hi, alpha=0.25, color="#4361EE",
                    label="94% posterior predictive band")
    ax.plot(dates, mu_mean, color="#4361EE", lw=1.5, label="Posterior mean")
    ax.plot(dates, revenue, color="#E63946", lw=1.2, alpha=0.85, label="Observed revenue")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x/1e3:.0f}K"))
    ax.set_xlabel("Date")
    ax.set_ylabel("Revenue ($)")
    ax.legend(loc="upper left", fontsize=9)

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()
    print(f"  ✓ Contribution decomposition saved: {save_path}")


# ══════════════════════════════════════════════════════════════════════════════
# 9. ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

def run_phase3(
    sampling_draws:   int   = 1000,
    sampling_tune:    int   = 1000,
    sampling_chains:  int   = 4,
    target_accept:    float = 0.90,
    prior_samples:    int   = 500,
    save_idata:       bool  = True,
):
    """
    Full Phase 3 pipeline:
        1. Load data
        2. Build model inputs
        3. Build PyMC model
        4. Prior predictive check
        5. MCMC sampling
        6. Diagnostics
        7. Parameter recovery
        8. Posterior contribution decomposition

    Parameters
    ----------
    sampling_draws  : Posterior draws per chain.
    sampling_tune   : Warmup (tuning) steps per chain.
    sampling_chains : Number of independent MCMC chains.
    target_accept   : NUTS target acceptance rate.
    prior_samples   : Prior predictive samples.
    save_idata      : If True, save InferenceData to outputs/idata_canada.nc.
    """
    print("=" * 65)
    print("MapleThread Outdoor Co. — Phase 3: Single-Region Bayesian MMM")
    print(f"Region: Canada  |  {N_WEEKS} weeks")
    print("=" * 65)

    # ── Step 1: Load data ─────────────────────────────────────────────────────
    print("\n[1/7] Loading data...")
    raw_df, gt_df = load_canada_data()

    # ── Step 2: Build model inputs ────────────────────────────────────────────
    print("\n[2/7] Building model inputs...")
    inputs = build_model_inputs(raw_df)
    print(f"  t_std range:         [{inputs['t_std'].min():.2f}, {inputs['t_std'].max():.2f}]")
    for ch in CHANNELS:
        print(f"  p95 ({ch:>12s}): {inputs['p95'][ch]:>12,.0f}")

    # ── Step 3: Build model ───────────────────────────────────────────────────
    print("\n[3/7] Building PyMC model...")
    model = build_model(inputs)
    print(f"  Free parameters: {len(model.free_RVs)}")
    print(f"  {model}")

    # ── Step 4: Prior predictive check ────────────────────────────────────────
    print("\n[4/7] Prior predictive check...")
    prior_pred = run_prior_predictive(model, inputs, n_samples=prior_samples)

    # ── Step 5: MCMC sampling ─────────────────────────────────────────────────
    print("\n[5/7] MCMC sampling...")
    idata = run_sampling(
        model,
        draws=sampling_draws,
        tune=sampling_tune,
        chains=sampling_chains,
        target_accept=target_accept,
    )

    # ── Step 6: Diagnostics ───────────────────────────────────────────────────
    print("\n[6/7] Diagnostics...")
    summary = run_diagnostics(idata)

    # ── Step 7: Parameter recovery ────────────────────────────────────────────
    print("\n[7/7] Parameter recovery & contribution plots...")
    plot_parameter_recovery(idata)
    plot_posterior_contributions(idata, inputs)

    # ── Save InferenceData ────────────────────────────────────────────────────
    if save_idata:
        idata_path = "outputs/idata_canada.nc"
        idata.to_netcdf(idata_path)
        print(f"\n  ✓ InferenceData saved: {idata_path}")

    print("\n" + "=" * 65)
    print("Phase 3 complete. ✓")
    print("=" * 65)

    return model, idata, inputs


# ── Run ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    # For a quick smoke-test pass smaller values:
    #   run_phase3(sampling_draws=200, sampling_tune=200, sampling_chains=2)
    model, idata, inputs = run_phase3(
        sampling_draws=1000,
        sampling_tune=1000,
        sampling_chains=4,
        target_accept=0.90,
        prior_samples=500,
    )

