# -*- coding: utf-8 -*-
"""transformations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oTOJAkbLOgeiEOchHUuf4tWCeSAS0XzW
"""

# -*- coding: utf-8 -*-
"""
transformations.py
==================
MapleThread Outdoor Co. — MMM Phase 2: Media Transformations + Tests

Implements standalone, numerically-tested media transformation functions:
  - geometric_adstock   : Geometric (exponential) decay carryover
  - weibull_adstock     : Flexible two-parameter Weibull carryover
  - hill_saturation     : Hill / S-curve diminishing-returns saturation
  - transform_spend     : Full pipeline (adstock → normalise → Hill) matching DGP
  - hill_derivative     : Analytical derivative for marginal ROAS (Phase 5)

All functions are pure (no side effects), operate on NumPy arrays, and are
safe to use inside PyMC model definitions (compatible with PyTensor ops when
arrays are swapped for tensors — see docstring notes).

Usage
-----
  Import functions:  from transformations import geometric_adstock, hill_saturation
  Run tests:         pytest transformations.py -v
"""

from __future__ import annotations

import numpy as np


# ══════════════════════════════════════════════════════════════════════════════
# 1. GEOMETRIC ADSTOCK
# ══════════════════════════════════════════════════════════════════════════════

def geometric_adstock(
    spend: np.ndarray,
    alpha: float,
    *,
    normalise: bool = False,
    normalise_percentile: float = 95.0,
) -> np.ndarray:
    """
    Geometric (exponential) adstock transformation.

    Each period's adstock is current spend plus alpha times the previous
    adstock value, forming a recursive convolution:

        adstock[0] = spend[0]
        adstock[t] = spend[t] + alpha * adstock[t-1]   for t >= 1

    The result is an impressionistic memory of past spend: high alpha values
    (e.g. 0.75 for TV) create a long tail of carryover; low values (e.g. 0.15
    for Display) decay almost immediately.

    Parameters
    ----------
    spend : np.ndarray, shape (T,)
        Raw media spend time series. All values should be >= 0.
    alpha : float
        Decay rate in [0, 1). 0 = no carryover; values close to 1 = very long
        memory. Typical range:
            TV           ~ 0.70–0.80  (brand-building, long carryover)
            Social       ~ 0.40–0.55  (medium carryover)
            Paid Search  ~ 0.15–0.25  (mostly immediate demand capture)
            Display      ~ 0.10–0.20  (very short carryover)
    normalise : bool, optional
        If True, divide the resulting adstock by its `normalise_percentile`
        percentile, rescaling to a [0, ~1] range. Useful before Hill
        saturation so the ec parameter is interpretable on a 0–1 scale.
        Default: False.
    normalise_percentile : float, optional
        Percentile used for normalisation. Default: 95.0, matching the DGP.

    Returns
    -------
    np.ndarray, shape (T,)
        Adstock series (same length as spend). Normalised to [0, ~1] if
        `normalise=True`.

    Notes
    -----
    PyMC compatibility: replace the Python for-loop with pytensor.scan when
    embedding this inside a pm.Model for vectorised gradient computation.

    Examples
    --------
    >>> spend = np.array([100., 0., 0., 0., 0.])
    >>> geometric_adstock(spend, alpha=0.5)
    array([100.  ,  50.  ,  25.  ,  12.5 ,   6.25])
    """
    if not (0.0 <= alpha < 1.0):
        raise ValueError(f"alpha must be in [0, 1), got {alpha!r}")
    if np.any(spend < 0):
        raise ValueError("spend contains negative values; all entries must be >= 0.")

    spend = np.asarray(spend, dtype=float)
    adstock = np.empty_like(spend)
    adstock[0] = spend[0]
    for t in range(1, len(spend)):
        adstock[t] = spend[t] + alpha * adstock[t - 1]

    if normalise:
        p = np.percentile(adstock, normalise_percentile)
        if p > 0:
            adstock = adstock / p

    return adstock


# ══════════════════════════════════════════════════════════════════════════════
# 2. WEIBULL ADSTOCK
# ══════════════════════════════════════════════════════════════════════════════

def weibull_adstock(
    spend: np.ndarray,
    shape: float,
    scale: float,
    *,
    max_lag: int = 13,
    normalise: bool = False,
    normalise_percentile: float = 95.0,
) -> np.ndarray:
    """
    Weibull adstock (convolution-based carryover) transformation.

    Instead of a single exponential decay, the Weibull distribution defines a
    flexible lag weight kernel w[l] for l = 0, 1, …, max_lag - 1:

        survival[l] = exp(-(l / scale)^shape)   (Weibull survival function)
        w[l]        = survival[l] / sum(survival)

    The adstock at time t is then the weighted sum of current and past spend:

        adstock[t] = sum_{l=0}^{min(t, max_lag-1)} w[l] * spend[t - l]

    This is a finite-window linear convolution, which is more tractable in
    PyMC (no scan required) and more expressive than geometric decay:

    - shape < 1 : front-loaded decay (most effect immediate, long thin tail)
    - shape = 1 : reduces to exponential / geometric-like decay
    - shape > 1 : delayed peak — ad effect builds before decaying (e.g. TV
                  brand campaigns where awareness compounds then wanes)

    Parameters
    ----------
    spend : np.ndarray, shape (T,)
        Raw media spend time series. All values should be >= 0.
    shape : float
        Weibull shape parameter (k > 0). Controls the shape of the carryover
        curve. Typical range: 0.5–3.0.
    scale : float
        Weibull scale parameter (λ > 0). Controls how quickly weights decay.
        Larger scale = longer effective memory. Typical range: 1.0–8.0.
    max_lag : int, optional
        Number of lagged periods to include in the convolution kernel.
        Default: 13 (approx. one quarter of weekly data).
    normalise : bool, optional
        If True, normalise the output by its `normalise_percentile` percentile.
    normalise_percentile : float, optional
        Percentile for normalisation. Default: 95.0.

    Returns
    -------
    np.ndarray, shape (T,)
        Weibull adstock series.

    Notes
    -----
    The convolution-based implementation is directly compatible with PyMC /
    PyTensor using pytensor.tensor.signal.conv.conv2d or manual dot products
    over the lagged spend matrix.

    Examples
    --------
    >>> spend = np.array([100., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
    >>> weibull_adstock(spend, shape=2.0, scale=3.0)  # delayed peak
    array([...])
    """
    if shape <= 0:
        raise ValueError(f"shape must be > 0, got {shape!r}")
    if scale <= 0:
        raise ValueError(f"scale must be > 0, got {scale!r}")
    if np.any(spend < 0):
        raise ValueError("spend contains negative values; all entries must be >= 0.")

    spend = np.asarray(spend, dtype=float)
    lags = np.arange(max_lag, dtype=float)

    # Weibull survival function as lag weights
    weights = np.exp(-((lags / scale) ** shape))
    weights = weights / weights.sum()  # normalise to sum to 1

    T = len(spend)
    adstock = np.zeros(T, dtype=float)
    for t in range(T):
        for l in range(min(t + 1, max_lag)):
            adstock[t] += weights[l] * spend[t - l]

    if normalise:
        p = np.percentile(adstock, normalise_percentile)
        if p > 0:
            adstock = adstock / p

    return adstock


# ══════════════════════════════════════════════════════════════════════════════
# 3. HILL SATURATION
# ══════════════════════════════════════════════════════════════════════════════

def hill_saturation(
    x: np.ndarray,
    k: float,
    ec: float,
) -> np.ndarray:
    """
    Hill saturation (diminishing-returns) function.

    Maps any non-negative input to the interval (0, 1], encoding the empirical
    observation that media returns diminish as spend increases:

        S(x) = x^k / (x^k + ec^k)

    At x = ec, S = 0.5 exactly — ec is the "half-saturation point", the spend
    level at which you achieve half the theoretical maximum effect.

    Shape intuition
    ---------------
    k (slope / Hill coefficient):
        k < 1 : concave from the start — diminishing returns immediately.
        k = 1 : hyperbolic (Michaelis–Menten) saturation.
        k > 1 : sigmoid / S-curve with an initial convex phase before
                diminishing returns kick in. Higher k = sharper transition.
    ec (half-saturation):
        Smaller ec = faster saturation (channel reaches diminishing returns at
        lower spend levels). Larger ec = more room to grow before saturation.

    MapleThread ground-truth parameters (for reference):
        TV          : k=2.5, ec=0.4  → strong S-curve, saturates quickly
        Paid Search : k=1.5, ec=0.6  → moderate sigmoid
        Social      : k=1.2, ec=0.7  → mild curvature, room to grow
        Display     : k=3.0, ec=0.3  → very sharp S-curve, saturates fast

    Parameters
    ----------
    x : np.ndarray
        Input values (normalised adstock). All values should be >= 0. Typically
        in [0, ~1.5] after 95th-percentile normalisation.
    k : float
        Hill slope parameter (> 0). Controls curvature.
    ec : float
        Half-saturation point (> 0). At x = ec, output = 0.5.

    Returns
    -------
    np.ndarray
        Saturation-adjusted effect, values in (0, 1].

    Examples
    --------
    >>> hill_saturation(np.array([0.0, 0.4, 1.0, 2.0]), k=2.0, ec=0.5)
    array([0.        , 0.39024390, 0.8       , 0.94117647])
    """
    if k <= 0:
        raise ValueError(f"k must be > 0, got {k!r}")
    if ec <= 0:
        raise ValueError(f"ec must be > 0, got {ec!r}")

    x = np.asarray(x, dtype=float)
    # Avoid 0^k = 0 / 0 ambiguity at x=0: result is correctly 0 (no spend → no effect)
    safe_x = np.where(x == 0.0, 1e-10, x)
    return safe_x**k / (safe_x**k + ec**k)


# ══════════════════════════════════════════════════════════════════════════════
# 4. FULL PIPELINE: ADSTOCK → NORMALISE → HILL
# ══════════════════════════════════════════════════════════════════════════════

def transform_spend(
    spend: np.ndarray,
    alpha: float,
    k: float,
    ec: float,
    *,
    normalise_percentile: float = 95.0,
    use_weibull: bool = False,
    weibull_shape: float | None = None,
    weibull_scale: float | None = None,
    weibull_max_lag: int = 13,
) -> dict[str, np.ndarray]:
    """
    Full media transformation pipeline matching the MapleThread DGP.

    Applies in sequence:
        1. Adstock (geometric or Weibull) → captures carryover
        2. Normalisation by `normalise_percentile` percentile → [0, ~1]
        3. Hill saturation → diminishing returns in [0, 1]

    This function is the canonical transformation used in both data generation
    and model construction, ensuring consistency between the two.

    Parameters
    ----------
    spend : np.ndarray, shape (T,)
        Raw media spend for one channel.
    alpha : float
        Geometric adstock decay rate in [0, 1). Ignored if use_weibull=True.
    k : float
        Hill slope parameter (> 0).
    ec : float
        Hill half-saturation point (> 0).
    normalise_percentile : float, optional
        Percentile for adstock normalisation. Default: 95.0 (matches DGP).
    use_weibull : bool, optional
        If True, use Weibull adstock instead of geometric. Requires
        weibull_shape and weibull_scale. Default: False.
    weibull_shape : float, optional
        Weibull shape parameter. Required when use_weibull=True.
    weibull_scale : float, optional
        Weibull scale parameter. Required when use_weibull=True.
    weibull_max_lag : int, optional
        Maximum lag window for Weibull convolution. Default: 13.

    Returns
    -------
    dict with keys:
        "adstock"      : np.ndarray — raw adstock (before normalisation)
        "adstock_norm" : np.ndarray — normalised adstock (input to Hill)
        "saturated"    : np.ndarray — Hill-transformed output in [0, 1]

    Examples
    --------
    >>> spend = np.random.default_rng(0).lognormal(10, 0.3, 52)
    >>> result = transform_spend(spend, alpha=0.75, k=2.5, ec=0.4)
    >>> result["saturated"].shape
    (52,)
    """
    if use_weibull:
        if weibull_shape is None or weibull_scale is None:
            raise ValueError(
                "weibull_shape and weibull_scale must be provided when use_weibull=True."
            )
        adstock = weibull_adstock(
            spend,
            shape=weibull_shape,
            scale=weibull_scale,
            max_lag=weibull_max_lag,
        )
    else:
        adstock = geometric_adstock(spend, alpha)

    p = np.percentile(adstock, normalise_percentile)
    adstock_norm = adstock / p if p > 0 else adstock.copy()

    saturated = hill_saturation(adstock_norm, k, ec)

    return {
        "adstock":      adstock,
        "adstock_norm": adstock_norm,
        "saturated":    saturated,
    }


# ══════════════════════════════════════════════════════════════════════════════
# 5. MARGINAL ROAS UTILITY
# ══════════════════════════════════════════════════════════════════════════════

def hill_derivative(x: float | np.ndarray, k: float, ec: float) -> np.ndarray:
    """
    Analytical derivative of the Hill function with respect to x.

    Used to compute marginal ROAS at current spend levels (Phase 5):

        dS/dx = k * ec^k * x^(k-1) / (x^k + ec^k)^2

    Parameters
    ----------
    x : float or np.ndarray
        Input spend level (normalised adstock). Should be > 0.
    k : float
        Hill slope parameter.
    ec : float
        Hill half-saturation point.

    Returns
    -------
    np.ndarray
        Marginal effect per unit of normalised adstock at each point in x.

    Notes
    -----
    To convert to marginal revenue (approximate ROAS), multiply the result
    by beta / p95, where beta is the channel coefficient and p95 is the
    normalisation constant used in adstock scaling.
    """
    x = np.asarray(x, dtype=float)
    safe_x = np.where(x <= 0, 1e-10, x)
    numerator   = k * (ec**k) * (safe_x ** (k - 1))
    denominator = (safe_x**k + ec**k) ** 2
    return np.where(x <= 0, 0.0, numerator / denominator)

# ══════════════════════════════════════════════════════════════════════════════
# TESTS  —  run with: pytest transformations.py -v
# ══════════════════════════════════════════════════════════════════════════════

import pytest

# ── Shared fixtures ───────────────────────────────────────────────────────────

SEED = 42
RNG  = np.random.default_rng(SEED)
N    = 52  # one year of weekly data

# Realistic spend vectors
SPEND_STEADY  = np.full(N, 100_000.0)
SPEND_PULSE   = np.zeros(N); SPEND_PULSE[0] = 100_000.0
SPEND_RANDOM  = RNG.lognormal(np.log(80_000), 0.3, N)
SPEND_ZEROS   = np.zeros(N)


# ══════════════════════════════════════════════════════════════════════════════
# geometric_adstock
# ══════════════════════════════════════════════════════════════════════════════

class TestGeometricAdstock:

    def test_single_pulse_decays_correctly(self):
        """A single spend impulse should decay geometrically."""
        spend = np.zeros(5)
        spend[0] = 100.0
        result = geometric_adstock(spend, alpha=0.5)
        expected = np.array([100.0, 50.0, 25.0, 12.5, 6.25])
        np.testing.assert_allclose(result, expected, rtol=1e-6)

    def test_zero_alpha_no_carryover(self):
        """alpha=0 means adstock equals raw spend (no carryover)."""
        spend = np.array([10.0, 20.0, 30.0, 0.0, 50.0])
        result = geometric_adstock(spend, alpha=0.0)
        np.testing.assert_allclose(result, spend, rtol=1e-10)

    def test_output_length_preserved(self):
        result = geometric_adstock(SPEND_RANDOM, alpha=0.5)
        assert result.shape == SPEND_RANDOM.shape

    def test_zero_spend_returns_zeros(self):
        result = geometric_adstock(SPEND_ZEROS, alpha=0.7)
        np.testing.assert_allclose(result, 0.0, atol=1e-10)

    def test_high_alpha_accumulates(self):
        """High alpha should produce values well above the raw spend."""
        spend = np.full(20, 100.0)
        result = geometric_adstock(spend, alpha=0.9)
        # At steady state, adstock ≈ spend / (1 - alpha) = 1000
        assert result[-1] > 500.0, "High alpha adstock should accumulate significantly."

    def test_steady_state_value(self):
        """At steady-state, adstock = spend / (1 - alpha)."""
        spend = np.full(200, 100.0)
        alpha = 0.75
        result = geometric_adstock(spend, alpha=alpha)
        expected_ss = 100.0 / (1 - alpha)
        np.testing.assert_allclose(result[-1], expected_ss, rtol=1e-3)

    def test_normalise_flag_produces_unit_scale(self):
        """normalise=True should put the 95th percentile at 1.0."""
        result = geometric_adstock(SPEND_RANDOM, alpha=0.5, normalise=True)
        p95 = np.percentile(result, 95)
        np.testing.assert_allclose(p95, 1.0, rtol=1e-6)

    def test_non_negative_output(self):
        result = geometric_adstock(SPEND_RANDOM, alpha=0.45)
        assert np.all(result >= 0), "Adstock must be non-negative."

    def test_invalid_alpha_raises(self):
        with pytest.raises(ValueError, match="alpha"):
            geometric_adstock(SPEND_RANDOM, alpha=1.0)
        with pytest.raises(ValueError, match="alpha"):
            geometric_adstock(SPEND_RANDOM, alpha=-0.1)

    def test_negative_spend_raises(self):
        bad_spend = np.array([100.0, -50.0, 200.0])
        with pytest.raises(ValueError, match="negative"):
            geometric_adstock(bad_spend, alpha=0.5)

    @pytest.mark.parametrize("alpha", [0.15, 0.20, 0.45, 0.75])
    def test_mapplethread_channels(self, alpha):
        """All four MapleThread decay rates should run without error."""
        result = geometric_adstock(SPEND_RANDOM, alpha=alpha)
        assert result.shape == SPEND_RANDOM.shape
        assert np.all(np.isfinite(result))

    def test_dtype_float(self):
        spend_int = np.array([100, 200, 300], dtype=int)
        result = geometric_adstock(spend_int, alpha=0.5)
        assert result.dtype == float


# ══════════════════════════════════════════════════════════════════════════════
# weibull_adstock
# ══════════════════════════════════════════════════════════════════════════════

class TestWeibullAdstock:

    def test_output_length_preserved(self):
        result = weibull_adstock(SPEND_RANDOM, shape=1.5, scale=3.0)
        assert result.shape == SPEND_RANDOM.shape

    def test_zero_spend_returns_zeros(self):
        result = weibull_adstock(SPEND_ZEROS, shape=1.5, scale=3.0)
        np.testing.assert_allclose(result, 0.0, atol=1e-10)

    def test_non_negative_output(self):
        result = weibull_adstock(SPEND_RANDOM, shape=2.0, scale=4.0)
        assert np.all(result >= 0)

    def test_weights_sum_to_one(self):
        """Weibull lag weights must sum to 1 (probability distribution)."""
        shape, scale, max_lag = 1.5, 3.0, 13
        lags = np.arange(max_lag, dtype=float)
        weights = np.exp(-((lags / scale) ** shape))
        weights /= weights.sum()
        np.testing.assert_allclose(weights.sum(), 1.0, rtol=1e-10)

    def test_pulse_response_bounded_by_spend(self):
        """A single pulse: all adstock values should be <= pulse magnitude."""
        result = weibull_adstock(SPEND_PULSE, shape=1.5, scale=3.0)
        assert np.all(result <= SPEND_PULSE[0] + 1e-6)

    def test_shape_1_approx_geometric(self):
        """
        Shape=1 (exponential Weibull) should approximate geometric adstock
        for short series, within reasonable tolerance (they are different
        parameterisations but both exponential-family).
        """
        # Just check it runs and gives finite values
        result = weibull_adstock(SPEND_RANDOM, shape=1.0, scale=5.0)
        assert np.all(np.isfinite(result))

    def test_delayed_peak_with_high_shape(self):
        """shape > 1 creates a delayed response peak for an impulse input."""
        result = weibull_adstock(SPEND_PULSE, shape=3.0, scale=3.0, max_lag=13)
        # Peak should not be at t=0 for shape > 1
        assert np.argmax(result) > 0, "Delayed peak expected for shape > 1."

    def test_invalid_shape_raises(self):
        with pytest.raises(ValueError, match="shape"):
            weibull_adstock(SPEND_RANDOM, shape=0.0, scale=3.0)
        with pytest.raises(ValueError, match="shape"):
            weibull_adstock(SPEND_RANDOM, shape=-1.0, scale=3.0)

    def test_invalid_scale_raises(self):
        with pytest.raises(ValueError, match="scale"):
            weibull_adstock(SPEND_RANDOM, shape=1.5, scale=0.0)

    def test_negative_spend_raises(self):
        bad = np.array([100.0, -10.0, 200.0])
        with pytest.raises(ValueError, match="negative"):
            weibull_adstock(bad, shape=1.5, scale=3.0)

    def test_normalise_produces_unit_p95(self):
        result = weibull_adstock(SPEND_RANDOM, shape=1.5, scale=3.0, normalise=True)
        np.testing.assert_allclose(np.percentile(result, 95), 1.0, rtol=1e-6)

    @pytest.mark.parametrize("shape,scale", [(0.5, 2.0), (1.0, 3.0), (2.0, 4.0), (3.0, 5.0)])
    def test_various_shapes(self, shape, scale):
        result = weibull_adstock(SPEND_RANDOM, shape=shape, scale=scale)
        assert result.shape == SPEND_RANDOM.shape
        assert np.all(np.isfinite(result))
        assert np.all(result >= 0)


# ══════════════════════════════════════════════════════════════════════════════
# hill_saturation
# ══════════════════════════════════════════════════════════════════════════════

class TestHillSaturation:

    def test_output_range_bounded(self):
        """Hill output must always be in (0, 1]."""
        x = np.linspace(0, 10, 1000)
        result = hill_saturation(x, k=2.0, ec=0.5)
        assert np.all(result >= 0), "Hill output must be >= 0."
        assert np.all(result <= 1.0 + 1e-10), "Hill output must be <= 1."

    def test_half_saturation_at_ec(self):
        """At x = ec, Hill function must return exactly 0.5."""
        for k, ec in [(1.5, 0.6), (2.5, 0.4), (3.0, 0.3), (1.2, 0.7)]:
            result = hill_saturation(np.array([ec]), k=k, ec=ec)
            np.testing.assert_allclose(result, 0.5, rtol=1e-6,
                err_msg=f"Hill(ec) != 0.5 for k={k}, ec={ec}")

    def test_asymptote_at_large_x(self):
        """Hill function should approach 1 asymptotically."""
        x = np.array([1e6])
        result = hill_saturation(x, k=2.0, ec=0.5)
        np.testing.assert_allclose(result, 1.0, rtol=1e-4)

    def test_zero_spend_approaches_zero(self):
        """Hill function at x=0 should return ~0 (no spend, no effect)."""
        result = hill_saturation(np.array([0.0]), k=2.0, ec=0.5)
        assert result[0] < 1e-8

    def test_monotone_increasing(self):
        """Hill function must be monotonically non-decreasing."""
        x = np.linspace(0, 5, 500)
        result = hill_saturation(x, k=2.5, ec=0.4)
        diffs = np.diff(result)
        assert np.all(diffs >= -1e-10), "Hill function must be monotonically increasing."

    def test_higher_k_sharper_curve(self):
        """
        Higher k should produce a sharper S-curve: at x < ec, lower response;
        at x > ec (well above), higher response — compared to lower k.
        """
        x_below = np.array([0.1])
        low_k  = hill_saturation(x_below, k=1.2, ec=0.4)
        high_k = hill_saturation(x_below, k=3.0, ec=0.4)
        # At x << ec, higher k gives lower response (more convex initial phase)
        assert low_k[0] > high_k[0], "Higher k should give lower effect below ec."

    def test_output_length_preserved(self):
        x = np.linspace(0, 2, 100)
        result = hill_saturation(x, k=2.0, ec=0.5)
        assert result.shape == x.shape

    def test_invalid_k_raises(self):
        with pytest.raises(ValueError, match="k"):
            hill_saturation(np.array([1.0]), k=0.0, ec=0.5)
        with pytest.raises(ValueError, match="k"):
            hill_saturation(np.array([1.0]), k=-1.0, ec=0.5)

    def test_invalid_ec_raises(self):
        with pytest.raises(ValueError, match="ec"):
            hill_saturation(np.array([1.0]), k=2.0, ec=0.0)
        with pytest.raises(ValueError, match="ec"):
            hill_saturation(np.array([1.0]), k=2.0, ec=-0.5)

    @pytest.mark.parametrize("k,ec", [
        (2.5, 0.4),   # TV
        (1.5, 0.6),   # Paid Search
        (1.2, 0.7),   # Social
        (3.0, 0.3),   # Display
    ])
    def test_mapplethread_params(self, k, ec):
        """All four MapleThread Hill configurations should produce valid output."""
        x = np.linspace(0, 1.5, 200)
        result = hill_saturation(x, k=k, ec=ec)
        assert np.all(np.isfinite(result))
        assert np.all(result >= 0) and np.all(result <= 1.0 + 1e-10)

    def test_scalar_and_array_consistent(self):
        """Scalar x and single-element array x should give same result."""
        scalar_x = hill_saturation(np.array([0.5]), k=2.0, ec=0.5)
        array_x  = hill_saturation(np.linspace(0.5, 0.5, 1), k=2.0, ec=0.5)
        np.testing.assert_allclose(scalar_x, array_x)


# ══════════════════════════════════════════════════════════════════════════════
# transform_spend (full pipeline)
# ══════════════════════════════════════════════════════════════════════════════

class TestTransformSpend:

    def test_output_keys(self):
        result = transform_spend(SPEND_RANDOM, alpha=0.75, k=2.5, ec=0.4)
        assert set(result.keys()) == {"adstock", "adstock_norm", "saturated"}

    def test_output_shapes(self):
        result = transform_spend(SPEND_RANDOM, alpha=0.75, k=2.5, ec=0.4)
        for arr in result.values():
            assert arr.shape == SPEND_RANDOM.shape

    def test_saturated_bounded(self):
        result = transform_spend(SPEND_RANDOM, alpha=0.75, k=2.5, ec=0.4)
        sat = result["saturated"]
        assert np.all(sat >= 0) and np.all(sat <= 1.0 + 1e-10)

    def test_adstock_norm_p95_is_one(self):
        """Normalised adstock should have its 95th percentile at 1.0."""
        result = transform_spend(SPEND_RANDOM, alpha=0.5, k=2.0, ec=0.5)
        np.testing.assert_allclose(np.percentile(result["adstock_norm"], 95), 1.0, rtol=1e-6)

    def test_zero_spend_produces_near_zero_saturated(self):
        result = transform_spend(SPEND_ZEROS, alpha=0.5, k=2.0, ec=0.5)
        # Normalisation divides by 0, should fallback gracefully
        assert np.all(result["saturated"] < 1e-5)

    def test_weibull_mode_runs(self):
        result = transform_spend(
            SPEND_RANDOM,
            alpha=0.75, k=2.5, ec=0.4,
            use_weibull=True,
            weibull_shape=2.0,
            weibull_scale=3.0,
        )
        sat = result["saturated"]
        assert sat.shape == SPEND_RANDOM.shape
        assert np.all(sat >= 0) and np.all(sat <= 1.0 + 1e-10)

    def test_weibull_mode_missing_params_raises(self):
        with pytest.raises(ValueError, match="weibull_shape"):
            transform_spend(SPEND_RANDOM, alpha=0.5, k=2.0, ec=0.5, use_weibull=True)

    @pytest.mark.parametrize("alpha,k,ec", [
        (0.75, 2.5, 0.4),   # TV
        (0.20, 1.5, 0.6),   # Paid Search
        (0.45, 1.2, 0.7),   # Social
        (0.15, 3.0, 0.3),   # Display
    ])
    def test_all_mapplethread_channels(self, alpha, k, ec):
        result = transform_spend(SPEND_RANDOM, alpha=alpha, k=k, ec=ec)
        assert np.all(np.isfinite(result["saturated"]))
        assert np.all(result["saturated"] >= 0)


# ══════════════════════════════════════════════════════════════════════════════
# hill_derivative
# ══════════════════════════════════════════════════════════════════════════════

class TestHillDerivative:

    def test_non_negative_output(self):
        """Derivative of a monotone increasing function must be >= 0."""
        x = np.linspace(0, 5, 100)
        result = hill_derivative(x, k=2.0, ec=0.5)
        assert np.all(result >= 0)

    def test_zero_at_zero_x(self):
        """At x=0, derivative should be 0 (no spend → no marginal effect)."""
        result = hill_derivative(np.array([0.0]), k=2.0, ec=0.5)
        np.testing.assert_allclose(result[0], 0.0, atol=1e-8)

    def test_derivative_decreasing_past_inflection(self):
        """Past the inflection point, the derivative should be decreasing (diminishing returns)."""
        x = np.linspace(1.0, 10.0, 100)
        result = hill_derivative(x, k=2.0, ec=0.5)
        # All diffs should be negative in this region
        assert np.all(np.diff(result) < 0)

    def test_consistent_with_numerical_gradient(self):
        """Analytical derivative should match numerical gradient closely."""
        x = np.linspace(0.1, 3.0, 50)
        k, ec = 2.0, 0.5
        eps = 1e-6
        numerical = (hill_saturation(x + eps, k, ec) - hill_saturation(x - eps, k, ec)) / (2 * eps)
        analytical = hill_derivative(x, k, ec)
        np.testing.assert_allclose(analytical, numerical, rtol=1e-4)

    def test_output_finite(self):
        x = np.linspace(0, 5, 200)
        result = hill_derivative(x, k=2.5, ec=0.4)
        assert np.all(np.isfinite(result))